src/objects/Account__c.object
<CustomObject>
    <label>Account Custom View</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/AppDynamics_University_Voucher__c.object
<CustomObject>
    <description>Track Vouchers and Library Cards sent to customers to use in View Central LMS</description>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The account associated to these Vouchers</description>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>AppDynamics University Vouchers</relationshipLabel>
        <relationshipName>AppDynamics_University_Vouchers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>New_Expiration_Date__c</fullName>
        <label>New Expiration Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>AppDynamics University Vouchers</relationshipLabel>
        <relationshipName>AppDynamics_University_Vouchers</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>This is the Primary Contact from the Opportunity Contact Role.</description>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>AppDynamics University Vouchers</relationshipLabel>
        <relationshipName>AppDynamics_University_Vouchers</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Purchased_Quantity__c</fullName>
        <description>The number of vouchers or Library cards purchased</description>
        <label>Purchased Quantity</label>
        <precision>10</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <description>Type of Voucher</description>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Training Units</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Library Cards</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>AppDynamics University Voucher</label>
    <nameField>
        <displayFormat>{0000000000}</displayFormat>
        <label>AppDynamics University Voucher Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>AppDynamics University Vouchers</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Complex_Product__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>This custom setting will be used to breakdown the contents of a complex product.</description>
    <fields>
        <fullName>Number_of_Cards__c</fullName>
        <description>This is the number of Library Cards for this product.</description>
        <label>Number of Cards</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Number_of_Training_Units__c</fullName>
        <description>This is the number of training units for this product.</description>
        <label>Number of Training Units</label>
        <precision>6</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Code__c</fullName>
        <description>This is the product code</description>
        <label>Product Code</label>
        <length>100</length>
        <required>true</required>
        <type>Text</type>
    </fields>
    <label>Complex Product</label>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Self_Service_Pro_Trial__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Self-Service Pro Trial</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Booked_Date__c</fullName>
        <label>Booked Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/OpportunityLineItem.object
<CustomObject>
    <fields>
        <fullName>Product_Code__c</fullName>
        <formula>PricebookEntry.Product2.ProductCode</formula>
        <label>Product Code</label>
        <type>Text</type>
    </fields>
</CustomObject>

src/classes/JSButtonManagement.cls
global class JSButtonManagement {
  webservice static String createVouchers(Id opportunityId, String newExpirationdate)
    {
    map<String, Complex_Product__c> productMap =
      new map<String, Complex_Product__c>();
    list<AppDynamics_University_Voucher__c> vouchersToCreateList =
      new list<AppDynamics_University_Voucher__c>();
    Opportunity oppObj;
    Decimal totalCards = 0;
    Decimal totalTraining = 0;

    try {
      for (Complex_Product__c c : [Select Name,
                                          Product_Code__c,
                                          Number_of_Training_Units__c,
                                          Number_of_Cards__c
                                   From Complex_Product__c
                                   Where Number_of_Cards__c != null
                                   Or Number_of_Training_Units__c != null]) {
        productMap.put(c.Product_Code__c, c);
      }
    } catch (Exception e) {
      return 'No Card/Training mappings found';
    }
    try {
      oppObj = [Select Id,
                       AccountId,
                       StageName,
                       Booked_Date__c,
                       End_Date__c,
                       (Select Id,
                               Quantity,
                               PricebookEntryId,
                               PricebookEntry.ProductCode
                        From OpportunityLineItems
                        Where PricebookEntry.ProductCode IN
                          :productMap.keySet()),
                       (Select Id,
                               ContactId
                        From OpportunityContactRoles
                        Where IsPrimary = true
                        And Contact.Self_Service_Pro_Trial__c = false)
                From Opportunity
                Where Id = :opportunityId];
      if (oppObj.StageName != 'W10 - Closed/Won') {
        return 'This Opportunity is not in \'W10 - Closed/Won\' status.';
      }
    } catch (Exception e) {
      return 'Invalid Opportunity Id';
    }

    if (oppObj.OpportunityLineItems == null ||
        oppObj.OpportunityLineItems.isEmpty()) {
      return 'No Training Products exist on this Opportunity';
    } else {
      for (OpportunityLineItem oli : oppObj.OpportunityLineItems) {
        if (oli.Quantity != null &&
            productMap.get(oli.PricebookEntry.ProductCode) != null) {
          totalCards +=
            oli.Quantity *
            productMap.get(oli.PricebookEntry.ProductCode).Number_of_Cards__c;
          totalTraining +=
            oli.Quantity *
            productMap.get(oli.PricebookEntry.ProductCode).Number_of_Training_Units__c;
        }
      }
      if (totalCards > 0) {
        vouchersToCreateList.add(new AppDynamics_University_Voucher__c(
          Opportunity__c = oppObj.Id,
          Account__c = oppObj.AccountId,
          Primary_Contact__c =
            oppObj.OpportunityContactRoles != null &&
            !oppObj.OpportunityContactRoles.isEmpty() ?
              oppObj.OpportunityContactRoles[0].ContactId : null,
          New_Expiration_Date__c = Date.parse(newExpirationdate),
          Type__c = 'Library Cards',
          Purchased_Quantity__c = totalCards));
      }
      if (totalTraining > 0) {
        vouchersToCreateList.add(new AppDynamics_University_Voucher__c(
          Opportunity__c = oppObj.Id,
          Account__c = oppObj.AccountId,
          Primary_Contact__c =
            oppObj.OpportunityContactRoles != null &&
            !oppObj.OpportunityContactRoles.isEmpty() ?
              oppObj.OpportunityContactRoles[0].ContactId : null,
          Type__c = 'Training Units',
         New_Expiration_Date__c = Date.parse(newExpirationdate),
          Purchased_Quantity__c = totalTraining));
      }
      if (!vouchersToCreateList.isEmpty()) {
        try {
          insert vouchersToCreateList;
          return '/' + oppObj.Id;
        } catch (Exception e) {
          return e.getMessage();
        }
      }
    }

    return 'No Training Products exist on this Opportunity';
  }
}