src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Margin_Discount__c</fullName>
        <label>Margin Discount %</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Partner_Margin_Discount__c</fullName>
        <formula>SyncedQuote.Partner_Margin_Discount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner Margin Discount %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Partner_Margin__c</fullName>
        <description>The Partner Margin Discount for the Partner Account to which this Partner Opportunity is associated.</description>
        <formula>SyncedQuote.Contact.Account.Margin_Discount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner Margin</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Monthly__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Monthly</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>One_Time_Discount_Applied__c</fullName>
        <label>One Time Discount Applied</label>
        <picklist>
            <picklistValues>
                <fullName>True</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>False</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Partner_Margin_Applied__c</fullName>
        <description>Determines whether the partner margin is applied to the quote line item</description>
        <label>Partner Margin Applied</label>
        <picklist>
            <picklistValues>
                <fullName>True</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>False</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Perpetual_Support_Type__c</fullName>
        <inlineHelpText>This field is for Products from the Perpetual Support Product Family.</inlineHelpText>
        <label>Perpetual Support Type</label>
        <picklist>
            <controllingField>Family</controllingField>
            <picklistValues>
                <fullName>New Order</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Support_Pecent_per_Year__c</fullName>
        <label>Support Pecent per Year</label>
        <precision>5</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Volume_Discount_Applied__c</fullName>
        <label>Volume Discount Applied</label>
        <picklist>
            <picklistValues>
                <fullName>True</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>False</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>One_Time_Discount__c</fullName>
        <description>This is the one time discount price based on the line item</description>
        <label>One Time Discount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Partner_Margin_Discount__c</fullName>
        <label>Partner Margin Discount %</label>
        <precision>13</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Partner_Margin__c</fullName>
        <label>Partner Margin %</label>
        <precision>8</precision>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>Months__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Enter a value in this field only if the Product is Monthly.</inlineHelpText>
        <label>Months</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>One_Time_Discount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>One Time Discount %</label>
        <precision>11</precision>
        <scale>8</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Partner_Margin_Applied__c</fullName>
        <label>Partner Margin Applied</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Partner_Margin__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Partner Margin Discount %</label>
        <precision>13</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Perpetual_Support_Renewal_Price__c</fullName>
        <defaultValue>0</defaultValue>
        <inlineHelpText>Enter a value in this field only if the Product is Support Renewal for Perpetual Licenses</inlineHelpText>
        <label>Monthly Perpetual Support Renewal Price</label>
        <precision>18</precision>
        <scale>10</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Volume_Discount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>manual entry of the volume discount</description>
        <label>Volume Discount %</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/TestAccountRollupToQuote.cls
@IsTest(seeAlldata= true)
private class TestAccountRollupToQuote 
{
    static testMethod void testPartnerMarginAndNewOrderQuoteLineItem()
    {
        try
        {
        List<Account> accList;
        List<Contact> conList;
        List<Product2> prodList;
        List<PriceBookEntry> standardPriceList;
        List<PriceBookEntry> pbeList;
        List<QuoteLineItem> qliList;
        
        accList = new List<Account>{TestUtil.createAccounts(1, false)[0], TestUtil.createAccounts(1, false)[0]};
        AccountTriggerHandler obj = new AccountTriggerHandler();
        accList[1].RecordTypeId = obj.getAccountRecordType('Partner Account');
        insert accList;
        
        conList = new List<Contact>{TestUtil.createContacts(1, accList[0].Id, false)[0], TestUtil.createContacts(1, accList[1].Id, false)[0]};
        insert conList;
        
        Opportunity opp = TestUtil.createOpps(1, accList[0].Id, true)[0];
        
        Quote q = TestUtil.createQuotes(1, conList[1].Id, opp.Id, false)[0];
         
        Pricebook2 standardPB = [select id from Pricebook2 where isStandard = true];
        
        Pricebook2 pb = new Pricebook2(Name = 'Test Price Book', Description = ' Price Book', IsActive = true);
        insert pb;
        
        Product2 prod1 = new Product2(Name = '.NET Pro Edition On-Premise Subscription 1-11 Months', Family = 'On-Premise Subscription', IsActive = true,
                                    Partner_Margin_Applied__c = 'True', Monthly__c = true, One_Time_Discount_Applied__c = 'true', Volume_Discount_Applied__c = 'true'
                                    );
        
        Product2 prod2 = new Product2(Name = '.NET Test & Dev Edition On-Premise Perpetual', Family = 'Perpetual License', IsActive = true,
                                    Partner_Margin_Applied__c = 'True', Monthly__c = false, One_Time_Discount_Applied__c = 'true', Volume_Discount_Applied__c = 'true',
                                    Support_Pecent_per_Year__c = 20);
        
        Product2 prod3 = new Product2(Name = 'Support Renewal for Perpetual Licenses', Family = 'Perpetual Support', IsActive = true,
                                    Partner_Margin_Applied__c = 'True', Monthly__c = true, One_Time_Discount_Applied__c = 'true', Volume_Discount_Applied__c = 'true',
                                    Perpetual_Support_Type__c = 'Renewal');
        
        Product2 prod4 = new Product2(Name = 'Support for Perpetual Licenses - 20%/Yr', Family = 'Perpetual Support', IsActive = true,
                                    Partner_Margin_Applied__c = 'True', Monthly__c = true, One_Time_Discount_Applied__c = 'true', Volume_Discount_Applied__c = 'true',
                                    Support_Pecent_per_Year__c = 20, Perpetual_Support_Type__c = 'New Order');
        prodList = new List<Product2>{prod1,prod2,prod3,prod4};
        insert prodList;
        
        PricebookEntry standardPrice1 = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = prod1.Id, 
                                                          UnitPrice = 10000, IsActive = true, 
                                                          UseStandardPrice = false);
        
        PricebookEntry standardPrice2 = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = prod2.Id, 
                                                          UnitPrice = 10000, IsActive = true, 
                                                          UseStandardPrice = false);
        
        PricebookEntry standardPrice3 = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = prod3.Id, 
                                                          UnitPrice = 10000, IsActive = true, 
                                                          UseStandardPrice = false);
        
        PricebookEntry standardPrice4 = new PricebookEntry(Pricebook2Id = standardPB.Id, Product2Id = prod4.Id, 
                                                          UnitPrice = 10000, IsActive = true, 
                                                          UseStandardPrice = false);
        standardPriceList = new List<PriceBookEntry>{standardPrice1,standardPrice2,standardPrice3,standardPrice4};
        insert standardPriceList;
        
        PricebookEntry pbe1 = new PricebookEntry(Pricebook2Id = pb.Id, Product2Id = prod1.Id, 
                                                          UnitPrice = 10000, IsActive = true, 
                                                          UseStandardPrice = false);
        
        PricebookEntry pbe2 = new PricebookEntry(Pricebook2Id = pb.Id, Product2Id = prod2.Id, 
                                                          UnitPrice = 10000, IsActive = true, 
                                                          UseStandardPrice = false);
        
        PricebookEntry pbe3 = new PricebookEntry(Pricebook2Id = pb.Id, Product2Id = prod3.Id, 
                                                          UnitPrice = 10000, IsActive = true, 
                                                          UseStandardPrice = false);
        
        PricebookEntry pbe4 = new PricebookEntry(Pricebook2Id = pb.Id, Product2Id = prod4.Id, 
                                                          UnitPrice = 10000, IsActive = true, 
                                                          UseStandardPrice = false);
        pbeList = new List<PricebookEntry>{pbe1,pbe2,pbe3,pbe4};
        insert pbeList;
        
        q.Pricebook2Id = pb.Id;
        q.RecordTypeId = '01280000000Lref';
        q.Partner_Margin_Discount__c = 0;
        insert q;
        
        QuoteLineItem qli1 = TestUtil.createQLIs(1, q.Id, pbe1.Id, false)[0];
        QuoteLineItem qli2 = TestUtil.createQLIs(1, q.Id, pbe2.Id, false)[0];
        QuoteLineItem qli3 = TestUtil.createQLIs(1, q.Id, pbe3.Id, false)[0];
        QuoteLineItem qli4 = TestUtil.createQLIs(1, q.Id, pbe4.Id, false)[0];
        
        qli1.Quantity = 4;
        qli1.Months__c = 6;
        qli1.Volume_Discount__c = 15;
        qli1.One_Time_Discount__c = 5;
        qli1.Perpetual_Support_Renewal_Price__c = 0;
        
        qli2.Quantity = 2;
        qli2.Months__c = 0;
        qli2.Volume_Discount__c = 5;
        qli2.One_Time_Discount__c = 10;
        qli2.Perpetual_Support_Renewal_Price__c = 0;
        
        qli4.Quantity = 1;
        qli4.Months__c = 18;
        qli4.Volume_Discount__c = 0;
        qli4.One_Time_Discount__c = 0;
        qli3.Perpetual_Support_Renewal_Price__c = 350;
        
        qli3.Quantity = 3;
        qli3.Months__c = 9;
        qli3.Volume_Discount__c = 0;
        qli3.One_Time_Discount__c = 15;
        qli4.Perpetual_Support_Renewal_Price__c = 0;
        
        List<QuoteLineItem> qlis = new List<QuoteLineItem>{qli1,qli2,qli3,qli4};
        insert qlis;
        
        test.startTest();
        
        //QuoteLineItemFutureUpdate.counter = 0;
        
        accList[1].Margin_Discount__c = 20;
        update accList[1];
        
        //System.assertEquals(accList[1].Margin_Discount__c, [Select Partner_Margin_Discount__c from quote where Id = :q.Id].Partner_Margin_Discount__c);
        //System.assertEquals(accList[1].Margin_Discount__c, [Select Partner_Margin__c from QuoteLineItem where Id = :qli1.Id].Partner_Margin__c);
        
        Delete qli1;
        
        test.stopTest();
        }
        catch(Exception e)
        {
            System.debug('An error occured in running TestAccountToQuoteRollup class: '+e.getMessage());
        }
    }
}