src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner_Region__c</fullName>
        <description>General region where partner is located.</description>
        <inlineHelpText>This field is used to create mailing lists for partners in territories.</inlineHelpText>
        <label>Partner Region</label>
        <picklist>
            <picklistValues>
                <fullName>ANZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASEAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LATAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAmerica</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Partner_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Partner Campaigns</relationshipLabel>
        <relationshipName>Partner_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Region__c</fullName>
        <label>Partner Region</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Partner Campaign</label>
    <nameField>
        <displayFormat>PC-{0000}</displayFormat>
        <label>Partner Campaign Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/setUserCampaign.cls
public class setUserCampaign
{
    @future
    public static void createCampaign(Set<Id> userIds)
    {
        Map<Id, String> campaignMap = new Map<Id, String>();
        
        for(User u : [select Id, ContactId, COntact.Account.Partner_Region__c from User where COntact.Account.Partner_Region__c != null and Id in :userIds])
        {
            campaignMap.put(u.ContactId, u.COntact.Account.Partner_Region__c);
        }
        if(campaignMap.keyset().size() > 0 )
        {
            List<CampaignMember> members = new List<CampaignMember>();
            Map<String, Id> regionCampaignMap = new Map<String, Id>();
            for(Partner_Campaign__c partnerCampaign : [select Id, Campaign__c, Campaign__r.Name, Partner_Region__c from Partner_Campaign__c])
            {
                regionCampaignMap.put(partnerCampaign.Partner_Region__c, partnerCampaign.Campaign__c);
                
            }
            for(Id cntId : campaignMap.keyset())
            {
                String region = campaignMap.get(cntId);
                Id campaignId = regionCampaignMap.get(region);
                if(region != null && campaignId != null)
                {
                    CampaignMember partnerUserMember = new CampaignMember(CampaignId = campaignId, ContactId = cntId);
                    members.add(partnerUserMember);
                }
            }
            if(members.size() > 0)
            {
                insert members;
            }
        }
    }
    
    @future
    public static void deleteCampaign(set<Id> userIds)
    {
        Set<Id> cntIds = new Set<Id>();
        for(User u : [select Id, ContactId, COntact.Account.Partner_Region__c from User where COntact.Account.Partner_Region__c != null and Id in :userIds])
        {
            cntIds.add(u.ContactId);
        }
        Set<Id> regionCampaignIds = new Set<Id>();
        for(Partner_Campaign__c partnerCampaign : [select Id, Campaign__c, Campaign__r.Name, Partner_Region__c from Partner_Campaign__c])
        {
            regionCampaignIds.add(partnerCampaign.Campaign__c);            
        }
        delete [select Id from CampaignMember where CampaignId in :regionCampaignIds and ContactId in :cntIds]; 
    }
}