src/objects/Account__c.object
<CustomObject>
    <label>Account Custom View</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Zendesk__c.object
<CustomObject>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Zendesk</relationshipLabel>
        <relationshipName>Account_Zendesk</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <label>Account Zendesk</label>
    <nameField>
        <label>Account Zendesk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Zendesk</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Status__c.object
<CustomObject>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads Owners Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestZendeskScheduleJob.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestZendeskScheduleJob {
/*
    static testMethod void zendeskFailure() {
        // TO DO: implement unit test
        Account account  = new Account(Name = 'testOrg');
    	insert account;
    	Account_Zendesk__c az = new Account_Zendesk__c(name = 'testAZ',Account__c = account.Id,Status__c = 'FAILED');
        Test.startTest();
    	ZendeskScheduleJob zs = new ZendeskScheduleJob();
    	String jobId = System.schedule('testLicenseExpiryCheckJobTest',
            '0 0 0 3 9 ? 2022', 
            zs);
        Test.StopTest();
    }
    
    static testMethod void zendeskSuccess() {
        // TO DO: implement unit test
        Account account  = new Account(Name = 'testOrg1');
    	insert account;
    	Account_Zendesk__c az = new Account_Zendesk__c(name = 'testAZ',Account__c = account.Id,Status__c = 'SUCCESS');
        Test.startTest();
    	ZendeskScheduleJob_Success zs = new ZendeskScheduleJob_Success();
    	String jobId = System.schedule('testLicenseExpiryCheckJobTest',
            '0 0 0 3 9 ? 2022', 
            zs);
        Test.StopTest();
    }
    
    static testMethod void zendeskEmpty() {
        // TO DO: implement unit test
        Account account  = new Account(Name = 'testOrg2');
    	insert account;
        Test.startTest();
    	ZendeskScheduleJob_Empty zs = new ZendeskScheduleJob_Empty();
    	String jobId = System.schedule('testLicenseExpiryCheckJobTest',
            '0 0 0 3 9 ? 2022', 
            zs);
        Test.StopTest();
    }*/
}