src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License</label>
        <referenceTo>LicenseDetail__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PortalID__c</fullName>
        <label>PortalID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Account__c.object
<CustomObject>
    <label>Account Custom View</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>ADUAUserDetails__c</fullName>
        <label>ADUAUserDetails</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Docs__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Docs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Download__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Download Center</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LMS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>PortalID__c</fullName>
        <label>PortalID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZenDesk__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Help Center</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact_Portal_User__c.object
<CustomObject>
    <fields>
        <fullName>ADUAUserDetails__c</fullName>
        <label>ADUAUserDetails</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Contact Portal User</relationshipLabel>
        <relationshipName>Contact_Portal_User</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Docs__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Docs</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Download__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Download</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>LMS__c</fullName>
        <defaultValue>false</defaultValue>
        <label>LMS</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>User_Portal_Id__c</fullName>
        <label>User Portal Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ZenDesk__c</fullName>
        <defaultValue>false</defaultValue>
        <label>ZenDesk</label>
        <type>Checkbox</type>
    </fields>
    <label>Contact Portal User</label>
    <nameField>
        <label>Contact Portal User Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Contact Portal User</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DBLicenseContactTransaction__c.object
<CustomObject>
    <fields>
        <fullName>AccMgrUsr__c</fullName>
        <label>AccMgrUsr</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DBLicense__c</fullName>
        <label>DBLicense</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesRepUsr__c</fullName>
        <label>SalesRepUsr</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>DBLicenseContactTransaction</label>
    <nameField>
        <label>DBLicenseContactTransaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>DBLicenseContactTransactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/DBTuna_License__c.object
<CustomObject>
    <fields>
        <fullName>ExpiryDate__c</fullName>
        <label>ExpiryDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>LicenseKey__c</fullName>
        <label>LicenseKey</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>DBTunas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Server_Name__c</fullName>
        <label>Server Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>AppDynamics For Databases - License</label>
    <nameField>
        <label>License</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AppDynamics For Databases - License</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LicenseContactTransaction__c.object
<CustomObject>
    <fields>
        <fullName>AccMgrUsr__c</fullName>
        <label>AccMgrUsr</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <label>Account</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <label>License</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SalesRepUsr__c</fullName>
        <label>SalesRepUsr</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <label>LicenseContactTransaction</label>
    <nameField>
        <label>LicenseContactTransaction Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>LicenseContactTransactions</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LicenseDetail__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>License_BackendID__c</fullName>
        <label>License_BackendID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_Expiry_Date__c</fullName>
        <label>License Expiration Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Net_Agents__c</fullName>
        <label>.Net Agents Old</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>ProcessState__c</fullName>
        <label>Last Transaction Result</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAILED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Deployment Option</label>
        <picklist>
            <picklistValues>
                <fullName>On-Premise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosted (SaaS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosted (SaaS Lite)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Server_Agents__c</fullName>
        <label>Java Agents Old</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>TRIAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRIAL EXPIRED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAID EXPIRED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DISABLED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>License</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Deal_Type__c</fullName>
        <label>Deal Type</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Perpetual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expansion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth - (Co-Term)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LicenseContactsController.cls
public with sharing class LicenseContactsController {
    public LicenseContactsController(ApexPages.StandardController stdCtrlr){
        
    }
    
    public PageReference initAction(){
        String inputLicenseID = ApexPages.currentPage().getParameters().get('licenseId');
        String inputDBLicenseID = ApexPages.currentPage().getParameters().get('dblicenseId');
        LicenseContactTransaction__c licTrans = null;
        DBLicenseContactTransaction__c dbLicTrans = null;
        if(inputLicenseID!=null){
	        try{
	            licTrans = [Select Id,License__c, Account__c, AccMgrUsr__c,SalesRepUsr__c from LicenseContactTransaction__c where License__c=:inputLicenseID];
	        }catch(Exception e){
	        }
        }
        
        if(inputDBLicenseID!=null){
	        try{
	            dbLicTrans = [Select Id,DBLicense__c, Account__c, AccMgrUsr__c,SalesRepUsr__c from DBLicenseContactTransaction__c where DBLicense__c=:inputDBLicenseID];
	        }catch(Exception e){
	        }
        }
        
        String url = '';
        if(licTrans!=null){
            url = '/apex/ContactsBackend?licenseId='+inputLicenseID;
            String accId = licTrans.Account__c;
            //List<Contact> cts = null;
            List<Contact_Portal_User__c> cts = null;
            try{
                //cts = DataLayerConstants.fetchMultiple('Contact',' where AccountId=\''+accId+'\' and PortalID__c Like \'PENDING%\' LIMIT 10');
                cts = DataBase.query('Select Id,ADUAUserDetails__c,Contact__c,Docs__c,Download__c,LMS__c,User_Portal_Id__c,ZenDesk__c from Contact_Portal_User__c where Contact__r.accountid =: accId and User_Portal_Id__c like \'PENDING%\' LIMIT 10');//[Select Id,ADUAUserDetails__c,Contact__c,Docs__c,Download__c,LMS__c,User_Portal_Id__c,ZenDesk__c from Contact_Portal_User__c where Contact__r.accountid =: accId and User_Portal_Id__c like 'PENDING%' LIMIT 10];
            }catch(Exception e){
                   
            }
            if(cts!=null && cts.size()>0){
                url = '/apex/ContactsBackend?licenseId='+inputLicenseID;
            }else{
                delete licTrans;
                url = '/'+inputLicenseID;
            }
        }else if(inputLicenseID!=null){
            url = '/'+inputLicenseID; 
        }
        
        if(dbLicTrans!=null){
            url = '/apex/ContactsBackend?dblicenseId='+inputLicenseID;
            String accId = dbLicTrans.Account__c;
            //List<Contact> cts = null;
            List<Contact_Portal_User__c> cts = null;
            try{
                //cts = DataLayerConstants.fetchMultiple('Contact',' where AccountId=\''+accId+'\' and PortalID__c Like \'PENDING%\' LIMIT 10');
                cts = Database.query('Select Id,ADUAUserDetails__c,Contact__c,Docs__c,Download__c,LMS__c,User_Portal_Id__c,ZenDesk__c from Contact_Portal_User__c where Contact__r.accountid =: accId and User_Portal_Id__c like \'PENDING%\' LIMIT 10');//[Select Id,ADUAUserDetails__c,Contact__c,Docs__c,Download__c,LMS__c,User_Portal_Id__c,ZenDesk__c from Contact_Portal_User__c where Contact__r.accountid =: accId and User_Portal_Id__c like 'PENDING%' LIMIT 10];
            }catch(Exception e){}  
            if(cts!=null && cts.size()>0){
                url = '/apex/ContactsBackend?dblicenseId='+inputDBLicenseID;
            }else{
                delete dbLicTrans;
                url = '/'+inputDBLicenseID;
            }
        }else if(inputDBLicenseID!=null){
            url = '/'+inputDBLicenseID; 
        }
        
        ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.INFO,'URL is:'+url+' input license id:'+inputLicenseID);
        ApexPages.addMessage(myMsg);
        //return null;
        PageReference ref = new PageReference(url);
        ref.setRedirect(false); 
        return ref;
    }
    
    public static testMethod void testInitAction(){
    	LicenseDetail__c licDetail = [Select Id from LicenseDetail__c  limit 1];
    	String licenseId = licDetail.Id;
    	LicenseContactsController ctrlr = new LicenseContactsController(new ApexPages.Standardcontroller(licDetail));
    	ctrlr.initAction();
    	
    	Account acct = new Account();
    	Integer day  = System.now().date().day();
    	Integer month  = System.now().date().month();
    	Integer year = System.now().date().year();
    	acct.Name = day+'_'+month+'_'+year+'_acc1';
    	upsert acct;
    	
    	List<Contact> cts = new List<Contact>();
    	for(Integer i=0;i<20;i++){
    		Contact ct = new Contact();
    		ct.AccountId = acct.Id;
    		ct.LastName=acct.Name+'_'+i;
    		ct.Email = acct.Name+'_'+i+'@tarams.com';
    		ct.Download__c=true;
    		ct.ZenDesk__c = true;
    		cts.add(ct);
    	}
    	upsert cts;
    	Opportunity opp = new Opportunity();
    	opp.Name=acct.Name+'_Opp';
    	opp.CloseDate = System.now().date().addDays(20);
    	opp.StageName = 'A1 - Active';
    	opp.Probability = 80;
    	opp.AccountId = acct.Id;
    	opp.LeadSource = 'PPC';
    	upsert opp;
    	
    	LicenseDetail__c lic = new LicenseDetail__c();
    	lic.License_Expiry_Date__c = System.now().date().addDays(10);
    	lic.Product_Type__c = AppDConstants.LICENSE_PRODUCT_TYPE_ON_PREMISE;
    	lic.Server_Agents__c = 2;
    	lic.Stage__c = 'TRIAL';
    	lic.ProcessState__c = 'SUCCESS';
    	upsert lic;
    	
    	Apexpages.currentPage().getParameters().put('licenseId',lic.Id);
    	LicenseContactsController ctBckCtrlr = new LicenseContactsController(new Apexpages.Standardcontroller(new LicenseDetail__c()));
    	ctBckCtrlr.initAction();
    	
    	LicenseContactTransaction__c licTrans = new LicenseContactTransaction__c();
    	licTrans.Account__c = acct.Id;
    	licTrans.License__c = lic.Id;
    	licTrans.SalesRepUsr__c = UserInfo.getUserId();
    	licTrans.AccMgrUsr__c = acct.CreatedById;
    	upsert licTrans;
    	ctBckCtrlr.initAction();
    	
    	DBTuna_License__c dblicDetail = [Select Id from DBTuna_License__c limit 1];
    	String dblicenseId = dblicDetail.Id;
    	ContactsBackendController ctrlr2 = new ContactsBackendController(new ApexPages.Standardcontroller(dblicDetail));
    	ctrlr2.initAction();
    	
    	DBTuna_License__c dblic = new DBTuna_License__c();
    	dblic.ExpiryDate__c = System.now().date().addDays(10);
    	dblic.Server_Name__c = 'Test';
    	dblic.Opportunity__c = opp.id;
    	upsert dblic;
    	
    	Apexpages.currentPage().getParameters().put('dblicenseId',dblic.Id);
    	ContactsBackendController ctBckCtrlr2 = new ContactsBackendController(new Apexpages.Standardcontroller(new DBTuna_License__c()));
    	ctBckCtrlr2.initAction();
    	
    	DBLicenseContactTransaction__c dblicTrans = new DBLicenseContactTransaction__c();
    	dblicTrans.Account__c = acct.Id;
    	dblicTrans.dbLicense__c = dblic.Id;
    	dblicTrans.SalesRepUsr__c = UserInfo.getUserId();
    	dblicTrans.AccMgrUsr__c = acct.CreatedById;
    	upsert dblicTrans;
    	ctBckCtrlr2.initAction();
    }
    
    public static testMethod void testInitAction2(){
    	RESTAPI.unitTestMode = true;
    	Account standardAccount = new Account(Name='Test');
    	insert standardAccount;
    	Contact standardContact = new Contact(LastName='TestName',AccountId=standardAccount.id,Email='test@test.com');
    	insert standardContact;
    	
    	Contact_Portal_User__c contactPortalUser = null;
    	if(standardContact.getSObjects(BackendConstants.CONTACT_CHILD_RELATIONAL_NAME)==null || standardContact.getSObjects(BackendConstants.CONTACT_CHILD_RELATIONAL_NAME).size()==0){
			//contactPortalUser = new Contact_Portal_User__c(Contact__c=con.Id);
			contactPortalUser = new Contact_Portal_User__c();
			contactPortalUser.put('Contact__c',standardContact.Id);
			contactPortalUser.put('User_Portal_Id__c','PENDING');
			insert contactPortalUser;
    	}
    	 
    	Opportunity opp = new Opportunity(Name='TestOpp',StageName='A1 - Active',Deal_Type__c='New',LeadSource='Website',Accountid=standardAccount.id,CloseDate=System.now().date());
    	insert opp;
    	OpportunityContactRole opc = new OpportunityContactRole(Contactid=standardContact.id,Opportunityid = opp.id,isPrimary=true);
    	insert opc;
    	
    	DBTuna_License__c lic = new DBTuna_License__c();
    	lic.ExpiryDate__c = System.now().date().addDays(4);
    	lic.Server_Name__c = 'TestServerName';
    	lic.LicenseKey__c = 'aksdkladksadla';
    	lic.Opportunity__c = opp.id;
    	insert lic;
    	
    	DBLicenseContactTransaction__c dblicTrans = new DBLicenseContactTransaction__c();
    	dblicTrans.Account__c = standardAccount.Id;
    	dblicTrans.dbLicense__c = lic.Id;
    	dblicTrans.SalesRepUsr__c = UserInfo.getUserId();
    	dblicTrans.AccMgrUsr__c = standardAccount.CreatedById;
    	upsert dblicTrans;
    	
    	Apexpages.currentPage().getParameters().put('dblicenseId',lic.Id);
    	LicenseContactsController ctrlr = new LicenseContactsController(new ApexPages.Standardcontroller(new DBTuna_License__c()));
    	ctrlr.initAction();
    	
    }
    
    public static testMethod void testInitAction3(){
    	RESTAPI.unitTestMode = true;
    	Account standardAccount = new Account(Name='Test');
    	insert standardAccount;
    	Contact standardContact = new Contact(LastName='TestName',AccountId=standardAccount.id,Email='test@test.com');
    	insert standardContact;
    	
    	Contact_Portal_User__c contactPortalUser = null;
    	if(standardContact.getSObjects(BackendConstants.CONTACT_CHILD_RELATIONAL_NAME)==null || standardContact.getSObjects(BackendConstants.CONTACT_CHILD_RELATIONAL_NAME).size()==0){
			//contactPortalUser = new Contact_Portal_User__c(Contact__c=con.Id);
			contactPortalUser = new Contact_Portal_User__c();
			contactPortalUser.put('Contact__c',standardContact.Id);
			contactPortalUser.put('User_Portal_Id__c','PENDING');
			insert contactPortalUser;
    	}
    	 
    	Opportunity opp = new Opportunity(Name='TestOpp',StageName='A1 - Active',Deal_Type__c='New',LeadSource='Website',Accountid=standardAccount.id,CloseDate=System.now().date());
    	insert opp;
    	OpportunityContactRole opc = new OpportunityContactRole(Contactid=standardContact.id,Opportunityid = opp.id,isPrimary=true);
    	insert opc;
    	
    	LicenseDetail__c lic = new LicenseDetail__c();
            lic.Product_Type__c = 'On-Premise';
            lic.License_BackendID__c = '100';
            lic.License_Expiry_Date__c = System.now().date().addDays(15);
            lic.Product_Type__c = AppDConstants.LICENSE_PRODUCT_TYPE_ON_PREMISE;
            //lic.Server_Agents__c  = 10;
            //lic.Net_Agents__c  = 10;
            lic.Stage__c = 'TRIAL';
            insert lic;
    	
    	LicenseContactTransaction__c licTrans = new LicenseContactTransaction__c();
    	licTrans.Account__c = standardAccount.Id;
    	licTrans.License__c = lic.Id;
    	licTrans.SalesRepUsr__c = UserInfo.getUserId();
    	licTrans.AccMgrUsr__c = standardAccount.CreatedById;
    	upsert licTrans;
    	
    	Apexpages.currentPage().getParameters().put('licenseId',lic.Id);
    	LicenseContactsController ctrlr = new LicenseContactsController(new ApexPages.Standardcontroller(new LicenseDetail__c()));
    	ctrlr.initAction();
    	
    }
}