src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License</label>
        <referenceTo>LicenseDetail__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/License_Agent__c.object
<CustomObject>
    <description>License Agent which will have:
Agent Type as Java/.Net/PHP
and Agent count</description>
    <fields>
        <fullName>License__c</fullName>
        <label>License</label>
        <referenceTo>LicenseDetail__c</referenceTo>
        <relationshipLabel>License Agents</relationshipLabel>
        <relationshipName>License_Agents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>License Agent</label>
    <nameField>
        <label>License Units Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Agents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/License_EUM_Details__c.object
<CustomObject>
    <fields>
        <fullName>AccountName__c</fullName>
        <label>EUM Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Allow_Overages__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EUM Allow Overages</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>License to which this EUM details are associated with.</inlineHelpText>
        <label>License</label>
        <referenceTo>LicenseDetail__c</referenceTo>
        <relationshipLabel>License EUM Details</relationshipLabel>
        <relationshipName>License_EUM_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>EUM License Type</inlineHelpText>
        <label>EUM Type</label>
        <picklist>
            <picklistValues>
                <fullName>LITE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>License EUM Detail</label>
    <nameField>
        <label>License EUM Detail(s) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License EUM Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LicenseDetail__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Last_License_User__c</fullName>
        <description>Indicates User Id used for last license operation</description>
        <label>Last License User</label>
        <length>150</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_Time__c</fullName>
        <description>Indicates Last License Generation time. This field is to be used in association with Last Opcode field which indicates what is last license generation operation</description>
        <label>License Time</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>MAC_Address__c</fullName>
        <description>MAC Address of the machine to be registered with license</description>
        <label>MAC Address</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Pro_Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRO_PAID</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>License</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HALicenseController.cls
public with sharing class HALicenseController extends AbstractLicenseController{
    
    public String eumWebDisplayString{get;set;}
    public String eumMobileDisplayString{get;set;}
    
    public HALicenseController(ApexPages.StandardController stdCtrlr){
        super(stdCtrlr);
    }  
      
    private LicenseDetail__c oldLicense;
    public override virtual void init(){
        super.init();
        loggerHandle.setClassName(HALicenseController.class.getName());
        licenseOpCode = BackendConstants.OPCODE_HA_LICENSE;
        
        inputLicenseId = ApexPages.currentPage().getParameters().get('licenseId');
        if(inputLicenseId!=null){
            licenseDetailObj = (LicenseDetail__c)DataLayerConstants.fetchSingle('LicenseDetail__c',inputLicenseId);
        }
        eumInput = new LicenseEUMInput(null,null,null);
        if(licenseDetailObj!=null){
            oldLicense = licenseDetailObj;
            List<PortalDataType.LicenseAgentInfo> oldLicAgents = LicenseUtil.getLicenseAgentInfoList(oldLicense,-1);
            licenseDetailObj = LicenseUtil.createHALicense(oldLicense);
            licAgentInfoList = LicenseUtil.copyLicenseAgents(oldLicAgents,false);
            pageContextObj = licenseDetailObj;
            
            /*
            	Handling EUM records, if the licenses has EUM.
            */
            try{  
	        	licenseEUMDetails = (License_EUM_Details__c)DataLayerConstants.fetchSingleWithWhereClause('License_EUM_Details__c', ' where License__c = \''+oldLicense.Id+'\' and License__c!=null');
	        	
				if(licenseEUMDetails!=null){
					eumInput = LicenseUtil.getEUMLicenseInput(licenseEUMDetails);
					eumInput = LicenseUtil.createEUMLicense(eumInput,licenseDetailObj);
					if(eumInput.eumWeb!=null && eumInput.eumWeb.Type__c!=null){
						eumWebDisplayString = eumInput.eumWeb.Units__c+' '+eumInput.eumWeb.Type__c;
						if(eumInput.eumWeb.Units__c > 1){
							eumWebDisplayString +=' units';
						} else {
							eumWebDisplayString +=' unit';
						}
						if(eumInput.eumWeb.Allow_overages__c==false){
							eumWebDisplayString +=' without overages ';	
						} else{
							eumWebDisplayString +=' with overages ';
						}
					}
					if(eumInput.eumMobile!=null && eumInput.eumMobile.Type__c!=null){
						eumMobileDisplayString = eumInput.eumMobile.Units__c+' '+eumInput.eumMobile.Type__c;
						if(eumInput.eumMobile.Units__c > 1){
							eumMobileDisplayString +=' units';
						} else{
							eumMobileDisplayString +=' unit';
						}
						if(eumInput.eumMobile.Allow_overages__c==false){
							eumMobileDisplayString +=' without overages ';	
						} else{
							eumMobileDisplayString +=' with overages ';
						}
					}
				} 
        	}catch(Exception  e){
        		//Here, the flow comes to catch if License_EUM_Details__c query in line 28 fails to return zero records.
	        }
	        
        }
    }
    
    public override virtual Boolean validateObject(){
        if(licenseDetailObj==null){
            errorMessage = 'No License Data available, please try again.';
            return false;
        }
        String macAddress = licenseDetailObj.MAC_Address__c;
        if(macAddress==null || macAddress.trim().equals('')){
            errorMessage = 'Please provide Failover Node MAC Address to proceed with HA license creation.';
            return false;
        }
        if(!ValidatorUtil.isValidMacAddress(macAddress)){
            errorMessage = 'Please a valid MAC Address for failover.';
            return false;
        }
        return true;
    }
    public override virtual Boolean doPreSave(){
        super.doPreSave();
        upsert licenseDetailObj;
        
        /*
        	Inserting EUM records for HALicense.
        */
        if(eumInput.eumDetails!=null && eumInput.eumDetails.AccountName__c!=null){
			eumInput.eumDetails.License__c = licenseDetailObj.id;
			upsert eumInput.eumDetails;
			
			if(eumInput.eumWeb.License_EUM_Detail__c == null){
				eumInput.eumWeb.License_EUM_Detail__c = eumInput.eumDetails.id;
			}
			if(eumInput.eumMobile.License_EUM_Detail__c == null){
				eumInput.eumMobile.License_EUM_Detail__c = eumInput.eumDetails.id;
			} 
			upsert eumInput.eumWeb;
			upsert eumInput.eumMobile;
		}
        
        /*
        	Quering oldLicense state to insert details into license history tracking for HALicense 
        	and setting the delta values status.
        */
        oldLicenseState = (LicenseDetail__c)DataLayerConstants.fetchSingle('LicenseDetail__c', licenseDetailObj.id);
        deltaValues = false;
        
        return true;
    }
    public override virtual void setupBackend(){
        backend = new BackendLayer();
        licenseDetailObj.Name = oldLicense.Name+'_HA';
        List<Opportunity> opps = CommonUtil.getOpportunitiesForLicense(oldLicense);
        
        if(opps!=null && opps.size()>0){
            Opportunity opp = opps.get(0);
            accObj = opp.Account;
            List<ContactWrapper> licenseContacts= LicenseUtil.getLicenceContacts(oldLicense, opp, accObj, false);
            
            backend.addBackend(new LicenseBackend(licenseDetailObj,opp,accObj,licAgentInfoList,licenseContacts,eumInput,BackendConstants.OPCODE_HA_LICENSE));
        }
    }
    
    public PageReference doHaSave(){
        PageReference haPageReference = saveObject();
        if(haPageReference!=null){
			licenseDetailObj.Last_License_User__c = Userinfo.getUserId();
			licenseDetailObj.License_Time__c = System.now();        
			upsert licenseDetailObj;
			CommonUtil.copyOpportunities(oldLicense,licenseDetailObj);
			List<License_Agent__c> licAgents = new List<License_Agent__c>();
			try{
                for(PortalDataType.LicenseAgentInfo licAgentInfo:licAgentInfoList){
                    License_Agent__c licAgent = licAgentInfo.licAgent;//new License_Agent__c();
                    if(licAgent.License__c==null){
                        licAgent.License__c=licenseDetailObj.Id;
                    }
                    licAgents.add(licAgent);
				}
				upsert licAgents;
	        }catch(Exception e){
	            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL,e.getMessage()+'\n'+e.getStackTraceString());
	            ApexPages.addMessage(myMsg);
	        }
	        LicenseUtil.copyLicenseContacts(oldLicense,licenseDetailObj);
        }
        return haPageReference;
    }
    
    public override virtual PageReference doCancel(){
        if(oldLicense!=null && oldLicense.Id!=null){
            PageReference licensePage = new PageReference('/'+oldLicense.Id);
            licensePage.setRedirect(false);
            return licensePage;
        }
        return stdController.cancel();
    }
}