src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Geo__c</fullName>
        <formula>text(Territory_AppD__r.Geo__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Geo</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TEXT(Territory_AppD__r.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subsidiary__c</fullName>
        <inlineHelpText>Appdynamics, Inc. refers to all accounts in North and South America
Appdynamics UK2 refers to all accounts in Europe, Asia, Australia, and Africa</inlineHelpText>
        <label>Subsidiary</label>
        <picklist>
            <picklistValues>
                <fullName>AppDynamics, Inc.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AppDynamics UK2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Territory_AppD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory AppD</label>
        <referenceTo>Territory_AppD__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Geo__c</fullName>
        <label>Geo</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ROW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Worldwide</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LATAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alliances</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East (Federal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mid Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subsidiary__c</fullName>
        <description>Used for Validation rule(No Sub) wherein subsidiary on the account cannot be blank.</description>
        <formula>IF( ISPICKVAL(Account.Subsidiary__c, &apos;Appdynamics, Inc.&apos;),&apos;US&apos;, 
IF( ISPICKVAL(Account.Subsidiary__c, &apos;Appdynamics UK2&apos;),&apos;UK&apos;, 
IF( ISPICKVAL(Account.Subsidiary__c, &apos;&apos;),&apos;None&apos;,NULL)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subsidiary</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Territory_AppD__c.object
<CustomObject>
    <description>Used to manage lead/account routing.</description>
    <fields>
        <fullName>Assigned_To_ID__c</fullName>
        <label>Assigned To ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geo__c</fullName>
        <label>Geo</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ROW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Worldwide</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LATAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alliances</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East (Federal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mid Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestClassUtility.cls
public class TestClassUtility {
  public static Account createAccount() {
  
     Territory_AppD__c t = new Territory_AppD__c(Name = 'Test Territory',
                                                 Geo__c = 'North America',
                                                 Region__c = 'West',
                                                 Assigned_To_ID__c = '00580000006Aq0QAAS');
                                                   
     Account a = new Account(Name = 'Test Account',
                            BillingStreet = '303 2nd Street', 
                            BillingCity = 'San Francisco', 
                            BillingState = 'CA', 
                            BillingCountry= 'United States', 
                            //Territory_AppD__c = 'a1k34000001se1MAAQ',
                            Territory_AppD__c = t.Id,
                            Subsidiary__c = 'AppDynamics, Inc.');
    return a;
  }

  public static Opportunity createOpportunity(Account a) {
    Opportunity o = new Opportunity(
      Name = 'Test Opportunity',
      AccountId = a.Id,
      StageName = 'New',
      CloseDate = system.today());
    return o;
  }

  public static Product2 createProduct() {
    Product2 p = new Product2(Name = 'Test Product', ProductCode = 'Test Code');
    return p;
  }

  public static PricebookEntry createPricebookEntry(Pricebook2 pb, Product2 p) {
    PricebookEntry pe = new PricebookEntry(Pricebook2Id = pb.Id,
      Product2Id = p.Id, UnitPrice = 2, IsActive = true);
    return pe;
  }

  public static OpportunityLineItem createOpportunityLineItem(
      Opportunity o,
      PricebookEntry pbe) {
    OpportunityLineItem oli = new OpportunityLineItem(
      OpportunityId = o.Id,
      PricebookEntryId = pbe.Id,
      Quantity = 1,
      TotalPrice = 100);
    return oli;
  }
}