src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Geo__c</fullName>
        <formula>text(Territory_AppD__r.Geo__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Geo</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Margin_Discount__c</fullName>
        <label>Margin Discount %</label>
        <precision>7</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TEXT(Territory_AppD__r.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subsidiary__c</fullName>
        <inlineHelpText>Appdynamics, Inc. refers to all accounts in North and South America
Appdynamics UK2 refers to all accounts in Europe, Asia, Australia, and Africa</inlineHelpText>
        <label>Subsidiary</label>
        <picklist>
            <picklistValues>
                <fullName>AppDynamics, Inc.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AppDynamics UK2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Territory_AppD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory AppD</label>
        <referenceTo>Territory_AppD__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <recordTypes>
        <fullName>Contacts</fullName>
        <active>true</active>
        <description>Customer and Non-Partner Contact</description>
        <label>Customer Contact</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Geo__c</fullName>
        <label>Geo</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ROW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Worldwide</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Partner_Margin__c</fullName>
        <description>The Partner Margin Discount for the Partner Account to which this Partner Opportunity is associated.</description>
        <formula>SyncedQuote.Contact.Account.Margin_Discount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner Margin</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LATAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alliances</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East (Federal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mid Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Subsidiary__c</fullName>
        <description>Used for Validation rule(No Sub) wherein subsidiary on the account cannot be blank.</description>
        <formula>IF( ISPICKVAL(Account.Subsidiary__c, &apos;Appdynamics, Inc.&apos;),&apos;US&apos;, 
IF( ISPICKVAL(Account.Subsidiary__c, &apos;Appdynamics UK2&apos;),&apos;UK&apos;, 
IF( ISPICKVAL(Account.Subsidiary__c, &apos;&apos;),&apos;None&apos;,NULL)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subsidiary</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>One_Time_Discount_Percentage__c</fullName>
        <defaultValue>0</defaultValue>
        <description>The One Time Discount to be applied to the Total Price of the Quote.</description>
        <inlineHelpText>Enter a One Time Discount to be applied against the Total Price of the Quote</inlineHelpText>
        <label>One Time Discount %</label>
        <precision>16</precision>
        <scale>13</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>One_Time_Discount__c</fullName>
        <description>This is the one time discount price based on the line item</description>
        <label>One Time Discount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Partner_Margin__c</fullName>
        <label>Partner Margin %</label>
        <precision>8</precision>
        <scale>5</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>One_Time_Discount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>One Time Discount %</label>
        <precision>11</precision>
        <scale>8</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Partner_Margin__c</fullName>
        <defaultValue>0</defaultValue>
        <label>Partner Margin Discount %</label>
        <precision>13</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Volume_Discount__c</fullName>
        <defaultValue>0</defaultValue>
        <description>manual entry of the volume discount</description>
        <label>Volume Discount %</label>
        <precision>18</precision>
        <scale>15</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Territory_AppD__c.object
<CustomObject>
    <description>Used to manage lead/account routing.</description>
    <fields>
        <fullName>Assigned_To_ID__c</fullName>
        <label>Assigned To ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geo__c</fullName>
        <label>Geo</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ROW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Worldwide</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LATAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alliances</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East (Federal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mid Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestUtil.cls
@isTest
public class TestUtil {
    public static List<Quote> createQuotes( Integer numToInsert, Id contactId, Id oppId, Boolean doInsert ) {
        RecordType rec = [ Select Id from RecordType where SObjectType='Quote' and Name = 'New Customer Quote'][0];
        List<Quote> quotes = new List<Quote>();
        for( Integer i=0; i< numToInsert; i++ ) {
            Quote q = new Quote();
            q.Name = 'TestQuote'+i;
            q.ContactId = contactId;
            q.RecordTypeId = rec.Id;
            q.OpportunityId = oppId;
            q.One_Time_Discount_Percentage__c = 0;
            quotes.add(q);
        }
        if( doInsert )
            insert quotes;
        return quotes;
    }
    
    public static List<QuoteLineItem> createQLIs( Integer numToInsert, Id quoteId ,Id priceBookEntryId, Boolean doInsert ) {
        List<QuoteLineItem> qlis = new List<QuoteLineItem>();
        for( Integer i=0; i< numToInsert; i++ ) {
            QuoteLineItem q = new QuoteLineItem();
            q.priceBookEntryId = priceBookEntryId;
            q.quoteId = quoteId;
            q.Quantity = 1;
            q.UnitPrice = 100;
            q.Volume_Discount__c = 0;
            q.Partner_Margin__c = 0;
            q.One_Time_Discount__c = 0;
            qlis.add( q );
        }
        if( doInsert )
            insert qlis;
        return qlis;
    }
    
    public static List<Contact> createContacts( Integer numToInsert, Id accountId, Boolean doInsert  ) {
        List<Contact> contacts = new List<Contact>();
        for( Integer i=0; i< numToInsert; i++ ){
            Contact c = new Contact();
            c.FirstName = 'Test';
            c.LastName = 'Name' + i;
            c.AccountId = accountId;
            c.MailingStreet = '302 Second Street';
            c.MailingCity = 'San Francisco';
            c.MailingPostalCode = '94100';
            c.MailingState = 'CA';
            c.MailingCountry = 'United States';
            
            contacts.add( c );
        }
        
        if( doInsert )
            insert contacts;
        return contacts;
    }
    
    public static List<Account> createAccounts( Integer numToInsert, Boolean doInsert  ) {
        List<Account> accounts = new List<Account>();
        
        Territory_AppD__c t = new Territory_AppD__c(Name = 'Test Territory',
                                                 Geo__c = 'North America',
                                                 Region__c = 'West',
                                                 Assigned_To_ID__c = '00580000006Aq0QAAS');
        insert t;
        
        for( Integer i=0; i< numToInsert; i++ ){
            Account a = new Account();
            a.Name = 'Test Account' + i;
            a.BillingStreet = '303 2nd Street';
            a.BillingCity = 'San Francisco';
            a.BillingState = 'CA'; 
            a.BillingCountry= 'United States'; 
            //a.Territory_AppD__c = 'a1k34000001se1MAAQ';
            a.Territory_AppD__c = t.Id;
            a.Subsidiary__c = 'AppDynamics, Inc.';
            a.Margin_Discount__c = 0;// Enhancement - This margin discount will be copied over to Quote & Quote Line items
            accounts.add( a );
        }
        
        if( doInsert )
            insert accounts;
        return accounts;
    }
    
    public static List<Opportunity> createOpps( Integer numToInsert, Id accId, Boolean doInsert  ) {
        List<Opportunity> opps = new List<Opportunity>();
        for( Integer i=0; i< numToInsert; i++ ){
            Opportunity o = new Opportunity();
            o.Name = 'Test Opp' + i;
            o.StageName = 'New';
            o.CloseDate = Date.Today().addMonths(1);
            o.AccountId = accId;
            opps.add( o );
        }
        
        if( doInsert )
            insert opps;
        return opps;
    }
    
}