src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACE_Architect__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ACE Architect</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Customer Success Rep</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>PortalID__c</fullName>
        <label>PortalID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Technical_Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technical Account Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>AppD Customer Success</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Account__c.object
<CustomObject>
    <label>Account Custom View</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Zendesk__c.object
<CustomObject>
    <fields>
        <fullName>ACE_Architect__c</fullName>
        <label>ACE Architect</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Zendesk</relationshipLabel>
        <relationshipName>Account_Zendesk</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>Account Zendesk</label>
    <nameField>
        <label>Account Zendesk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Zendesk</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZendeskScheduleJob_Empty.cls
global class ZendeskScheduleJob_Empty implements Schedulable {
	global void execute(SchedulableContext SC) {
		/*List<Account> accountsList = new List<Account>();
		List<Account> accountsNotInZendesk = [select Id, ACE_Architect__c, Technical_Account_Manager__c from Account where PortalID__c != null and ID NOT IN(Select Account__c from Account_Zendesk__c)];
		
		//List<Account> aaa = [select Id,(select Id, Account__c from Account_Zendesk__r) from Account_Zendesk__c];
		for(Account account:accountsNotInZendesk){
			if(!ZendeskBackend.checkIf_ACE_TAM_NULL(account)){
           		if(accountsList.size()<2){
           			accountsList.add(account);
           		} else{
           			break;
           		}
           }
		}
		if(accountsList.size()>0){
			for(Account account:accountsList){
				ZendeskBackend.checkTriggerDetails(account);
			}
		}*/
	}
}