src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>ACE_Architect__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>ACE Architect</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.UserRole.Name</field>
                <operation>equals</operation>
                <value>Customer Success Rep</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Technical_Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technical Account Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>AppD Customer Success</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Account__c.object
<CustomObject>
    <label>Account Custom View</label>
    <nameField>
        <label>Account Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Accounts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Account_Zendesk__c.object
<CustomObject>
    <fields>
        <fullName>ACE_Architect__c</fullName>
        <label>ACE Architect</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Account__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Account</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Account Zendesk</relationshipLabel>
        <relationshipName>Account_Zendesk</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Description__c</fullName>
        <label>Description</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>OP_CODE__c</fullName>
        <label>OP CODE</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Organisation_Id__c</fullName>
        <label>Organisation Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SE__c</fullName>
        <label>SE</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>TAM__c</fullName>
        <label>TAM</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Trigger_Id__c</fullName>
        <label>Trigger Id</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Account Zendesk</label>
    <nameField>
        <label>Account Zendesk Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Account Zendesk</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Status__c.object
<CustomObject>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads Owners Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ZendeskScheduleJob_Success.cls
global class ZendeskScheduleJob_Success implements Schedulable {
	global void execute(SchedulableContext SC) {
		/*List<Account> accountsList = new List<Account>();
		List<Account_Zendesk__c> accountZendesks = [select Id, Account__c, Account__r.ACE_Architect__c, Account__r.ACE_Architect__r.Email, Account__r.CreatedBy.Email, Account__r.Technical_Account_Manager__c, Account__r.Technical_Account_Manager__r.Email, Description__c, OP_CODE__c, Organisation_Id__c, Status__c, Trigger_Id__c, ACE_Architect__c, TAM__c, SE__c from Account_Zendesk__c where Status__c in ('SUCCESS')];
		for(Account_Zendesk__c az:accountZendesks){
           //Account account = [select Id, Name , ACE_Architect__c, ACE_Architect__r.Email, CreatedBy.Email, Technical_Account_Manager__c, Technical_Account_Manager__r.Email from Account where id =:az.Account__c];
           //ZendeskBackend.checkTriggerDetails(account);
           if(ZendeskBackend.checkIf_ACE_TAM_Changed(az.Account__r, az)){
           		if(accountsList.size()<2){
           			accountsList.add(az.Account__r);
           		} else{
           			break;
           		}
           }
		}
		if(accountsList.size()>0){
			for(Account account:accountsList){
				ZendeskBackend.checkTriggerDetails(account);
			}
		}*/
	}
}