src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Partner_Region__c</fullName>
        <description>General region where partner is located.</description>
        <inlineHelpText>This field is used to create mailing lists for partners in territories.</inlineHelpText>
        <label>Partner Region</label>
        <picklist>
            <picklistValues>
                <fullName>ANZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ASEAN</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LATAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NAmerica</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Partner_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Partner Campaigns</relationshipLabel>
        <relationshipName>Partner_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Region__c</fullName>
        <label>Partner Region</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Partner Campaign</label>
    <nameField>
        <displayFormat>PC-{0000}</displayFormat>
        <label>Partner Campaign Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/NewEditPartnerCampaignController.cls
global class NewEditPartnerCampaignController
{    
    private String partnerCampaignId = ApexPages.currentpage().getparameters().get('id');
    
    public NewEditPartnerCampaignController()
    {
        PartnerCampaign = new Partner_Campaign__c();
        if(partnerCampaignId != null && partnerCampaignId instanceOf ID)
        {
            PartnerCampaign = [select Id, Campaign__c, Campaign__r.Name, Partner_Region__c from Partner_Campaign__c where Id = :partnerCampaignId];
        }
    }
    
    public Partner_Campaign__c PartnerCampaign { get; set; }
    
    public List<SelectOption> getPartnerRegions()
    {
        List<SelectOption> results = new List<SelectOption>();
        Schema.DescribeFieldResult regions = Account.Partner_Region__c.getDescribe();
        for(Schema.PicklistEntry entry : regions.getPicklistValues())
        {
            results.add(new SelectOption(entry.getValue(), entry.getValue()));
        }
        return results;
    }
    
    public List<SelectOption> getAllActiveCampaigns()
    {
        List<SelectOption> results = new List<SelectOption>();
        
        for(Campaign cam : [select Id, Name from Campaign where IsActive = true])
        {
            results.add(new SelectOption(cam.Id, cam.Name));
        }
        return results;
    }
    
    public PageReference cancel()
    {
        PageReference retPage = new PageReference('/apex/PartnerCampaigns');
        retPage.setRedirect(true);
        return retPage; 
    }
    
    @RemoteAction
    global static List<Campaign> searchCampaigns(String campaignNameKeyword)
    {
        String keyword = '%' + campaignNameKeyword + '%';
        return [select Id, Name from Campaign where Name like :keyword limit 1000];
    }
    
    public PageReference savePartnerCampaign()
    {
        
        Set<String> hasCampaignRegions = new Set<String>();
        for(Partner_Campaign__c thispartnerCampaign : [select Id, Campaign__c, Campaign__r.Name, Partner_Region__c from Partner_Campaign__c where Id != :PartnerCampaign.Id])
        {
            hasCampaignRegions.add(thispartnerCampaign.Partner_Region__c);
        }
        if(hasCampaignRegions.contains(PartnerCampaign.Partner_Region__c))
        {
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.ERROR, PartnerCampaign.Partner_Region__c + ' already has a campaign, please select another Account Region.'));
        }
        else
        {        
            upsert PartnerCampaign;
            ApexPages.addMessage(new ApexPages.Message(ApexPages.Severity.INFO, 'Partner Campaign was saved.'));
        }
        //PageReference retPage = new PageReference('/apex/NewEditPartnerCampaign?id=' + PartnerCampaign.Id);
        //retPage.setRedirect(true);
        return null; 
    }
}