src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Territory_AppD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory AppD</label>
        <referenceTo>Territory_AppD__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <picklist>
            <picklistValues>
                <fullName>Northeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federal Gov.</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <recordTypes>
        <fullName>Contacts</fullName>
        <active>true</active>
        <description>Customer and Non-Partner Contact</description>
        <label>Customer Contact</label>
    </recordTypes>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Territory_AppD__c.object
<CustomObject>
    <description>Used to manage lead/account routing.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Assigned_To_ID__c</fullName>
        <label>Assigned To ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_To_Type__c</fullName>
        <label>Assigned To Type</label>
        <picklist>
            <picklistValues>
                <fullName>User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Queue</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <label>Assigned To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>This field determines the order in which Lead Territories are reviewed for Lead Assignment.</description>
        <label>Order</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Federal Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geography</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Source</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Named Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Territory_Field_Criteria__c.object
<CustomObject>
    <description>Criteria of Lead Territory based on Lead Fields.</description>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <referenceTo>Territory_AppD__c</referenceTo>
        <relationshipLabel>Territory Field Criterias</relationshipLabel>
        <relationshipName>Territory_Field_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Territory Field Criteria</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Territory Field Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Field Criterias</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Territory_Geography__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <referenceTo>Territory_AppD__c</referenceTo>
        <relationshipLabel>Territory Geographies</relationshipLabel>
        <relationshipName>Territory_Geographies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zip_End__c</fullName>
        <label>Zip End</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Start__c</fullName>
        <label>Zip Start</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Territory Geography</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Territory Geography Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Geographies</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/assignOneAccountToTerritoryHelper.cls
public class assignOneAccountToTerritoryHelper
{
    public static void assignTerritory(String accountQuery)
    {
        List<Account> accts = (List<Account>)database.query(accountQuery);
        system.debug('###' + accts);
        Id accountTerritoryRecordTypeId = [select Id from RecordType where SobjectType = 'Territory_AppD__c' and Name = 'Account' limit 1].Id;
        //List<Territory_AppD__c> allAccountTerritories = c];
        Account thisAcct = accts[0];
        for(Territory_AppD__c acctTerritory : [select Id, Name, Type__c,  Assigned_To__c, Assigned_To_ID__c, Assigned_To_Type__c, Order__c, 
            (select Territory__c, Country__c, State__c, Zip_End__c, Zip_Start__c from Territory_Geographies__r order by Country__c, State__c),
            (select Territory__c, Field__c, Operator__c, Value__c from Territory_Field_Criteria__r order by Field__c )
            from Territory_AppD__c where RecordTypeId = :accountTerritoryRecordTypeId and Active__c = true and Effective_Date__c <= :Date.today() order by Order__c])
        {
            if( acctTerritory.Territory_Geographies__r.size() > 0 || acctTerritory.Territory_Field_Criteria__r.size() > 0 )
            {
                Boolean isMatchTerField = false;
                Boolean isFindTerritory = false;
                if(acctTerritory.Territory_Geographies__r.size() == 0)
                {
                    isFindTerritory = true;
                }
                else
                {
                    String country = thisAcct.BillingCountry != null ? thisAcct.BillingCountry.toLowerCase() : '';
                    String state = thisAcct.BillingState != null ? thisAcct.BillingState.toLowerCase() : '';
                    String postalCode = thisAcct.BillingPostalCode != null ? thisAcct.BillingPostalCode.toLowerCase() : '';
                    String countryState = country + '/' + state;
                    String justCountry = country + '/';
                    map<String, List<Territory_Geography__c>> countryStateToGeosMap = new map<String, List<Territory_Geography__c>>();
                    Boolean justCountryGeo = false;
                    for(Territory_Geography__c acctgeo : acctTerritory.Territory_Geographies__r)
                    {
                        String theCountryState = (acctgeo.Country__c != null ? acctgeo.Country__c.toLowerCase() : '') + '/' + (acctgeo.State__c != null?acctgeo.State__c.toLowerCase():'');
                        if(countryStateToGeosMap.containsKey(theCountryState))
                        {
                            countryStateToGeosMap.get(theCountryState).add(acctgeo);
                        }
                        else
                        {
                            countryStateToGeosMap.put(theCountryState, new List<Territory_Geography__c> {acctgeo});
                        }
                    }
                    system.debug('###' + countryStateToGeosMap);
                    system.debug('###' + countryState);
                    system.debug('###' + justCountry);
                    String theMapKey = countryState;
                    if(countryStateToGeosMap.containsKey(justCountry))
                    {
                        theMapKey = justCountry;
                    }
                    List<Territory_Geography__c> theCountryStateGeos = countryStateToGeosMap.get(theMapKey);
                    system.debug('###' + theCountryStateGeos);
                    if(theCountryStateGeos != null && theCountryStateGeos.size() > 0)
                    {
                        for(Territory_Geography__c theCountryStateGeo : theCountryStateGeos)
                        {
                            if(isInPostalRange(thisAcct.BillingPostalCode, theCountryStateGeo.Zip_Start__c, theCountryStateGeo.Zip_End__c))
                            {
                                isFindTerritory = true;
                                break;
                            }
                        }
                    }
                }
                system.debug('###' + isFindTerritory);
                if(isFindTerritory)
                {
                    if(acctTerritory.Territory_Field_Criteria__r.size() == 0)
                    {
                        isMatchTerField = true;
                    }
                    else
                    {
                        Boolean isPassTheFieldCriteria = true;
                        for(Territory_Field_Criteria__c criteria: acctTerritory.Territory_Field_Criteria__r)
                        {
                            String thisFieldName = criteria.Field__c; 
                            //STring thisFieldValue = thisLead.get(thisFieldName);
                            Schema.DisplayType type = GlobalVariables.AccountFieldTypeMap.get(thisFieldName);
                            if(type == Schema.DisplayType.Boolean)
                            {
                                Boolean criteriaValue = criteria.Value__c == null || criteria.Value__c.toLowerCase() == 'false' ? false : true;
                                Boolean fieldValue = Boolean.valueOf(thisAcct.get(thisFieldName));
                                if(criteria.Operator__c.toLowerCase() == 'equals' && fieldValue != criteriaValue)
                                {
                                    isPassTheFieldCriteria = false;
                                }
                                else if(criteria.Operator__c.toLowerCase() == 'not equal to' && fieldValue == criteriaValue)
                                {
                                    isPassTheFieldCriteria = false;
                                }
                            }
                            else if(type == Schema.DisplayType.Currency || type == Schema.DisplayType.Integer || type == Schema.DisplayType.Percent || type == Schema.DisplayType.Double)
                            {
                                try
                                {
                                    Decimal criteriaValue = criteria.Value__c == null ? null : Decimal.valueOf(criteria.Value__c);
                                    Decimal fieldValue = thisAcct.get(thisFieldName) == null ? null : Decimal.valueOf(Double.valueOf(thisAcct.get(thisFieldName)));
                                    if(criteria.Operator__c.toLowerCase() == 'equals' && fieldValue != criteriaValue)
                                    {
                                        isPassTheFieldCriteria = false;
                                    }
                                    else if(criteria.Operator__c.toLowerCase() == 'not equal to' && fieldValue == criteriaValue)
                                    {
                                        isPassTheFieldCriteria = false;
                                    }
                                    else
                                    {} 
                                }
                                catch(Exception ex)
                                {
                                    isPassTheFieldCriteria = false;
                                }
                            }
                            else if(type == Schema.DisplayType.DateTime)
                            {
                                 DateTime criteriaValue = null;
                                if(criteria.Value__c != null)
                                {
                                    String[] dates = criteria.Value__c.split('/');
                                    criteriaValue = DateTime.newInstance(Integer.valueOf(dates[2]), Integer.valueOf(dates[0]), Integer.valueOf(dates[1]));
                                }
                                DateTime fieldValue = thisAcct.get(thisFieldName) == null ? null : DateTime.valueOf(thisAcct.get(thisFieldName));
                                if(criteria.Operator__c.toLowerCase() == 'equals' && fieldValue != criteriaValue)
                                {
                                    isPassTheFieldCriteria = false;
                                }
                                else if(criteria.Operator__c.toLowerCase() == 'not equal to' && fieldValue == criteriaValue)
                                {
                                    isPassTheFieldCriteria = false;
                                }                                
                                else
                                {} 
                            }
                            else if(type == Schema.DisplayType.Date)
                            {
                                Date criteriaValue = null;
                                if(criteria.Value__c != null)
                                {
                                    String[] dates = criteria.Value__c.split('/');
                                    criteriaValue = Date.newInstance(Integer.valueOf(dates[2]), Integer.valueOf(dates[0]), Integer.valueOf(dates[1]));
                                }
                                Date fieldValue = thisAcct.get(thisFieldName) == null ? null : Date.valueOf(thisAcct.get(thisFieldName));
                                if(criteria.Operator__c.toLowerCase() == 'equals' && fieldValue != criteriaValue)
                                {
                                    isPassTheFieldCriteria = false;
                                }
                                else if(criteria.Operator__c.toLowerCase() == 'not equal to' && fieldValue == criteriaValue)
                                {
                                    isPassTheFieldCriteria = false;
                                }
                                else
                                {
                                }
                            }
                            else
                            {
                                String criteriaValue = criteria.Value__c == null ? '' : criteria.Value__c.trim().toLowerCase();
                                String fieldValue = thisAcct.get(thisFieldName) == null ? '' : String.valueOf(thisAcct.get(thisFieldName)).trim().toLowerCase();
                                Set<String> values = new Set<String>();
                                
                                for(String value : criteriaValue.split(','))
                                {
                                    //if(value.trim().toLowerCase() != '')
                                    //{
                                        values.add(value.trim().toLowerCase());
                                    //}  
                                }
                                system.debug('###1' + fieldValue);
                                system.debug('###2' + values);
                                if(criteria.Operator__c.toLowerCase() == 'equals' && !values.contains(fieldValue))
                                {
                                    isPassTheFieldCriteria = false;
                                }
                                else if(criteria.Operator__c.toLowerCase() == 'not equal to' && values.contains(fieldValue))
                                {
                                    isPassTheFieldCriteria = false;
                                }
                            }
                            system.debug('###' + isPassTheFieldCriteria);
                            if(!isPassTheFieldCriteria)
                            {
                                break;
                            }
                        }
                        isMatchTerField = isPassTheFieldCriteria;
                    }
                }
                if(isMatchTerField && isFindTerritory )
                {
                    thisAcct.Territory_AppD__c = acctTerritory.Id;
                    Id acctNewOwnerId = acctTerritory.Assigned_To_ID__c;                   
                    thisAcct.OwnerId = acctNewOwnerId;
                    update thisAcct;
                    for(Contact ct : thisAcct.Contacts)
                    {
                        ct.OwnerId = acctNewOwnerId;
                    }
                    update thisAcct.Contacts;
                    break;
                }
            }            
        }
    }
    
    private static Boolean isInPostalRange(String postalCode, String postalStart, String postalEnd)
    {
        if(postalStart == null && postalEnd == null)
        {
            return true;
        }
        // When PostalCode is NULL, and PostalStart or PostalEnd is NOT NULL.
        if(postalCode == null)
        {
            return false;
        }            
        
        if(postalStart != null && postalEnd != null)
        {
            return (postalCode.compareTo(postalStart) >= 0 && postalCode.compareTo(postalEnd) <= 0); 
        }
        return false;        
    }
}