src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Account_Balance__c</fullName>
        <description>Total Account Balance from NetSuite.</description>
        <label>Account Balance</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>X500K_Email_Sent__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This field is checked when an email for the account surpassing $500K in bookings has been sent.</description>
        <label>500K Email Sent</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/testAssignAccountTerritoryController.cls
@isTest
public class testAssignAccountTerritoryController
{
    @isTest
    static void testController()
    {
         Id standardAccountRecordTypeId = [select Id from RecordType where SobjectType = 'Account' and Name = 'Standard Account' limit 1].Id;
        Account testAccount = new Account(name = 'acme', Industry='Education', BillingCOuntry = 'USA', X500K_Email_Sent__c = true, Account_Balance__c = 100000, BillingState = 'CA', BillingPostalCode = '1500', RecordTypeId = standardAccountRecordTypeId);
        insert testAccount;
        PageReference testPage = new PageReference('/apex/AssignAccountTerritory?id=' + testAccount.Id);
        test.setCurrentPage(testPage);
        AssignAccountTerritoryCOntroller controller = new AssignAccountTerritoryCOntroller();
        controller.assignTerritory();
    }
}