src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>Geo__c</fullName>
        <formula>text(Territory_AppD__r.Geo__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Geo</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <formula>TEXT(Territory_AppD__r.Region__c)</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Region</label>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Subsidiary__c</fullName>
        <inlineHelpText>Appdynamics, Inc. refers to all accounts in North and South America
Appdynamics UK2 refers to all accounts in Europe, Asia, Australia, and Africa</inlineHelpText>
        <label>Subsidiary</label>
        <picklist>
            <picklistValues>
                <fullName>AppDynamics, Inc.</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>AppDynamics UK2</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Territory_AppD__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Territory AppD</label>
        <referenceTo>Territory_AppD__c</referenceTo>
        <relationshipLabel>Accounts</relationshipLabel>
        <relationshipName>Accounts</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/OppAutoRenewSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings to use for Opportunity Auto Renewal</description>
    <fields>
        <fullName>Id__c</fullName>
        <description>Salesforce Id of the associated resource</description>
        <label>Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Auto Renewal Settings</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Booked_Date__c</fullName>
        <label>Booked Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FSR_Not_Required_On_Opp__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if there will not be an FSR on the opportunity</description>
        <inlineHelpText>Check this box if there will not be an FSR on the opportunity</inlineHelpText>
        <label>FSR Not Required On Opp</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Geo__c</fullName>
        <label>Geo</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ROW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Worldwide</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>ISR_Not_Required_On_Opp__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if there will not be an ISR on the opportunity</description>
        <inlineHelpText>Check this box if there will not be an ISR on the opportunity</inlineHelpText>
        <label>ISR Not Required On Opp</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License_Term_in_Months__c</fullName>
        <description>Please enter the license term in whole months.</description>
        <inlineHelpText>Please enter the license term in whole months.</inlineHelpText>
        <label>License Term in Months</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Previous_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity that was previously renewed into this one.</description>
        <label>Previous Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Renewed_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Competitor_Strengths__c</fullName>
        <label>Primary Competitor Strengths</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Primary_Competitor_Weaknesses__c</fullName>
        <label>Primary Competitor Weaknesses</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Primary_Competitor__c</fullName>
        <label>Primary Competitor</label>
        <picklist>
            <picklistValues>
                <fullName>AppNeta/Traceview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aternity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BlueStripe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMC Software</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA Technologies/Wily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compuware/dynaTrace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Correlsense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crittercism</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ExtraHop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HP/Openview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IBM/ITCAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Keynote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loggly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ManageEngine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Microsoft/Avicode</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nastel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Relic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opnet Technologies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Optier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oracle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Precise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quest Software/Foglight</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ruxit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smartbear/Lucierna</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solarwinds/Confio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Splunk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SumoLogic</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LATAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alliances</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East (Federal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mid Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Renewal__c</fullName>
        <label>Renewal</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Subsidiary__c</fullName>
        <description>Used for Validation rule(No Sub) wherein subsidiary on the account cannot be blank.</description>
        <formula>IF( ISPICKVAL(Account.Subsidiary__c, &apos;Appdynamics, Inc.&apos;),&apos;US&apos;, 
IF( ISPICKVAL(Account.Subsidiary__c, &apos;Appdynamics UK2&apos;),&apos;UK&apos;, 
IF( ISPICKVAL(Account.Subsidiary__c, &apos;&apos;),&apos;None&apos;,NULL)))</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Subsidiary</label>
        <type>Text</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Territory_AppD__c.object
<CustomObject>
    <description>Used to manage lead/account routing.</description>
    <fields>
        <fullName>Assigned_To_ID__c</fullName>
        <label>Assigned To ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Geo__c</fullName>
        <label>Geo</label>
        <picklist>
            <picklistValues>
                <fullName>North America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ROW</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BD</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Worldwide</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Region__c</fullName>
        <label>Region</label>
        <picklist>
            <picklistValues>
                <fullName>Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>West</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SER</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Japan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ANZ</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>India</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LATAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Channel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Alliances</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewals</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East (Federal)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Operations</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Management</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>GSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mid Market</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>East</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <recordTypes>
        <fullName>Account</fullName>
        <active>true</active>
        <label>Account</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OpportunityAutoRenew_Test.cls
@isTest
private class OpportunityAutoRenew_Test {

// Extend Test class to test multiples/bulk

   private static testMethod void testClone() {
      Database.SaveResult sr;

      RecordType[] RecordType_query = [SELECT Id FROM RecordType WHERE Name='Renewal Deal' AND SObjectType='Opportunity'];
      String RenewalDealId = RecordType_query[0].Id;
      
      OppAutoRenewSetting__c rdrt = new OppAutoRenewSetting__c();
      rdrt.Name = 'Renewal Deal Record Type';
      rdrt.Id__c = RenewalDealId;
      insert rdrt;
      
      // Create Pricebook and Products
      Pricebook2 pb = new Pricebook2(
         Name = 'Default Pricebook',
         IsActive = true
      );
      sr = Database.insert(pb);
      String PricebookId = sr.GetId();
      
      Product2 testSub = new Product2(
         Name = 'Test Subscription',
         Family = 'Subscription License'
      );
      sr = Database.insert(testSub);
      String SubId = sr.GetId();

      Product2 testPerp = new Product2(
         Name = 'Test Perpetual',
         Family = 'Perpetual Maintenance and Support'
      );
      sr = Database.insert(testPerp);
      String PerpId = sr.GetId();

      PricebookEntry stdPb = new PricebookEntry(
         Product2Id = SubId,
         Pricebook2Id = Test.getStandardPricebookId(),
         UnitPrice = 55.00,
         IsActive = true
      );
      insert stdPb;
      stdPb = new PricebookEntry(
         Product2Id = PerpId,
         Pricebook2Id = Test.getStandardPricebookId(),
         UnitPrice = 75.00,
         IsActive = true
      );
      insert stdPb;

      PricebookEntry pbe = new PricebookEntry(
         Product2Id = SubId,
         Pricebook2Id = PricebookId,
         UnitPrice = 123.00,
         UseStandardPrice = false,
         IsActive = true
      );
      sr = Database.insert(pbe);
      SubId = sr.GetId();
      pbe = new PricebookEntry(
         Product2Id = PerpId,
         Pricebook2Id = PricebookId,
         UnitPrice = 80.00,
         UseStandardPrice = false,
         IsActive = true
      );
      sr = Database.insert(pbe);
      PerpId = sr.GetId();
      
      Territory_AppD__c t = new Territory_AppD__c(Name = 'Test Territory',
                                                 Geo__c = 'North America',
                                                 Region__c = 'West',
                                                 Assigned_To_ID__c = '00580000006Aq0QAAS');  
      insert t;
          
      // Insert a new Account
      Account newAccount = new Account (Name = 'Test Account', 
                                        BillingStreet = '303 2nd Street', 
                                        BillingCity = 'San Francisco', 
                                        BillingState = 'CA', 
                                        BillingCountry= 'United States', 
                                        //Territory_AppD__c = 'a1k34000001se1MAAQ',
                                        Territory_AppD__c = t.Id,
                                        Subsidiary__c = 'AppDynamics, Inc.');
      sr = Database.insert(newAccount);
      String AccountId = sr.GetId();
      
      OpportunityLineItem newLineItem;
      
      Opportunity newSubOpp = new Opportunity(
         Name = 'Subscription Test Opp',
         AccountId = AccountId,
         StageName = 'A1 - Pipeline Generation',
         CloseDate = Date.today(),
         License_Term_in_Months__c = 12,
         Type = 'Subscription',
         Pricebook2Id = PricebookId
      );
      System.debug('++++ SUB OPP INSERT CLOSE DATE: ' + newSubOpp.CloseDate.format());
      sr = Database.insert(newSubOpp);
      String SubOppId = sr.GetId();
      newLineItem = new OpportunityLineItem(
         OpportunityId = SubOppId,
         PricebookEntryId = SubId,
         Quantity = 1,
         TotalPrice = 123.00
      );
      insert newLineItem;
      
      Opportunity newPerpOpp = new Opportunity(
         Name = 'Perpetual Test Opp',
         AccountId = AccountId,
         StageName = 'A1 - Pipeline Generation',
         CloseDate = Date.today(),
         License_Term_in_Months__c = 12,
         Type = 'Perpetual',
         Pricebook2Id = PricebookId
      );
      System.debug('++++ PERP OPP INSERT CLOSE DATE: ' + newPerpOpp.CloseDate.format());
      sr = Database.insert(newPerpOpp);
      String PerpOppId = sr.GetId();
      newLineItem = new OpportunityLineItem(
         OpportunityId = PerpOppId,
         PricebookEntryId = PerpId,
         Quantity = 1,
         TotalPrice = 80.00
      );
      insert newLineItem;

      Opportunity newSecondRenewOpp = new Opportunity(
         Name = 'Second Renewal Opp (Renewal)',
         AccountId = AccountId,
         StageName = 'A1 - Pipeline Generation',
         CloseDate = Date.today(),
         License_Term_in_Months__c = 12,
         Type = 'Subscription',
         Renewal__c = 1,
         Pricebook2Id = PricebookId
      );
      sr = Database.insert(newSecondRenewOpp);
      
      Opportunity newThirdRenewOpp = new Opportunity(
         Name = 'Third Renewal Opp (Renewal #2)',
         AccountId = AccountId,
         StageName = 'A1 - Pipeline Generation',
         CloseDate = Date.today(),
         License_Term_in_Months__c = 12,
         Type = 'Subscription',
         Renewal__c = 2,
         Pricebook2Id = PricebookId
      );
      sr = Database.insert(newThirdRenewOpp);   
      
      Test.startTest();
      newSubOpp.Booked_Date__c = Date.today();
      newSubOpp.StageName = 'W10 - Closed/Won';
      newSubOpp.FSR_Not_Required_On_Opp__c = true;
      newSubOpp.ISR_Not_Required_On_Opp__c = true;
      newSubOpp.Primary_Competitor__c = 'New Relic';
      newSubOpp.Primary_Competitor_Strengths__c = 'Strength1';
      newSubOpp.Primary_Competitor_Weaknesses__c = 'Weakness1';
      update newSubOpp;
      newPerpOpp.Booked_Date__c = Date.today();
      newPerpOpp.StageName = 'W10 - Closed/Won';
      newPerpOpp.FSR_Not_Required_On_Opp__c = true;
      newPerpOpp.ISR_Not_Required_On_Opp__c = true;
      newPerpOpp.Primary_Competitor__c = 'New Relic';
      newPerpOpp.Primary_Competitor_Strengths__c = 'Strength1';
      newPerpOpp.Primary_Competitor_Weaknesses__c = 'Weakness1';
      update newPerpOpp;
      newSecondRenewOpp.Booked_Date__c = Date.today();
      newSecondRenewOpp.StageName = 'W10 - Closed/Won';
      newSecondRenewOpp.FSR_Not_Required_On_Opp__c = true;
      newSecondRenewOpp.ISR_Not_Required_On_Opp__c = true;
      newSecondRenewOpp.Primary_Competitor__c = 'New Relic';
      newSecondRenewOpp.Primary_Competitor_Strengths__c = 'Strength1';
      newSecondRenewOpp.Primary_Competitor_Weaknesses__c = 'Weakness1';
      update newSecondRenewOpp;
      newThirdRenewOpp.Booked_Date__c = Date.today();
      newThirdRenewOpp.StageName = 'W10 - Closed/Won';
      newThirdRenewOpp.FSR_Not_Required_On_Opp__c = true;
      newThirdRenewOpp.ISR_Not_Required_On_Opp__c = true;
      newThirdRenewOpp.Primary_Competitor__c = 'New Relic';
      newThirdRenewOpp.Primary_Competitor_Strengths__c = 'Strength1';
      newThirdRenewOpp.Primary_Competitor_Weaknesses__c = 'Weakness1';
      update newThirdRenewOpp;
      Test.stopTest();
      
      // A new Opportunity should have been created (cloned) with a Stage of B2
      Opportunity[] o_query = [SELECT Id,StageName,Booked_Date__c,Previous_Opportunity__c,Renewal__c FROM Opportunity WHERE Name='Subscription Test Opp (Renewal)'];
      Opportunity clonedOpp = o_query[0];
      System.assertEquals('B2 - First Meeting/Qualification', clonedOpp.StageName);
      System.assertEquals(newSubOpp.Id,clonedOpp.Previous_Opportunity__c);
      System.assertEquals(1,clonedOpp.Renewal__c);
      
      // A new Opportunity Line Item should have been created as well
      OpportunityLineItem[] oli_query = [SELECT Id,OpportunityId,TotalPrice FROM OpportunityLineItem
                                         WHERE OpportunityId =: clonedOpp.Id AND PricebookEntryId =: SubId];
      OpportunityLineItem clonedLineItem = oli_query[0];
      System.assertEquals(123.00, clonedLineItem.TotalPrice);
      
      // Check for the new Perpetual one as well
      o_query = [SELECT Id,StageName,Booked_Date__c,Previous_Opportunity__c,Renewal__c FROM Opportunity WHERE Name='Perpetual Test Opp (Renewal)'];
      clonedOpp = o_query[0];
      System.assertEquals('B2 - First Meeting/Qualification', clonedOpp.StageName);
      System.assertEquals(newPerpOpp.Id,clonedOpp.Previous_Opportunity__c);
      System.assertEquals(1,clonedOpp.Renewal__c);
      oli_query = [SELECT Id,OpportunityId,TotalPrice FROM OpportunityLineItem
                   WHERE OpportunityId !=: clonedOpp.Id AND PricebookEntryId =: PerpId];
      clonedLineItem = oli_query[0];
      System.assertEquals(80.00, clonedLineItem.TotalPrice);

      for (Opportunity o : [SELECT Id,Name,Renewal__c FROM Opportunity WHERE Renewal__c > 1]) {
         System.debug('+++ ' + o.Name);
      }

/*      
      // Test for the Second Renewal
      o_query = [SELECT Id,StageName,Booked_Date__c,Previous_Opportunity__c FROM Opportunity WHERE Name='Second Renewal Opp (Renewal #2)'];
      clonedOpp = o_query[0];
      System.assertEquals('B2 - First Meeting/Qualificaton', clonedOpp.StageName);
      
      // Test for the Third Renewal
      o_query = [SELECT Id,StageName,Booked_Date__c,Previous_Opportunity__c FROM Opportunity WHERE Name='Third Renewal Opp (Renewal #3)'];
      clonedOpp = o_query[0];
      System.assertEquals('B2 - First Meeting/Qualificaton', clonedOpp.StageName);
*/



   }

}