src/objects/Account.object
<CustomObject>
    <fields>
        <fullName>PortalID__c</fullName>
        <label>PortalID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Technical_Account_Manager__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Technical Account Manager</label>
        <lookupFilter>
            <active>true</active>
            <filterItems>
                <field>User.Profile.Name</field>
                <operation>equals</operation>
                <value>AppD Customer Success</value>
            </filterItems>
            <isOptional>false</isOptional>
        </lookupFilter>
        <referenceTo>User</referenceTo>
        <relationshipName>Accounts2</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/DBTuna_License__c.object
<CustomObject>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipName>DBTunas</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>AppDynamics For Databases - License</label>
    <nameField>
        <label>License</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AppDynamics For Databases - License</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/User.object
<CustomObject>
    <fields>
        <fullName>PortalID__c</fullName>
        <label>PortalID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/classes/DBTunaLicenseDetailsController.cls
public with sharing class DBTunaLicenseDetailsController extends AbstractAppDController {
	public Opportunity myOpportunity{get;set;}
	public Account accObj;
	public List<ContactWrapper> dblicenseContacts{get;set;}
	public DBTuna_License__c lic {get;set;}
	public DBTunaLicenseDetailsController(ApexPages.StandardController controller){
		super(controller);
	}
	
	public override void init(){
		super.init();
		loggerHandle.setClassName(DBTunaLicenseDetailsController.class.getName());
		lic = (DBTuna_License__c)pageContextObj;
		myOpportunity = (Opportunity)DataLayerConstants.fetchSingle('Opportunity_Account_Owner',lic.Opportunity__c);
		accObj = [Select Id,CreatedById, OwnerId,Technical_Account_Manager__r.Id,Technical_Account_Manager__r.Email ,Name,PortalID__c,RecordType.Name,RecordType.Id from Account where Id=:myOpportunity.AccountId];
		dblicenseContacts = LicenseUtil.getDBContacts(lic,myOpportunity,accObj,true);
	}
}