src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>FCRM__FCR_Repeat_Responses_Allowed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>True if repeat responses are allowed for this campaign (i.e. cascading enabled).</description>
        <inlineHelpText>True if repeat responses are allowed for this campaign (i.e. cascading enabled).</inlineHelpText>
        <label>Repeat Responses Allowed</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>FCRM__FCR_Response_Date__c</fullName>
        <description>Response date</description>
        <label>Response Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FCRM__FCR_Response_Status__c</fullName>
        <description>Current response status</description>
        <label>Response Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attempting Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recycled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified Forever</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified - New Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved - Already Engaged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved - No Action Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved - Opportunity Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved - Opportunity Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not a Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unmapped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/RM_Score_Evaluation_Setting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Contact_Status_after_Response__c</fullName>
        <description>This is the status value to set on the Contact Status field (FCR_Status__c) during contact updates</description>
        <label>Contact Status after Response</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Contact_Trigger_Field__c</fullName>
        <description>This is the contact field that the application monitors for an update; It can be a number field, a text field or Boolean field.</description>
        <label>Contact Trigger Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Campaign_ID__c</fullName>
        <label>Default Campaign ID</label>
        <length>20</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Default_Member_Status__c</fullName>
        <label>Default Member Status</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Follow_Converted_Lead__c</fullName>
        <defaultValue>false</defaultValue>
        <description>This is a checkbox field that indicates that if the lead has been converted during the timeframe- go ahead and continue functionality on the converted contact (re-open or associate response).</description>
        <label>Follow Converted Lead</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Lead_Status_after_Response__c</fullName>
        <description>This is the status value to set on the Lead Status field (Status) during lead updates</description>
        <label>Lead Status after Response</label>
        <length>125</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Lead_Trigger_Field__c</fullName>
        <description>This is the lead field that the application monitors for an update; It can be a number field, a text field or Boolean field.</description>
        <label>Lead Trigger Field</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_Status_Values__c</fullName>
        <defaultValue>&quot;Resolved - Already Engaged,Resolved - No Action Required&quot;</defaultValue>
        <description>Response status that would be subject to re-opening based on the Response Status Value.</description>
        <label>Response Status Values</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Time_Delay_for_Evaluation__c</fullName>
        <defaultValue>0</defaultValue>
        <description>Time, in minutes, to wait before evaluating whether or not there is a response to re-open or one to associate. Time delay applies across converted leads as well.</description>
        <label>Time Delay for Evaluation</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>RM Score Evaluation Setting</label>
</CustomObject>

src/classes/FC_GSR_ScoreReevaluatorTest.cls
@isTest (SeeAllData=true)
public class FC_GSR_ScoreReevaluatorTest {

    static testMethod void testRescoreReevaluationOnContact() 
    {
    	FCRM.FCR_SupportAPI.SetRepeatResponseUserForContext();
    	
    	// Get custom setting
    	RM_Score_Evaluation_Setting__c setting = getCustomSetting('default');      
        
        // Bypass scoring requirement because scoring field not visible in test
        FC_GSR_ScoreReevaluator.bypassScoreRequirement = true;
        
        List<Contact> cts = initTestContacts('cts', 1);
        insert cts;
        
        List<Campaign> camps = initTestCampaigns('cmp', cts.size());
        insert camps;        
        
        List<String> unanimatedStatusValues = setting.Response_Status_Values__c.split(',');
        CampaignMember cm = new CampaignMember(Status='Responded', FCRM__FCR_Response_Date__c=Date.today() - 2, FCRM__FCR_Response_Status__c = unanimatedStatusValues[0], ContactID = cts[0].id, CampaignID = camps[0].id);        
        
        insert cm;
        
        cts[0].put(setting.Contact_Trigger_Field__c, 'new value');
        Test.startTest();
        update cts[0];
        Test.stopTest();
                
        CampaignMember response = [Select FCRM__FCR_Response_Status__c From CampaignMember Where Id = :cm.Id];
               
        system.assert(response.FCRM__FCR_Response_Status__c == setting.Contact_Status_after_Response__c);             
    }
    
    static testMethod void testInsertDefaultCampaign() 
    {
    	FCRM.FCR_SupportAPI.SetRepeatResponseUserForContext();
    	
    	// Get custom setting
    	RM_Score_Evaluation_Setting__c setting = getCustomSetting('default');      
        
        // Bypass scoring requirement because scoring field not visible in test
        FC_GSR_ScoreReevaluator.bypassScoreRequirement = true;
        
        List<Contact> cts = initTestContacts('cts', 1);
        insert cts;
        
        List<Campaign> camps = initTestCampaigns('cmp', cts.size());        
        insert camps;  
              
        setting.Default_Campaign_ID__c = camps[0].Id;
        upsert setting;                
        
        cts[0].put(setting.Contact_Trigger_Field__c, 'new value');
        Test.startTest();
        update cts[0];
        Test.stopTest();
                
        List<CampaignMember> responses = [Select FCRM__FCR_Response_Status__c From CampaignMember Where ContactId = :cts[0].Id];
               
        system.assert(responses.size() > 0);             
    }              
    
    static testMethod void testRescoreReevaluationOnContactAsync() 
    {
    	FCRM.FCR_SupportAPI.SetRepeatResponseUserForContext();
    	
    	// Get custom setting
    	RM_Score_Evaluation_Setting__c setting = getCustomSetting('default');
    	
    	// Register Plugin            
        installPlugin('FC_GSR_AsyncPlugin');              
        
        // Bypass scoring requirement because scoring field not visible in test
        FC_GSR_ScoreReevaluator.bypassScoreRequirement = true;
        
        List<Contact> cts = initTestContacts('cts', 1);
        insert cts;
        
        List<Campaign> camps = initTestCampaigns('cmp', cts.size());
        insert camps;        
        
        List<String> unanimatedStatusValues = setting.Response_Status_Values__c.split(',');
        CampaignMember cm = new CampaignMember(Status='Responded', FCRM__FCR_Response_Date__c=Date.today() - 2, FCRM__FCR_Response_Status__c = unanimatedStatusValues[0], ContactID = cts[0].id, CampaignID = camps[0].id);        
        
        insert cm;
        
        FC_GSR_AsyncPlugin plugin = new FC_GSR_AsyncPlugin();
        Test.startTest();
        plugin.ExtensibilityEvent('TimedAsync', getArgs(new List<Id>{cts[0].Id}));
        Test.stopTest();
                
        CampaignMember response = [Select FCRM__FCR_Response_Status__c From CampaignMember Where Id = :cm.Id];
               
        system.assert(response.FCRM__FCR_Response_Status__c == setting.Contact_Status_after_Response__c);             
    }    
    
    static testMethod void testRescoreReevaluationOnConvertedLead() 
    {
    	FCRM.FCR_SupportAPI.SetRepeatResponseUserForContext();
    	
    	// Get custom setting
    	RM_Score_Evaluation_Setting__c setting = getCustomSetting('default');  
    	setting.Follow_Converted_Lead__c = true; 
    	upsert setting;   
        
        // Bypass scoring requirement because scoring field not visible in test
        FC_GSR_ScoreReevaluator.bypassScoreRequirement = true;
        
        List<Lead> lds = initTestLeads('lds', 1);
        insert lds;
        
        List<Campaign> camps = initTestCampaigns('cmp', lds.size());
        insert camps;         
        
        List<String> unanimatedStatusValues = setting.Response_Status_Values__c.split(',');
        CampaignMember cm = new CampaignMember(Status='Responded', FCRM__FCR_Response_Date__c=Date.today() - 2, FCRM__FCR_Response_Status__c = unanimatedStatusValues[0], LeadID = lds[0].id, CampaignID = camps[0].id);        
        
        insert cm;
        
        // Convert the Lead
        Database.LeadConvert lc = new database.LeadConvert();
        lc.setLeadId(lds[0].id);
        LeadStatus convertStatus = [Select Id, MasterLabel from LeadStatus where IsConverted=true limit 1];
        lc.setConvertedStatus(convertStatus.MasterLabel);         
        Database.LeadConvertResult lcr = Database.convertLead(lc);                
        
        FC_GSR_AsyncPlugin plugin = new FC_GSR_AsyncPlugin();
        Test.startTest();
		plugin.ExtensibilityEvent('TimedAsync', getArgs(new List<Id>{lds[0].Id}));
        Test.stopTest();
                
        CampaignMember response = [Select FCRM__FCR_Response_Status__c From CampaignMember Where Id = :cm.Id];
               
        system.assert(response.FCRM__FCR_Response_Status__c == setting.Lead_Status_after_Response__c);             
    }       
    
    static testMethod void testRescoreReevaluationOnLead() 
    {
    	FCRM.FCR_SupportAPI.SetRepeatResponseUserForContext();
    	
    	// Get custom setting
    	RM_Score_Evaluation_Setting__c setting = getCustomSetting('default');      
        
        // Bypass scoring requirement because scoring field not visible in test
        FC_GSR_ScoreReevaluator.bypassScoreRequirement = true;
        
        List<Lead> lds = initTestLeads('lds', 1);
        insert lds;
        
        List<Campaign> camps = initTestCampaigns('cmp', lds.size());
        insert camps;        
        
        List<String> unanimatedStatusValues = setting.Response_Status_Values__c.split(',');
        CampaignMember cm = new CampaignMember(Status='Responded', FCRM__FCR_Response_Date__c=Date.today() - 2, FCRM__FCR_Response_Status__c = unanimatedStatusValues[0], LeadID = lds[0].id, CampaignID = camps[0].id);        
        
        insert cm;
        
        lds[0].put(setting.Lead_Trigger_Field__c, 'new value');
        Test.startTest();
        update lds[0];
        Test.stopTest();
                
        CampaignMember response = [Select FCRM__FCR_Response_Status__c From CampaignMember Where Id = :cm.Id];
               
        system.assert(response.FCRM__FCR_Response_Status__c == setting.Lead_Status_after_Response__c);             
    }    

    // Args class used for testing the plugin
    public Class Args implements FCRM.FCR_ExtensibilityAPI.IExtensibilityEventArgs
    {
        public List<List<Sobject>> Recordlists;
        public List<Map<ID, Sobject>> RecordMaps;
        public List<List<ID>> RecordIds;
        
        public List<List<Sobject>> getRecordLists() { return RecordLists; }
        public List<Map<ID, Sobject>> getRecordMaps() { return RecordMaps; }
        public List<List<ID>> getRecordIds() { return RecordIds; }
        public List<Object> getAdditionalParams() {return null; }
        public void setRaiseFuture() {  }
        public String getXMLdata() {
            List<String> personIdList = new List<String>();
            for (String id : this.getRecordIds()[0]) personIdList.add(id);          
            return String.join(personIdList, ',');
        }
        
        public Args(){}
                
    } 
    
    public static Args getArgs(List<Id> taskIdList) 
    {
        Args args = new Args();
        args.RecordIds = new List<List<Id>>();
        args.RecordIds.add(taskIdList);
        return args;
    }    

    public static RM_Score_Evaluation_Setting__c getCustomSetting(String name)
    {
    	RM_Score_Evaluation_Setting__c setting = RM_Score_Evaluation_Setting__c.getInstance(name);
    	if (setting == null) setting = new RM_Score_Evaluation_Setting__c(name = name); 
		setting.Lead_Status_after_Response__c = 'Open - Not Contacted';
		setting.Contact_Status_after_Response__c = 'Open - Not Contacted';
		setting.Default_Member_Status__c = 'Responded';
		setting.Contact_Trigger_Field__c = 'Title';
		setting.Lead_Trigger_Field__c = 'Industry';    	
		setting.Response_Status_Values__c = 'Resolved - Already Engaged,Resolved - No Action Required';
		setting.Time_Delay_for_Evaluation__c = 0;
    	upsert setting; 
    	return setting;
    } 
    
    public static void installPlugin(String pluginname)
    {
        FCRM.FCR_ExtensibilityAPI.EnablePluginsForTest = new Set<String>{pluginname};
        FCRM.FCR_ExtensibilityAPI.InstallPluginClass(pluginname);
    }    

    public static List<Contact> initTestContacts(String prefix, Integer count)  
    {    
        List<Contact>cts = new List<Contact>();    
        for(Integer x=1;x<count+1;x++)    
        {      
          cts.add(new Contact(LastName = prefix + '_' + String.valueOf(x)));
        }
        return cts;  
    }
    
    public static List<Account> initTestAccounts(String prefix, Integer count)
    {
	  List<Account> accounts = new List<Account>();
	  for(Integer x=1; x<count + 1; x++)
	  {
	    accounts.add(new Account(Name= prefix + '_' + String.valueOf(x)));    
	  }
	  return accounts;
    }
    
   public static List<Lead> initTestLeads(String prefix, Integer count)  
   {    
		List<Lead>lds = new List<Lead>();    
		for(Integer x=1;x<count+1;x++)    
		{      
		  lds.add(new Lead(Company= prefix + '_' + String.valueOf(x), LastName = prefix + '_' + String.valueOf(x), Status='Nurture/Marketing'));    
		}    
		return lds;  
   }    
        
    
    public static List<Campaign> initTestCampaigns(String prefix, Integer count)
    {
        List<Campaign> camps = new List<Campaign>();
        for(Integer x=1; x<count+1; x++)
        {
          camps.add(new Campaign(Name = prefix+'_'+ String.ValueOf(x), FCRM__FCR_Repeat_Responses_Allowed__c=true, IsActive = true));
        }
        return camps;
    }    

}