src/objects/Campaign.object
<CustomObject>
    <fields>
        <fullName>FCRM__FCR_Bypass_Nurture_Timeout__c</fullName>
        <defaultValue>false</defaultValue>
        <description>If selected any responses to this campaign will ignore nurture timeout dates set on the lead/contact record.</description>
        <inlineHelpText>If selected any responses to this campaign will ignore nurture timeout dates set on the lead/contact record.</inlineHelpText>
        <label>Bypass Nurture Timeout</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FCRM__FCR_Repeat_Responses_Allowed__c</fullName>
        <defaultValue>false</defaultValue>
        <description>True if repeat responses are allowed for this campaign (i.e. cascading enabled).</description>
        <inlineHelpText>True if repeat responses are allowed for this campaign (i.e. cascading enabled).</inlineHelpText>
        <label>Repeat Responses Allowed</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FC_Defer_To_Reanimation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Defer To Reanimation</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>FC_Exclude_From_Reanimation__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Exclude From Reanimation</label>
        <type>Checkbox</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/CampaignMember.object
<CustomObject>
    <fields>
        <fullName>FCRM__FCR_Campaign_Repeat_Parent__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Lookup to the cascade parent campaign, or the campaign (if this is not a repeat)</description>
        <inlineHelpText>This field is used in reporting to group all responses by Repeat Parent Campaign.</inlineHelpText>
        <label>Campaign Name (Repeat Parent)</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Campaign Members (Campaign Name (Repeat Parent))</relationshipLabel>
        <relationshipName>Campaign_Members_With_Repeats</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>FCRM__FCR_Response_Date__c</fullName>
        <description>Response date</description>
        <label>Response Date</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>FCRM__FCR_Response_Status__c</fullName>
        <description>Current response status</description>
        <label>Response Status</label>
        <picklist>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attempting Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recycled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified Forever</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified - New Opportunity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved - Already Engaged</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved - No Action Required</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved - Opportunity Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Resolved - Opportunity Lost</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Not a Response</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unmapped</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/FC_ResponseReanimateManager__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <fields>
        <fullName>Last_X_Days_Responded_For_Reopen__c</fullName>
        <description>Number of days to evaluate from today when looking for a response to re-animate.</description>
        <inlineHelpText>Number of days to evaluate from today when looking for a response to re-animate.</inlineHelpText>
        <label>Last X Days Responded For Reopen</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Response_Active_Status_Value__c</fullName>
        <label>Response Active Status Value</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Response_Status_Values_to_Consider__c</fullName>
        <description>Response Status values that are eligible for re-animation</description>
        <inlineHelpText>Response Status values that are eligible for re-animation</inlineHelpText>
        <label>Response Status Values to Consider</label>
        <type>TextArea</type>
    </fields>
    <label>Response Reanimate Manager</label>
</CustomObject>

src/classes/FC_ResponseReanimatorTest.cls
@isTest (SeeAllData=true)
public with sharing class FC_ResponseReanimatorTest {

    private static FC_ResponseReanimateManager__c setting {
    	get {
    		if (setting == null)
    		{
    			FC_ResponseReanimateManager__c newsetting = FC_ResponseReanimateManager__c.getInstance('default');
    			if (newsetting == null)
    			{
    				newsetting.Last_X_Days_Responded_For_Reopen__c = 45;
    				newsetting.Response_Active_Status_Value__c = 'Open';
    				newsetting.Response_Status_Values_to_Consider__c = 'Disqualified';
    			}
    			setting = newsetting;
    		}
    		return setting;    		
    	}
    	set;
    }
    
    static testMethod void TestResponsePromptInsert() 
    {
        FCRM.FCR_SupportAPI.SetRepeatResponseUserForContext();
        
        List<Contact> cts = initTestContacts('cts', 1);
        insert cts;
        
        List<Campaign> camps = initTestCampaigns('cmp', cts.size());
        insert camps;        
        
        List<String> unanimatedStatusValues = setting.Response_Status_Values_to_Consider__c.split(';');
        CampaignMember cm = new CampaignMember(Status='Responded', FCRM__FCR_Response_Date__c=Date.today() - 2, FCRM__FCR_Response_Status__c = unanimatedStatusValues[0], ContactID = cts[0].id, CampaignID = camps[0].id);        
        
        FCRM.FCR_SupportAPI.DisableApplicationForContext();
        insert cm;
        FCRM.FCR_SupportAPI.UndoDisableApplicationForContext();
        
        Set<Id> respPromptCampaignIds = FCRM.FCR_SupportAPI.GetResponsePromptCampaignIDs();
        List<Id> respPromptCampaignIdList = new List<Id>();
        for (Id cid : respPromptCampaignIds) respPromptCampaignIdList.add(cid); 
        List<Campaign> respPromptCamps = [Select Id, FC_Defer_to_Reanimation__c, FC_Exclude_from_Reanimation__c From Campaign Where Id IN :respPromptCampaignIdList];
                  
        respPromptCamps[0].FC_Defer_to_Reanimation__c = true; 
        respPromptCamps[0].FC_Exclude_from_Reanimation__c = false;
        update respPromptCamps[0];
        
        CampaignMember responsePrompt = new CampaignMember(Status='Responded', ContactID = cts[0].id,  CampaignID = respPromptCamps[0].id);       
        
        Test.startTest();   
        insert responsePrompt; 
        Test.stopTest();  
                
        //List<CampaignMember> responses = [Select FCRM__FCR_Response_Status__c, FCRM__FCR_Campaign_Repeat_Parent__c From CampaignMember Where ContactId = :cts[0].id];    
        //system.assertEquals(setting.Response_Active_Status_Value__c, responses[0].FCRM__FCR_Response_Status__c);                   
                        
    }
    
    public static List<Contact> initTestContacts(String prefix, Integer count)  
    {    
        List<Contact>cts = new List<Contact>();    
        for(Integer x=1;x<count+1;x++)    
        {      
          cts.add(new Contact(LastName = prefix + '_' + String.valueOf(x)));
        }
        return cts;  
    }


    public static List<Campaign> initTestCampaigns(String prefix, Integer count)
    {
        List<Campaign> camps = new List<Campaign>();
        for(Integer x=1; x<count+1; x++)
        {
          camps.add(new Campaign(Name = prefix+'_'+ String.ValueOf(x), FC_Exclude_from_Reanimation__c=false, 
            FC_Defer_to_Reanimation__c=true, FCRM__FCR_Repeat_Responses_Allowed__c=true, FCRM__FCR_Bypass_Nurture_Timeout__c=true, IsActive = true));
        }
        return camps;
    } 

}