src/objects/Contact.object
<CustomObject>
    <fields>
        <fullName>FCRM__FCR_Admin_Update_Counter__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This counter is changed any time this object is updated by the response management system.</description>
        <inlineHelpText>This counter is changed any time this object is updated by the response management system.</inlineHelpText>
        <label>Admin Update Counter</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FCRM__FCR_Nurture_Timeout__c</fullName>
        <description>Nurture timeout date for this contact.</description>
        <inlineHelpText>Indicates the earliest date this contact can promote out of nurture for follow up.</inlineHelpText>
        <label>Nurture Timeout</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>FCRM__FCR_Status__c</fullName>
        <description>The status of the contact.</description>
        <label>Contact Status</label>
        <picklist>
            <picklistValues>
                <fullName>Pending</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Open</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Attempting Contact</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Working</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Recycled</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Unqualified Forever</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Active Opportunity</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Read</sharingModel>
</CustomObject>

src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>FCRM__FCR_Admin_Update_Counter__c</fullName>
        <defaultValue>0</defaultValue>
        <description>This counter is changed any time this object is updated by the response management system.</description>
        <inlineHelpText>This counter is changed any time this object is updated by the response management system.</inlineHelpText>
        <label>Admin Update Counter</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>FCRM__FCR_Nurture_Timeout__c</fullName>
        <description>Nurture timeout for the lead.</description>
        <inlineHelpText>If populated, this field indicates the next possible date this lead could promote out of nurture and be sent back to sales for follow up.</inlineHelpText>
        <label>Nurture Timeout</label>
        <type>Date</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/FC_GSR_AsyncPlugin.cls
global without sharing class FC_GSR_AsyncPlugin implements FCRM.FCR_ExtensibilityAPI.IExtensibilityPlugin  {

    public static final String TIMEDASYNC = 'TimedAsync';   
    
    global Set<String> RequestedAPIs() { return new Set<String>{TIMEDASYNC} ;}   

    global String GetUniqueName() { return 'FC_GSR_AsyncPlugin' ;}
    
    global Map<String,Set<String>> RequestedFields() 
    { 
        return new Map<String, Set<String>>();
    }    
    
    global void ExtensibilityEvent(String eventname, FCRM.FCR_ExtensibilityAPI.IExtensibilityEventArgs args) {

        if (eventname == TIMEDASYNC && args.getXMLdata() != null)
        {
            List<String> personIds = args.getXMLdata().split(',');
			String firstPersonId = personIds[0];
    		String personType = firstPersonId.startsWith('003') == true ? 'Contact' : 'Lead';
    		String statusField = personType == 'Contact' ? 'FCRM__FCR_Status__c' : 'Status';
    		String queryStr = 'Select Id, FCRM__FCR_Admin_Update_Counter__c, FCRM__FCR_Nurture_Timeout__c, ' 
    			+ statusField + ' From ' + personType + ' Where Id IN :personIds';   
    		List<sObject> personsToProcessList = Database.query(queryStr);  
    		Map<Id, sObject> personsToProcess = new Map<Id, sObject>(personsToProcessList);   
    		FC_GSR_ScoreReevaluator.processPersonRecords(personsToProcess, personType, true);
        } 
        
        return;
           
    }

}