src/objects/DBTuna_License__c.object
<CustomObject>
    <fields>
        <fullName>ExpiryDate__c</fullName>
        <label>ExpiryDate</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Server_Name__c</fullName>
        <label>Server Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>AppDynamics For Databases - License</label>
    <nameField>
        <label>License</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>AppDynamics For Databases - License</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/DBTunaBackend.cls
public virtual class DBTunaBackend extends Backend{
	public DBTuna_License__c license{get;set;}
	
	public DBTunaBackend(DBTuna_License__c license){
		super(license,BackendConstants.OPCODE_DBTUNA_PROVISION);
        this.license=license;
        this.opCode = BackendConstants.OPCODE_DBTUNA_PROVISION;
        
        setupInputParameters();
	}
	
	public virtual override void setupInputParameters(){
		setParameters(new List<BackendLayer.BackendParameter>());
		BackendLayer.BackendParameter param = null;
        String expiryDate = String.valueOf(license.ExpiryDate__c);
        String serverName = license.Server_Name__c;
        
        param = new BackendLayer.BackendParameter('expiry_date',expiryDate);
        getParameters().add(param);
        param = new BackendLayer.BackendParameter('environment',serverName);
        getParameters().add(param);
	}
	
}