src/objects/EUM_Mobile__c.object
<CustomObject>
    <fields>
        <fullName>Allow_overages__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow overages</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License_EUM_Detail__c</fullName>
        <label>License EUM Detail</label>
        <referenceTo>License_EUM_Details__c</referenceTo>
        <relationshipLabel>EUM Mobile</relationshipLabel>
        <relationshipName>EUM_Mobile</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>EUM Mobile Type</label>
        <picklist>
            <picklistValues>
                <fullName>LITE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <defaultValue>1</defaultValue>
        <label>EUM Mobile Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>EUM Mobile</label>
    <nameField>
        <label>License EUM Mobile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EUM Mobile</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EUM_Web__c.object
<CustomObject>
    <fields>
        <fullName>Allow_overages__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow overages</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License_EUM_Detail__c</fullName>
        <label>License EUM Detail</label>
        <referenceTo>License_EUM_Details__c</referenceTo>
        <relationshipLabel>EUM Web</relationshipLabel>
        <relationshipName>EUM_Web</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>LITE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <label>Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>EUM Web</label>
    <nameField>
        <label>License EUM Web Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EUM Web</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/License_EUM_Details__c.object
<CustomObject>
    <fields>
        <fullName>AccountName__c</fullName>
        <label>EUM Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Allow_Overages__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EUM Allow Overages</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>License to which this EUM details are associated with.</inlineHelpText>
        <label>License</label>
        <referenceTo>LicenseDetail__c</referenceTo>
        <relationshipLabel>License EUM Details</relationshipLabel>
        <relationshipName>License_EUM_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>EUM License Type</inlineHelpText>
        <label>EUM Type</label>
        <picklist>
            <picklistValues>
                <fullName>LITE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>License EUM Detail</label>
    <nameField>
        <label>License EUM Detail(s) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License EUM Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LicenseDetail__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>License_BackendID__c</fullName>
        <label>License_BackendID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_Expiry_Date__c</fullName>
        <label>License Expiration Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Net_Agents__c</fullName>
        <label>.Net Agents Old</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Deployment Option</label>
        <picklist>
            <picklistValues>
                <fullName>On-Premise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosted (SaaS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosted (SaaS Lite)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Server_Agents__c</fullName>
        <label>Java Agents Old</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>TRIAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRIAL EXPIRED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAID EXPIRED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DISABLED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Pro_Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRO_PAID</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>License</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestEUMLicense.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestEUMLicense {

    static testMethod void testEUM_1() {
        LicenseEUMInput eumInput = new LicenseEUMInput(null,null,null);
        LicenseUtil.getEUMLicenseInput(null);
        LicenseDetail__c lic = new LicenseDetail__c();
		lic.Product_Type__c = 'On-Premise';
        lic.License_BackendID__c = '100';
        lic.License_Expiry_Date__c = System.now().date().addDays(15);
        lic.Product_Type__c = AppDConstants.LICENSE_PRODUCT_TYPE_ON_PREMISE;
        lic.Server_Agents__c  = 10;
        lic.Net_Agents__c  = 10;
        lic.Stage__c = 'TRIAL';
        insert lic;
        
        License_EUM_Details__c eumLicense =  new License_EUM_Details__c();
        eumLicense.License__c = lic.id;
        eumLicense.AccountName__c = 'TestEUM';
        insert eumLicense;
        
        LicenseUtil.getEUMLicenseInput(eumLicense);
    }
    
    static testMethod void testEUM_2() {
    	LicenseDetail__c lic = new LicenseDetail__c();
		lic.Product_Type__c = 'On-Premise';
        lic.License_BackendID__c = '100';
        lic.License_Expiry_Date__c = System.now().date().addDays(15);
        lic.Product_Type__c = AppDConstants.LICENSE_PRODUCT_TYPE_ON_PREMISE;
        lic.Server_Agents__c  = 10;
        lic.Net_Agents__c  = 10;
        lic.Stage__c = 'TRIAL';
        insert lic;
        
    	License_EUM_Details__c eum =  new License_EUM_Details__c();
        eum.License__c = lic.id;
        eum.AccountName__c = 'TestEUM';
        insert eum;
        
        EUM_Mobile__c eumMobile = new EUM_Mobile__c();
        eumMobile.Allow_overages__c = false;
        eumMobile.License_EUM_Detail__c = eum.id;
        eumMobile.Type__c = 'LITE';
        eumMobile.Units__c = 1;
        insert eumMobile;
        
        EUM_Web__c eumWeb = new EUM_Web__c();
        eumWeb.Allow_overages__c = false;
        eumWeb.License_EUM_Detail__c = eum.id;
        eumWeb.Type__c = 'LITE';
        eumWeb.Units__c = 1;
        insert eumWeb;
        
        eum = (License_EUM_Details__c)DataLayerConstants.fetchSingle('License_EUM_Details__c', eum.id);
        LicenseUtil.getEUMLicenseInput(eum);
    }
}