src/objects/EUM_Mobile__c.object
<CustomObject>
    <fields>
        <fullName>Allow_overages__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow overages</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License_EUM_Detail__c</fullName>
        <label>License EUM Detail</label>
        <referenceTo>License_EUM_Details__c</referenceTo>
        <relationshipLabel>EUM Mobile</relationshipLabel>
        <relationshipName>EUM_Mobile</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>EUM Mobile Type</label>
        <picklist>
            <picklistValues>
                <fullName>LITE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <defaultValue>1</defaultValue>
        <label>EUM Mobile Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>EUM Mobile</label>
    <nameField>
        <label>License EUM Mobile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EUM Mobile</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EUM_Web__c.object
<CustomObject>
    <fields>
        <fullName>Allow_overages__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow overages</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License_EUM_Detail__c</fullName>
        <label>License EUM Detail</label>
        <referenceTo>License_EUM_Details__c</referenceTo>
        <relationshipLabel>EUM Web</relationshipLabel>
        <relationshipName>EUM_Web</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>LITE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <label>Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>EUM Web</label>
    <nameField>
        <label>License EUM Web Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EUM Web</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/License_Agent__c.object
<CustomObject>
    <description>License Agent which will have:
Agent Type as Java/.Net/PHP
and Agent count</description>
    <fields>
        <fullName>Agent_Type__c</fullName>
        <label>Agent Type</label>
        <picklist>
            <picklistValues>
                <fullName>Java</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>.NET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PHP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NodeJs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Database</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Python</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transaction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Log</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Machine</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <label>License</label>
        <referenceTo>LicenseDetail__c</referenceTo>
        <relationshipLabel>License Agents</relationshipLabel>
        <relationshipName>License_Agents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>License Agent</label>
    <nameField>
        <label>License Units Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Agents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/License_EUM_Details__c.object
<CustomObject>
    <fields>
        <fullName>AccountName__c</fullName>
        <label>EUM Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Allow_Overages__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EUM Allow Overages</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>License to which this EUM details are associated with.</inlineHelpText>
        <label>License</label>
        <referenceTo>LicenseDetail__c</referenceTo>
        <relationshipLabel>License EUM Details</relationshipLabel>
        <relationshipName>License_EUM_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>EUM License Type</inlineHelpText>
        <label>EUM Type</label>
        <picklist>
            <picklistValues>
                <fullName>LITE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>License EUM Detail</label>
    <nameField>
        <label>License EUM Detail(s) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License EUM Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/License_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>License__c</fullName>
        <label>License</label>
        <referenceTo>LicenseDetail__c</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LicenseDetail__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Is_HA__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is HA?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License_BackendID__c</fullName>
        <label>License_BackendID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_Expiry_Date__c</fullName>
        <label>License Expiration Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MAC_Address__c</fullName>
        <description>MAC Address of the machine to be registered with license</description>
        <label>MAC Address</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Net_Agents__c</fullName>
        <label>.Net Agents Old</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Deployment Option</label>
        <picklist>
            <picklistValues>
                <fullName>On-Premise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosted (SaaS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosted (SaaS Lite)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Server_Agents__c</fullName>
        <label>Java Agents Old</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>TRIAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRIAL EXPIRED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAID EXPIRED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DISABLED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Pro_Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRO_PAID</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>License</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Count__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LicenseHATest.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class LicenseHATest {
    
    static void createLicense() {
        Opportunity opp = [Select Id from Opportunity LIMIT 1];
        List<LicenseDetail__c>  licenses = new  List<LicenseDetail__c>();
        for( integer i =0; i<1; i++) {
            LicenseDetail__c lic = new LicenseDetail__c();
            lic.Product_Type__c = 'On-Premise';
            lic.License_BackendID__c = '100';
            lic.License_Expiry_Date__c = System.now().date().addDays(15);
            lic.Product_Type__c = AppDConstants.LICENSE_PRODUCT_TYPE_ON_PREMISE;
            //lic.Server_Agents__c  = 10;
            //lic.Net_Agents__c  = 10;
            lic.Stage__c = 'TRIAL';
            insert lic;
            licenses.add(lic);
            
            License_Agent__c laJava = new License_Agent__c();
            laJava.Agent_Type__c = 'Java';
            laJava.Count__c = 10;
            laJava.License__c = lic.id;
            insert laJava;
            License_Agent__c laNet = new License_Agent__c();
            laNet.Agent_Type__c = '.Net';
            laNet.Count__c = 10;
            laNet.License__c = lic.id;
            insert laNet;
            
            License_EUM_Details__c eum =  new License_EUM_Details__c();
	        eum.License__c = lic.id;
	        eum.AccountName__c = 'TestEUM';
	        insert eum;
	        
	        EUM_Mobile__c eumMobile = new EUM_Mobile__c();
	        eumMobile.Allow_overages__c = false;
	        eumMobile.License_EUM_Detail__c = eum.id;
	        eumMobile.Type__c = 'LITE';
	        eumMobile.Units__c = 1;
	        insert eumMobile;
	        
	        EUM_Web__c eumWeb = new EUM_Web__c();
	        eumWeb.Allow_overages__c = false;
	        eumWeb.License_EUM_Detail__c = eum.id;
	        eumWeb.Type__c = 'LITE';
	        eumWeb.Units__c = 1;
	        insert eumWeb;
                
        }
        
        //insert licenses;
        //insert licenseAgents;
        List<License_Opportunity__c> licOpps = new List<License_Opportunity__c>();
        for (integer i =0; i<licenses.size(); i++ ) {
            LicenseDetail__c lic = licenses.get(i);
            License_Opportunity__c licOpp = new License_Opportunity__c();
            licOpp.Opportunity__c = opp.id;
            licOpp.license__c = lic.id;
            licOpps.add(licOpp);
        }
        insert licOpps;
        
    }

    static testMethod void testHALicenseInit() {
        createLicense();
        String licenseId = 'a01U0000000LtsIIAS';
        LicenseDetail__c lic = [Select ID from LicenseDetail__c limit 1];
        if(lic==null){
            return;
        }
        licenseId = lic.Id;
        
        ApexPages.Standardcontroller stdCtrler = new ApexPages.Standardcontroller(new License_Opportunity__c());
        Pagereference ref = new PageReference('/apex/HALicensePage');
        Test.setCurrentPage(ref);
        ApexPages.currentPage().getParameters().put('licenseId',licenseId);
        
        HALicenseController ctrler = new HALicenseController(stdCtrler);
        
        System.assertNotEquals(ctrler.licenseDetailObj,null);
        System.assertEquals(ctrler.licenseDetailObj.IS_HA__c,true);
//        System.assertEquals(ctrler.licenseOpcode,HALicenseController.LICENSE_OPCODE_HA_LICENSE);
    }
    
    static testMethod void testHALicenseSaveFailureNoParameter() {
        createLicense();
        String licenseId = 'a01U0000000LtsIIAS';
        LicenseDetail__c lic = [Select ID from LicenseDetail__c limit 1];
        if(lic==null){
            return;
        }
        licenseId = lic.Id;
        
        ApexPages.Standardcontroller stdCtrler = new ApexPages.Standardcontroller(new License_Opportunity__c());
        Pagereference ref = new PageReference('/apex/HALicensePage');
        Test.setCurrentPage(ref);
        //ApexPages.currentPage().getParameters().put('licenseId',licenseId);
        
        HALicenseController ctrler = new HALicenseController(stdCtrler);
        
        try{
        PageReference nextPage = ctrler.doHaSave();
        System.assertEquals(nextPage , null);
        }catch(Exception e){}
    }
    
    static testMethod void testHALicenseSaveFailureBackend() {
        createLicense();
        String licenseId = 'a01U0000000LtsIIAS';
        LicenseDetail__c lic = [Select ID from LicenseDetail__c limit 1];
        if(lic==null){
            return;
        }
        licenseId = lic.Id;
        
        ApexPages.Standardcontroller stdCtrler = new ApexPages.Standardcontroller(new License_Opportunity__c());
        Pagereference ref = new PageReference('/apex/HALicensePage');
        Test.setCurrentPage(ref);
        ApexPages.currentPage().getParameters().put('licenseId',licenseId);
        
        HALicenseController ctrler = new HALicenseController(stdCtrler);
        
        try{
        PageReference nextPage = ctrler.dohaSave();
        System.assertEquals(nextPage , null);
        }catch(Exception e){}
    }
    
    static testMethod void testHALicenseSave() {
        createLicense();
        RESTAPI.unitTestMode = true;
        String licenseId = 'a01U0000000LtsIIAS';
        LicenseDetail__c lic = [Select ID from LicenseDetail__c limit 1];
        if(lic==null){
            return;
        }
        licenseId = lic.Id;
        
        BackendConstants.OPCODE_URL_MAP.put(BackendConstants.OPCODE_HA_LICENSE,'http://license.ha');
        ApexPages.Standardcontroller stdCtrler = new ApexPages.Standardcontroller(new License_Opportunity__c());
        Pagereference ref = new PageReference('/apex/HALicensePage');
        Test.setCurrentPage(ref);
        ApexPages.currentPage().getParameters().put('licenseId',licenseId);
        
        HALicenseController ctrler = new HALicenseController(stdCtrler);
        
        ctrler.licenseDetailObj.MAC_Address__c ='aa:bb:cc:dd:ee:ff';
        try{
        PageReference nextPage = ctrler.dohaSave();
        }catch(Exception e){}
        //System.assertNotEquals(nextPage , null);
    }
    
    
    static testMethod void testHALicenseCancel() {
        createLicense();
        String licenseId = 'a01U0000000LtsIIAS';
        LicenseDetail__c lic = [Select ID from LicenseDetail__c limit 1];
        if(lic==null){
            return;
        }
        licenseId = lic.Id;
        
        ApexPages.Standardcontroller stdCtrler = new ApexPages.Standardcontroller(new License_Opportunity__c());
        Pagereference ref = new PageReference('/apex/HALicensePage');
        Test.setCurrentPage(ref);
        ApexPages.currentPage().getParameters().put('licenseId',licenseId);
        
        HALicenseController ctrler = new HALicenseController(stdCtrler);
        
        PageReference nextPage = ctrler.cancel();
        System.assertNotEquals(nextPage , null);
    }
    
    static testMethod void testHALicenseInit2() {
        
		Opportunity opp = [Select Id from Opportunity LIMIT 1];
        
            LicenseDetail__c lic = new LicenseDetail__c();
            lic.Product_Type__c = 'On-Premise';
            lic.License_BackendID__c = '100';
            lic.License_Expiry_Date__c = System.now().date().addDays(15);
            lic.Product_Type__c = AppDConstants.LICENSE_PRODUCT_TYPE_ON_PREMISE;
            //lic.Server_Agents__c  = 10;
            //lic.Net_Agents__c  = 10;
            lic.Stage__c = 'TRIAL';
            insert lic;
            
            License_Agent__c laJava = new License_Agent__c();
            laJava.Agent_Type__c = 'Java';
            laJava.Count__c = 10;
            laJava.License__c = lic.id;
            insert laJava;
            License_Agent__c laNet = new License_Agent__c();
            laNet.Agent_Type__c = '.Net';
            laNet.Count__c = 10;
            laNet.License__c = lic.id;
            insert laNet;
            
            License_EUM_Details__c eum =  new License_EUM_Details__c();
	        eum.License__c = lic.id;
	        eum.AccountName__c = 'TestEUM';
	        insert eum;
	        
	        EUM_Mobile__c eumMobile = new EUM_Mobile__c();
	        eumMobile.Allow_overages__c = false;
	        eumMobile.License_EUM_Detail__c = eum.id;
	        eumMobile.Type__c = 'LITE';
	        eumMobile.Units__c = 1;
	        insert eumMobile;
	        
	        EUM_Web__c eumWeb = new EUM_Web__c();
	        eumWeb.Allow_overages__c = false;
	        eumWeb.License_EUM_Detail__c = eum.id;
	        eumWeb.Type__c = 'LITE';
	        eumWeb.Units__c = 1;
	        insert eumWeb;
                
            License_Opportunity__c licOpp = new License_Opportunity__c();
            licOpp.Opportunity__c = opp.id;
            licOpp.license__c = lic.id;
        	insert licOpp;
			
		
        String licenseId = lic.Id;
        
        ApexPages.Standardcontroller stdCtrler = new ApexPages.Standardcontroller(new License_Opportunity__c());
        Pagereference ref = new PageReference('/apex/HALicensePage');
        Test.setCurrentPage(ref);
        ApexPages.currentPage().getParameters().put('licenseId',licenseId);
        
        HALicenseController ctrler = new HALicenseController(stdCtrler);
        
        PageReference nextPage = ctrler.cancel();
        System.assertNotEquals(nextPage , null);
    }
    
    static testMethod void testHALicenseInit3() {
        
		Opportunity opp = [Select Id from Opportunity LIMIT 1];
        
            LicenseDetail__c lic = new LicenseDetail__c();
            lic.Product_Type__c = 'On-Premise';
            lic.License_BackendID__c = '100';
            lic.License_Expiry_Date__c = System.now().date().addDays(15);
            lic.Product_Type__c = AppDConstants.LICENSE_PRODUCT_TYPE_ON_PREMISE;
            //lic.Server_Agents__c  = 10;
            //lic.Net_Agents__c  = 10;
            lic.Stage__c = 'TRIAL';
            insert lic;
            
            License_Agent__c laJava = new License_Agent__c();
            laJava.Agent_Type__c = 'Java';
            laJava.Count__c = 10;
            laJava.License__c = lic.id;
            insert laJava;
            License_Agent__c laNet = new License_Agent__c();
            laNet.Agent_Type__c = '.Net';
            laNet.Count__c = 10;
            laNet.License__c = lic.id;
            insert laNet;
            
            License_EUM_Details__c eum =  new License_EUM_Details__c();
	        eum.License__c = lic.id;
	        eum.AccountName__c = 'TestEUM';
	        insert eum;
	        
	        EUM_Mobile__c eumMobile = new EUM_Mobile__c();
	        eumMobile.Allow_overages__c = false;
	        eumMobile.License_EUM_Detail__c = eum.id;
	        eumMobile.Type__c = 'LITE';
	        eumMobile.Units__c = 2;
	        insert eumMobile;
	        
	        EUM_Web__c eumWeb = new EUM_Web__c();
	        eumWeb.Allow_overages__c = false;
	        eumWeb.License_EUM_Detail__c = eum.id;
	        eumWeb.Type__c = 'LITE';
	        eumWeb.Units__c = 2;
	        insert eumWeb;
                
            License_Opportunity__c licOpp = new License_Opportunity__c();
            licOpp.Opportunity__c = opp.id;
            licOpp.license__c = lic.id;
        	insert licOpp;
			
		
        String licenseId = lic.Id;
        
        ApexPages.Standardcontroller stdCtrler = new ApexPages.Standardcontroller(new License_Opportunity__c());
        Pagereference ref = new PageReference('/apex/HALicensePage');
        Test.setCurrentPage(ref);
        ApexPages.currentPage().getParameters().put('licenseId',licenseId);
        
        HALicenseController ctrler = new HALicenseController(stdCtrler);
        
        PageReference nextPage = ctrler.cancel();
        System.assertNotEquals(nextPage , null);
    }
    
    static testMethod void testHALicenseInit4() {
        
		Opportunity opp = [Select Id from Opportunity LIMIT 1];
        
            LicenseDetail__c lic = new LicenseDetail__c();
            lic.Product_Type__c = 'On-Premise';
            lic.License_BackendID__c = '100';
            lic.License_Expiry_Date__c = System.now().date().addDays(15);
            lic.Product_Type__c = AppDConstants.LICENSE_PRODUCT_TYPE_ON_PREMISE;
            //lic.Server_Agents__c  = 10;
            //lic.Net_Agents__c  = 10;
            lic.Stage__c = 'TRIAL';
            insert lic;
            
            License_Agent__c laJava = new License_Agent__c();
            laJava.Agent_Type__c = 'Java';
            laJava.Count__c = 10;
            laJava.License__c = lic.id;
            insert laJava;
            License_Agent__c laNet = new License_Agent__c();
            laNet.Agent_Type__c = '.Net';
            laNet.Count__c = 10;
            laNet.License__c = lic.id;
            insert laNet;
            
            License_EUM_Details__c eum =  new License_EUM_Details__c();
	        eum.License__c = lic.id;
	        eum.AccountName__c = 'TestEUM';
	        insert eum;
	        
	        EUM_Mobile__c eumMobile = new EUM_Mobile__c();
	        eumMobile.Allow_overages__c = true;
	        eumMobile.License_EUM_Detail__c = eum.id;
	        eumMobile.Type__c = 'LITE';
	        eumMobile.Units__c = 2;
	        insert eumMobile;
	        
	        EUM_Web__c eumWeb = new EUM_Web__c();
	        eumWeb.Allow_overages__c = true;
	        eumWeb.License_EUM_Detail__c = eum.id;
	        eumWeb.Type__c = 'LITE';
	        eumWeb.Units__c = 2;
	        insert eumWeb;
                
            License_Opportunity__c licOpp = new License_Opportunity__c();
            licOpp.Opportunity__c = opp.id;
            licOpp.license__c = lic.id;
        	insert licOpp;
			
		
        String licenseId = lic.Id;
        
        ApexPages.Standardcontroller stdCtrler = new ApexPages.Standardcontroller(new License_Opportunity__c());
        Pagereference ref = new PageReference('/apex/HALicensePage');
        Test.setCurrentPage(ref);
        ApexPages.currentPage().getParameters().put('licenseId',licenseId);
        
        HALicenseController ctrler = new HALicenseController(stdCtrler);
        
        PageReference nextPage = ctrler.cancel();
        System.assertNotEquals(nextPage , null);
    }
    
    static testMethod void testHALicenseValidateWithLicenseObjectNull() {
        
		Opportunity opp = [Select Id from Opportunity LIMIT 1];
        
            LicenseDetail__c lic = new LicenseDetail__c();
            lic.Product_Type__c = 'On-Premise';
            lic.License_BackendID__c = '100';
            lic.License_Expiry_Date__c = System.now().date().addDays(15);
            lic.Product_Type__c = AppDConstants.LICENSE_PRODUCT_TYPE_ON_PREMISE;
            //lic.Server_Agents__c  = 10;
            //lic.Net_Agents__c  = 10;
            lic.Stage__c = 'TRIAL';
            insert lic;
            
            License_Agent__c laJava = new License_Agent__c();
            laJava.Agent_Type__c = 'Java';
            laJava.Count__c = 10;
            laJava.License__c = lic.id;
            insert laJava;
            License_Agent__c laNet = new License_Agent__c();
            laNet.Agent_Type__c = '.Net';
            laNet.Count__c = 10;
            laNet.License__c = lic.id;
            insert laNet;
            
            License_EUM_Details__c eum =  new License_EUM_Details__c();
	        eum.License__c = lic.id;
	        eum.AccountName__c = 'TestEUM';
	        insert eum;
	        
	        EUM_Mobile__c eumMobile = new EUM_Mobile__c();
	        eumMobile.Allow_overages__c = true;
	        eumMobile.License_EUM_Detail__c = eum.id;
	        eumMobile.Type__c = 'LITE';
	        eumMobile.Units__c = 2;
	        insert eumMobile;
	        
	        EUM_Web__c eumWeb = new EUM_Web__c();
	        eumWeb.Allow_overages__c = true;
	        eumWeb.License_EUM_Detail__c = eum.id;
	        eumWeb.Type__c = 'LITE';
	        eumWeb.Units__c = 2;
	        insert eumWeb;
                
            License_Opportunity__c licOpp = new License_Opportunity__c();
            licOpp.Opportunity__c = opp.id;
            licOpp.license__c = lic.id;
        	insert licOpp;
			
		
        String licenseId = lic.Id;
        
        ApexPages.Standardcontroller stdCtrler = new ApexPages.Standardcontroller(new License_Opportunity__c());
        Pagereference ref = new PageReference('/apex/HALicensePage');
        Test.setCurrentPage(ref);
        ApexPages.currentPage().getParameters().put('licenseId',licenseId);
        
        HALicenseController ctrler = new HALicenseController(stdCtrler);
        ctrler.licenseDetailObj = null;
        
        ctrler.validateObject();
    }
    
    static testMethod void testHALicenseValidateWithMacAddressNull() {
        
		Opportunity opp = [Select Id from Opportunity LIMIT 1];
        
            LicenseDetail__c lic = new LicenseDetail__c();
            lic.Product_Type__c = 'On-Premise';
            lic.License_BackendID__c = '100';
            lic.License_Expiry_Date__c = System.now().date().addDays(15);
            lic.Product_Type__c = AppDConstants.LICENSE_PRODUCT_TYPE_ON_PREMISE;
            //lic.Server_Agents__c  = 10;
            //lic.Net_Agents__c  = 10;
            lic.Stage__c = 'TRIAL';
            insert lic;
            
            License_Agent__c laJava = new License_Agent__c();
            laJava.Agent_Type__c = 'Java';
            laJava.Count__c = 10;
            laJava.License__c = lic.id;
            insert laJava;
            License_Agent__c laNet = new License_Agent__c();
            laNet.Agent_Type__c = '.Net';
            laNet.Count__c = 10;
            laNet.License__c = lic.id;
            insert laNet;
            
            License_EUM_Details__c eum =  new License_EUM_Details__c();
	        eum.License__c = lic.id;
	        eum.AccountName__c = 'TestEUM';
	        insert eum;
	        
	        EUM_Mobile__c eumMobile = new EUM_Mobile__c();
	        eumMobile.Allow_overages__c = true;
	        eumMobile.License_EUM_Detail__c = eum.id;
	        eumMobile.Type__c = 'LITE';
	        eumMobile.Units__c = 2;
	        insert eumMobile;
	        
	        EUM_Web__c eumWeb = new EUM_Web__c();
	        eumWeb.Allow_overages__c = true;
	        eumWeb.License_EUM_Detail__c = eum.id;
	        eumWeb.Type__c = 'LITE';
	        eumWeb.Units__c = 2;
	        insert eumWeb;
                
            License_Opportunity__c licOpp = new License_Opportunity__c();
            licOpp.Opportunity__c = opp.id;
            licOpp.license__c = lic.id;
        	insert licOpp;
			
		
        String licenseId = lic.Id;
        
        ApexPages.Standardcontroller stdCtrler = new ApexPages.Standardcontroller(new License_Opportunity__c());
        Pagereference ref = new PageReference('/apex/HALicensePage');
        Test.setCurrentPage(ref);
        ApexPages.currentPage().getParameters().put('licenseId',licenseId);
        
        HALicenseController ctrler = new HALicenseController(stdCtrler);
        
        ctrler.validateObject();
    }
    
    static testMethod void testHALicenseValidateWithInValidMacAddress() {
        
		Opportunity opp = [Select Id from Opportunity LIMIT 1];
        
            LicenseDetail__c lic = new LicenseDetail__c();
            lic.Product_Type__c = 'On-Premise';
            lic.License_BackendID__c = '100';
            lic.License_Expiry_Date__c = System.now().date().addDays(15);
            lic.Product_Type__c = AppDConstants.LICENSE_PRODUCT_TYPE_ON_PREMISE;
            //lic.Server_Agents__c  = 10;
            //lic.Net_Agents__c  = 10;
            lic.Stage__c = 'TRIAL';
            insert lic;
            
            License_Agent__c laJava = new License_Agent__c();
            laJava.Agent_Type__c = 'Java';
            laJava.Count__c = 10;
            laJava.License__c = lic.id;
            insert laJava;
            License_Agent__c laNet = new License_Agent__c();
            laNet.Agent_Type__c = '.Net';
            laNet.Count__c = 10;
            laNet.License__c = lic.id;
            insert laNet;
            
            License_EUM_Details__c eum =  new License_EUM_Details__c();
	        eum.License__c = lic.id;
	        eum.AccountName__c = 'TestEUM';
	        insert eum;
	        
	        EUM_Mobile__c eumMobile = new EUM_Mobile__c();
	        eumMobile.Allow_overages__c = true;
	        eumMobile.License_EUM_Detail__c = eum.id;
	        eumMobile.Type__c = 'LITE';
	        eumMobile.Units__c = 2;
	        insert eumMobile;
	        
	        EUM_Web__c eumWeb = new EUM_Web__c();
	        eumWeb.Allow_overages__c = true;
	        eumWeb.License_EUM_Detail__c = eum.id;
	        eumWeb.Type__c = 'LITE';
	        eumWeb.Units__c = 2;
	        insert eumWeb;
                
            License_Opportunity__c licOpp = new License_Opportunity__c();
            licOpp.Opportunity__c = opp.id;
            licOpp.license__c = lic.id;
        	insert licOpp;
			
		
        String licenseId = lic.Id;
        
        ApexPages.Standardcontroller stdCtrler = new ApexPages.Standardcontroller(new License_Opportunity__c());
        Pagereference ref = new PageReference('/apex/HALicensePage');
        Test.setCurrentPage(ref);
        ApexPages.currentPage().getParameters().put('licenseId',licenseId);
        
        HALicenseController ctrler = new HALicenseController(stdCtrler);
        ctrler.licenseDetailObj.MAC_Address__c = '11';
        ctrler.validateObject();
    }
}