src/objects/EUM_Mobile__c.object
<CustomObject>
    <fields>
        <fullName>Allow_overages__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow overages</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License_EUM_Detail__c</fullName>
        <label>License EUM Detail</label>
        <referenceTo>License_EUM_Details__c</referenceTo>
        <relationshipLabel>EUM Mobile</relationshipLabel>
        <relationshipName>EUM_Mobile</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>EUM Mobile Type</label>
        <picklist>
            <picklistValues>
                <fullName>LITE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <defaultValue>1</defaultValue>
        <label>EUM Mobile Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>EUM Mobile</label>
    <nameField>
        <label>License EUM Mobile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EUM Mobile</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EUM_Web__c.object
<CustomObject>
    <fields>
        <fullName>Allow_overages__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow overages</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License_EUM_Detail__c</fullName>
        <label>License EUM Detail</label>
        <referenceTo>License_EUM_Details__c</referenceTo>
        <relationshipLabel>EUM Web</relationshipLabel>
        <relationshipName>EUM_Web</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>LITE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <label>Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>EUM Web</label>
    <nameField>
        <label>License EUM Web Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EUM Web</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/License_Agent__c.object
<CustomObject>
    <description>License Agent which will have:
Agent Type as Java/.Net/PHP
and Agent count</description>
    <fields>
        <fullName>Agent_Type__c</fullName>
        <label>Agent Type</label>
        <picklist>
            <picklistValues>
                <fullName>Java</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>.NET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PHP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NodeJs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Database</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Python</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transaction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Log</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Machine</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <label>License</label>
        <referenceTo>LicenseDetail__c</referenceTo>
        <relationshipLabel>License Agents</relationshipLabel>
        <relationshipName>License_Agents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>License Agent</label>
    <nameField>
        <label>License Units Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Agents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/License_EUM_Details__c.object
<CustomObject>
    <fields>
        <fullName>AccountName__c</fullName>
        <label>EUM Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Agent_Units__c</fullName>
        <label>EUM Agents</label>
        <precision>10</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Allow_Overages__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EUM Allow Overages</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Import_EUM__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Import EUM</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>License to which this EUM details are associated with.</inlineHelpText>
        <label>License</label>
        <referenceTo>LicenseDetail__c</referenceTo>
        <relationshipLabel>License EUM Details</relationshipLabel>
        <relationshipName>License_EUM_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>RUM_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <label>RUM Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>EUM License Type</inlineHelpText>
        <label>EUM Type</label>
        <picklist>
            <picklistValues>
                <fullName>LITE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>License EUM Detail</label>
    <nameField>
        <label>License EUM Detail(s) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License EUM Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/License_History_Property__c.object
<CustomObject>
    <fields>
        <fullName>License_History_Tracking__c</fullName>
        <label>License History Tracking</label>
        <referenceTo>License_History_Tracking__c</referenceTo>
        <relationshipLabel>License History Property</relationshipLabel>
        <relationshipName>License_History_Property</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>New_Value__c</fullName>
        <label>New Value</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Old_Value__c</fullName>
        <label>Old Value</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>Property_Field_Name__c</fullName>
        <label>Property Field Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Property_Object_Name__c</fullName>
        <label>Property Object Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>License History Property</label>
    <nameField>
        <label>License History Property Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License History Property</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/License_History_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>License_Operation__c</fullName>
        <label>License Operation</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License</label>
        <referenceTo>LicenseDetail__c</referenceTo>
        <relationshipLabel>License History Tracking</relationshipLabel>
        <relationshipName>License_History_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <label>License History Tracking</label>
    <nameField>
        <label>License History Tracking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License History Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LicenseDetail__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>License_BackendID__c</fullName>
        <label>License_BackendID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_Expiry_Date__c</fullName>
        <label>License Expiration Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Net_Agents__c</fullName>
        <label>.Net Agents Old</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Deployment Option</label>
        <picklist>
            <picklistValues>
                <fullName>On-Premise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosted (SaaS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosted (SaaS Lite)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>RUM_Enabled__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Enable Real User Monitoring?</description>
        <inlineHelpText>Enable Real User Monitoring?</inlineHelpText>
        <label>RUM Enabled</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Server_Agents__c</fullName>
        <label>Java Agents Old</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>TRIAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRIAL EXPIRED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAID EXPIRED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DISABLED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Pro_Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRO_PAID</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>License</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Status__c.object
<CustomObject>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads Owners Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestLicenseHistoryController.cls
/*
	TestLicenseHistoryController contains test methods for License History Tracking implementation. 
*/

@IsTest
public with sharing class TestLicenseHistoryController {
	public static testMethod void testLicenseHistoryController_1(){
		LicenseDetail__c lic = new LicenseDetail__c();
		lic.Product_Type__c = 'On-Premise';
        lic.License_BackendID__c = '100';
        lic.License_Expiry_Date__c = System.now().date().addDays(15);
        lic.Product_Type__c = AppDConstants.LICENSE_PRODUCT_TYPE_ON_PREMISE;
        lic.Server_Agents__c  = 10;
        lic.Net_Agents__c  = 10;
        lic.Stage__c = 'TRIAL';
        insert lic;
        
        License_History_Tracking__c lht = new License_History_Tracking__c();
        lht.License__c = lic.id;
        lht.License_Operation__c = 'TRIAL';
        lht.Status__c = 'SUCCESS';
        insert lht;
        
        License_History_Property__c lhp = new License_History_Property__c();
        lhp.License_History_Tracking__c = lht.id;
        lhp.New_Value__c = 'PAID';
        lhp.Old_Value__c = 'TRIAL';
        lhp.Property_Field_Name__c = 'Stage__c';
        lhp.Property_Object_Name__c = 'LicenseDetail__c';
        insert lhp;
        
        LicenseHistoryController_V2 lhc = new LicenseHistoryController_V2();
        lhc.setLicenseIdCtrller(lic.id+'');
        String licId = lhc.getLicenseIdCtrller();
        List<LicenseHistoryController_V2.HistoryWrapper> lhw = lhc.licenseHistories;
        for(LicenseHistoryController_V2.HistoryWrapper hw: lhw){
        	String actionString = hw.getActionString();
        }
	}
	
	public static testMethod void testLicenseHistoryController_2(){
		LicenseDetail__c lic = new LicenseDetail__c();
		lic.Product_Type__c = 'On-Premise';
        lic.License_BackendID__c = '100';
        lic.License_Expiry_Date__c = System.now().date().addDays(15);
        lic.Product_Type__c = AppDConstants.LICENSE_PRODUCT_TYPE_ON_PREMISE;
        lic.Server_Agents__c  = 10;
        lic.Net_Agents__c  = 10;
        lic.Stage__c = 'TRIAL';
        insert lic;
        
        License_EUM_Details__c eum =  new License_EUM_Details__c();
        eum.License__c = lic.id;
        eum.Type__c = 'LITE';
        eum.Allow_Overages__c = true;
        eum.AccountName__c = 'TestEUM';
        insert eum;
        
        EUM_Mobile__c eumMobile = new EUM_Mobile__c();
        eumMobile.Allow_overages__c = false;
        eumMobile.License_EUM_Detail__c = eum.id;
        eumMobile.Type__c = 'LITE';
        eumMobile.Units__c = 1;
        insert eumMobile;
        
        EUM_Web__c eumWeb = new EUM_Web__c();
        eumWeb.Allow_overages__c = false;
        eumWeb.License_EUM_Detail__c = eum.id;
        eumWeb.Type__c = 'LITE';
        eumWeb.Units__c = 1;
        insert eumWeb;
        
        lic = (LicenseDetail__c)DataLayerConstants.fetchSingle('LicenseDetail__c', lic.id);
        Map<String,List<SObject>> relationalLicenseHistoryMap = new Map<String,List<SObject>>();
        LicenseUtil.saveHistory(lic,relationalLicenseHistoryMap,'IN_PROGRESS',false);
	}
	
	public static testMethod void testLicenseHistoryController_3(){
		LicenseDetail__c lic = new LicenseDetail__c();
		lic.Product_Type__c = 'On-Premise';
        lic.License_BackendID__c = '100';
        lic.License_Expiry_Date__c = System.now().date().addDays(15);
        lic.Product_Type__c = AppDConstants.LICENSE_PRODUCT_TYPE_ON_PREMISE;
        lic.Server_Agents__c  = 10;
        lic.Net_Agents__c  = 10;
        lic.Stage__c = 'TRIAL';
        insert lic;
        
        License_EUM_Details__c eum =  new License_EUM_Details__c();
        eum.License__c = lic.id;
        eum.Type__c = 'LITE';
        eum.Allow_Overages__c = true;
        eum.AccountName__c = 'TestEUM';
        insert eum;
        
        License_History_Tracking__c lht = new License_History_Tracking__c();
        lht.License__c = lic.id;
        lht.License_Operation__c = 'TRIAL';
        lht.Status__c = 'IN_PROGRESS';
        insert lht;
        
        License_History_Property__c lhp = new License_History_Property__c();
        lhp.License_History_Tracking__c = lht.id;
        lhp.New_Value__c = 'PAID';
        lhp.Old_Value__c = 'TRIAL';
        lhp.Property_Field_Name__c = 'Stage__c';
        lhp.Property_Object_Name__c = 'LicenseDetail__c';
        insert lhp;
        
        License_History_Property__c lhp2 = new License_History_Property__c();
        lhp2.License_History_Tracking__c = lht.id;
        lhp2.New_Value__c = '123123';
        lhp2.Old_Value__c = '234234';
        lhp2.Property_Field_Name__c = 'License_BackendID__c';
        lhp2.Property_Object_Name__c = 'LicenseDetail__c';
        insert lhp2;
        
        lic = (LicenseDetail__c)DataLayerConstants.fetchSingle('LicenseDetail__c', lic.id);
        
       	LicenseUtil.updateLicenseHistory(lic,lic,'SUCCESS');
	}
	
	public static testMethod void testLicenseHistoryController_4(){
		LicenseDetail__c lic = new LicenseDetail__c();
		lic.Product_Type__c = 'On-Premise';
        lic.License_BackendID__c = '100';
        lic.License_Expiry_Date__c = System.now().date().addDays(15);
        lic.Product_Type__c = AppDConstants.LICENSE_PRODUCT_TYPE_ON_PREMISE;
        lic.Server_Agents__c  = 10;
        lic.Net_Agents__c  = 10;
        lic.Stage__c = 'TRIAL';
        insert lic;
        
        License_Agent__c laJava = new License_Agent__c();
        laJava.Agent_Type__c = 'Java';
        laJava.Count__c = 10;
        laJava.License__c = lic.id;
        insert laJava;
        
        License_Agent__c laNet = new License_Agent__c();
        laNet.Agent_Type__c = '.NET';
        laNet.Count__c = 10;
        laNet.License__c = lic.id;
        insert laNet;
        
        License_Agent__c laPHP = new License_Agent__c();
        laPHP.Agent_Type__c = 'PHP';
        laPHP.Count__c = 10;
        laPHP.License__c = lic.id;
        insert laPHP;
        
        License_Agent__c laMachine = new License_Agent__c();
        laMachine.Agent_Type__c = 'Machine';
        laMachine.Count__c = 10;
        laMachine.License__c = lic.id;
        insert laMachine;
        
        License_EUM_Details__c eum =  new License_EUM_Details__c();
        eum.License__c = lic.id;
        eum.Type__c = 'LITE';
        eum.Allow_Overages__c = true;
        eum.AccountName__c = 'TestEUM';
        eum.Agent_Units__c = 1;
        eum.Import_EUM__c = false;
        eum.RUM_Enabled__c = true;
        insert eum;
        
        EUM_Mobile__c eumMobile = new EUM_Mobile__c();
        eumMobile.Allow_overages__c = false;
        eumMobile.License_EUM_Detail__c = eum.id;
        eumMobile.Type__c = 'LITE';
        eumMobile.Units__c = 1;
        insert eumMobile;
        
        EUM_Web__c eumWeb = new EUM_Web__c();
        eumWeb.Allow_overages__c = false;
        eumWeb.License_EUM_Detail__c = eum.id;
        eumWeb.Type__c = 'LITE';
        eumWeb.Units__c = 1;
        insert eumWeb;
        
        lic = (LicenseDetail__c)DataLayerConstants.fetchSingle('LicenseDetail__c', lic.id);
        
        Map<String,List<SObject>> relationalLicenseHistoryMap = new Map<String,List<SObject>>();
        LicenseUtil.saveHistory(lic,relationalLicenseHistoryMap,'IN_PROGRESS',false);
       	LicenseUtil.updateLicenseHistory(lic,lic,'Failed');
	}
}