src/objects/EUM_Mobile__c.object
<CustomObject>
    <fields>
        <fullName>Allow_overages__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow overages</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License_EUM_Detail__c</fullName>
        <label>License EUM Detail</label>
        <referenceTo>License_EUM_Details__c</referenceTo>
        <relationshipLabel>EUM Mobile</relationshipLabel>
        <relationshipName>EUM_Mobile</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>EUM Mobile Type</label>
        <picklist>
            <picklistValues>
                <fullName>LITE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <defaultValue>1</defaultValue>
        <label>EUM Mobile Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>EUM Mobile</label>
    <nameField>
        <label>License EUM Mobile Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EUM Mobile</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/EUM_Web__c.object
<CustomObject>
    <fields>
        <fullName>Allow_overages__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Allow overages</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License_EUM_Detail__c</fullName>
        <label>License EUM Detail</label>
        <referenceTo>License_EUM_Details__c</referenceTo>
        <relationshipLabel>EUM Web</relationshipLabel>
        <relationshipName>EUM_Web</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>LITE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Units__c</fullName>
        <label>Units</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>EUM Web</label>
    <nameField>
        <label>License EUM Web Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>EUM Web</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/License_Agent__c.object
<CustomObject>
    <description>License Agent which will have:
Agent Type as Java/.Net/PHP
and Agent count</description>
    <fields>
        <fullName>Agent_Type__c</fullName>
        <label>Agent Type</label>
        <picklist>
            <picklistValues>
                <fullName>Java</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>.NET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PHP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NodeJs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Database</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Python</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transaction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Log</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Machine</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <label>License</label>
        <referenceTo>LicenseDetail__c</referenceTo>
        <relationshipLabel>License Agents</relationshipLabel>
        <relationshipName>License_Agents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>License Agent</label>
    <nameField>
        <label>License Units Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Agents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/License_EUM_Details__c.object
<CustomObject>
    <fields>
        <fullName>Access_Key__c</fullName>
        <label>EUM Access Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountName__c</fullName>
        <label>EUM Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Allow_Overages__c</fullName>
        <defaultValue>false</defaultValue>
        <label>EUM Allow Overages</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>License to which this EUM details are associated with.</inlineHelpText>
        <label>License</label>
        <referenceTo>LicenseDetail__c</referenceTo>
        <relationshipLabel>License EUM Details</relationshipLabel>
        <relationshipName>License_EUM_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <inlineHelpText>EUM License Type</inlineHelpText>
        <label>EUM Type</label>
        <picklist>
            <picklistValues>
                <fullName>LITE</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRO</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>License EUM Detail</label>
    <nameField>
        <label>License EUM Detail(s) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License EUM Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LicenseDetail__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Custom_URL_Name__c</fullName>
        <label>Customer SaaS URL</label>
        <length>63</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Database_Agents_Rollup__c</fullName>
        <label>Database Agents</label>
        <summarizedField>License_Agent__c.Count__c</summarizedField>
        <summaryFilterItems>
            <field>License_Agent__c.Agent_Type__c</field>
            <operation>equals</operation>
            <value>Database</value>
        </summaryFilterItems>
        <summaryForeignKey>License_Agent__c.License__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Java_Agents_Rollup__c</fullName>
        <label>Java Agents</label>
        <summarizedField>License_Agent__c.Count__c</summarizedField>
        <summaryFilterItems>
            <field>License_Agent__c.Agent_Type__c</field>
            <operation>equals</operation>
            <value>Java</value>
        </summaryFilterItems>
        <summaryForeignKey>License_Agent__c.License__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>License_BackendID__c</fullName>
        <label>License_BackendID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_Expiry_Date__c</fullName>
        <label>License Expiration Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MAC_Address__c</fullName>
        <description>MAC Address of the machine to be registered with license</description>
        <label>MAC Address</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Machine_Agents_Rollup__c</fullName>
        <label>Additional Machine Agents</label>
        <summarizedField>License_Agent__c.Count__c</summarizedField>
        <summaryFilterItems>
            <field>License_Agent__c.Agent_Type__c</field>
            <operation>equals</operation>
            <value>Machine</value>
        </summaryFilterItems>
        <summaryForeignKey>License_Agent__c.License__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Net_Agents_Rollup__c</fullName>
        <label>.Net Agents</label>
        <summarizedField>License_Agent__c.Count__c</summarizedField>
        <summaryFilterItems>
            <field>License_Agent__c.Agent_Type__c</field>
            <operation>equals</operation>
            <value>.Net</value>
        </summaryFilterItems>
        <summaryForeignKey>License_Agent__c.License__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>NodeJs_Agents_Rollup__c</fullName>
        <label>NodeJs Agents</label>
        <summarizedField>License_Agent__c.Count__c</summarizedField>
        <summaryFilterItems>
            <field>License_Agent__c.Agent_Type__c</field>
            <operation>equals</operation>
            <value>NodeJs</value>
        </summaryFilterItems>
        <summaryForeignKey>License_Agent__c.License__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>PHP_Agents_Rollup__c</fullName>
        <label>PHP Agents</label>
        <summarizedField>License_Agent__c.Count__c</summarizedField>
        <summaryFilterItems>
            <field>License_Agent__c.Agent_Type__c</field>
            <operation>equals</operation>
            <value>PHP</value>
        </summaryFilterItems>
        <summaryForeignKey>License_Agent__c.License__c</summaryForeignKey>
        <summaryOperation>sum</summaryOperation>
        <type>Summary</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Deployment Option</label>
        <picklist>
            <picklistValues>
                <fullName>On-Premise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosted (SaaS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosted (SaaS Lite)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>TRIAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRIAL EXPIRED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAID EXPIRED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DISABLED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Transaction_ID__c</fullName>
        <label>Transaction ID</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Pro_Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PRO_PAID</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>License</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/HistoryMap.cls
/*
 * HistoryMap class maintains Maps which contains object as key and values as list of fields or relational object names.
*/
public with sharing class HistoryMap {
	
	/*
		Map contains Field API name as key and label as value. This map is used in LicenseHistoryController_V2 to show 
		license history details in Audit trial UI.
	*/
	public static Map<String,Map<String,String>> objectsFieldsAndLabelNamesMap = new Map<String,Map<String,String>>
														{
															'LicenseDetail__c'=> new Map<String,String>{
																											'Product_Type__c' => 'Deployment-Option','Stage__c' => 'Stage','Product_Type__c' => 'Deployment-Option',
																											'License_Expiry_Date__c' => 'Expiry Date','Java_Agents_Rollup__c' => 'Java','Net_Agents_Rollup__c' => '.Net',
																											'Machine_Agents_Rollup__c' => 'Machine','Database_Agents_Rollup__c' => 'Database','NodeJs_Agents_Rollup__c' => 'NodeJs',
																											'License_BackendID__c' => 'License BackendID',
																											'PHP_Agents_Rollup__c' => 'PHP','MAC_Address__c' => 'Mac Address','Custom_URL_Name__c' => 'SAAS URL','Transaction_ID__c' => 'Transaction Id'
																										},
															'EUM_Web__c' => new Map<String,String>{
																									'Allow_overages__c' => 'EUM Web Overages','Type__c' => 'EUM Web Type',
																									'Units__c' => 'EUM Web Units'
																								},
															'EUM_Mobile__c' => new Map<String,String>{
																									'Allow_overages__c' => 'EUM Mobile Overages','Type__c' => 'EUM Mobile Type',
																									'Units__c' => 'EUM Mobile Units'
																								}
														};																
	
	/*
		The Map contains object name as key and list of field names as values.
	*/
	public static Map<String,List<String>> objectAndFieldsMap = new Map<String,List<String>>
												{
													'LicenseDetail__c'=> new List<String>{
											   												'Custom_URL_Name__c','Product_Type__c',
											                                         		'License_Expiry_Date__c','MAC_Address__c',
											                                         		'Stage__c','License_BackendID__c',
											                                         		'Java_Agents_Rollup__c','Net_Agents_Rollup__c',
											                                         		'Machine_Agents_Rollup__c','PHP_Agents_Rollup__c',
											                                         		'Database_Agents_Rollup__c','NodeJs_Agents_Rollup__c',
											                                         		'Transaction_ID__c'
											                                         },
											    	'License_EUM_Details__c'=> new List<String>{
											   												'AccountName__c','Access_Key__c'
											                                         },
													'License_Agent__c'=> new List<String>{
											   												'Agent_Type__c','Count__c'
											                                         },
													'EUM_Web__c'=> new List<String>{
											   												'Allow_overages__c','Type__c','Units__c'
											                                         },
													'EUM_Mobile__c'=> new List<String>{
											   												'Allow_overages__c','Type__c','Units__c'
											                                         }											                                         
											   };
	
	/*
		The Map contains object name as key and list of relational object names as values.
	*/											   
	public static Map<String,List<String>> relatedObjectsMap = new Map<String,List<String>>
												{
													'LicenseDetail__c'=> new List<String>{
											   												'License_EUM_Details__r','License_Agents__r',
											   												'License_EUM_Details__r.EUM_Web__r','License_EUM_Details__r.EUM_Mobile__r'
											            	                             }
												};
}