src/objects/Lead.object
<CustomObject>
    <fields>
        <fullName>AppJam_Presenter__c</fullName>
        <defaultValue>false</defaultValue>
        <label>AppJam Presenter</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>App_Map_First_Visit__c</fullName>
        <label>App Map First Visit</label>
        <type>DateTime</type>
    </fields>
    <fields>
        <fullName>Deal_Stage__c</fullName>
        <label>Deal Stage</label>
        <picklist>
            <picklistValues>
                <fullName>Suspect</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Identified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Qualified</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Proposed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Agreed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>In Contract</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed-Won</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Closed-Lost</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Estimated_Close_Date__c</fullName>
        <label>Estimated Close Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <picklist>
            <picklistValues>
                <fullName>West Coast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Central</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Northeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Southeast</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>International</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Reseller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Mid-Atlantic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federal Gov.</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Territory_AppD__c.object
<CustomObject>
    <description>Used to manage lead/account routing.</description>
    <fields>
        <fullName>Assigned_To_ID__c</fullName>
        <label>Assigned To ID</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Assigned_To_Type__c</fullName>
        <label>Assigned To Type</label>
        <picklist>
            <picklistValues>
                <fullName>User</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Queue</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Assigned_To__c</fullName>
        <label>Assigned To</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Order__c</fullName>
        <description>This field determines the order in which Lead Territories are reviewed for Lead Assignment.</description>
        <label>Order</label>
        <precision>5</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Type__c</fullName>
        <label>Type</label>
        <picklist>
            <picklistValues>
                <fullName>Federal Employee</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Geography</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Lead Source</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Named Account</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Federal</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Tier 3</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Standard</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Territory_Field_Criteria__c.object
<CustomObject>
    <description>Criteria of Lead Territory based on Lead Fields.</description>
    <fields>
        <fullName>Field__c</fullName>
        <label>Field</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Operator__c</fullName>
        <label>Operator</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <referenceTo>Territory_AppD__c</referenceTo>
        <relationshipLabel>Territory Field Criterias</relationshipLabel>
        <relationshipName>Territory_Field_Criteria</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Value__c</fullName>
        <label>Value</label>
        <length>5000</length>
        <type>LongTextArea</type>
    </fields>
    <label>Territory Field Criteria</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Territory Field Criteria Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Field Criterias</pluralLabel>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Territory_Geography__c.object
<CustomObject>
    <fields>
        <fullName>Country__c</fullName>
        <label>Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>State</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Territory__c</fullName>
        <label>Territory</label>
        <referenceTo>Territory_AppD__c</referenceTo>
        <relationshipLabel>Territory Geographies</relationshipLabel>
        <relationshipName>Territory_Geographies</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Zip_End__c</fullName>
        <label>Zip End</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Zip_Start__c</fullName>
        <label>Zip Start</label>
        <length>10</length>
        <type>Text</type>
    </fields>
    <label>Territory Geography</label>
    <nameField>
        <displayFormat>{0}</displayFormat>
        <label>Territory Geography Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Territory Geographies</pluralLabel>
    <recordTypes>
        <fullName>Lead</fullName>
        <active>true</active>
        <label>Lead</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/testEditLeadTerritory.cls
@isTest
public class testEditLeadTerritory
{
    @isTest
    static void testEditLeadTerritory()
    {
        Id leadTerritoryRecordTypeId = [select Id from RecordType where SobjectType = 'Territory_AppD__c' and Name = 'Lead' limit 1].Id;
        Territory_AppD__c testLt = new Territory_AppD__c(Name = 'Acme', RecordTypeId = leadTerritoryRecordTypeId, Type__c = 'Geography', Assigned_To_Type__c = 'User', Assigned_To_ID__c = Userinfo.getUserId(), Assigned_To__c = userinfo.getUserName(), Order__c = 1);
        insert testLt;
        //AnnualRevenue
        Territory_Field_Criteria__c testLeadFIeldCriteria1 = new Territory_Field_Criteria__c(Field__c = 'AppJam_Presenter__c', Value__c = 'true', Operator__c = 'equals', Territory__c = testLt.Id);
        Territory_Field_Criteria__c testLeadFIeldCriteria2 = new Territory_Field_Criteria__c(Field__c = 'Deal_Stage__c', Value__c = 'Qualified', Operator__c = 'equals', Territory__c = testLt.Id);
        Territory_Field_Criteria__c testLeadFIeldCriteria3 = new Territory_Field_Criteria__c(Field__c = 'AnnualRevenue', Value__c = '100000', Operator__c = 'equals', Territory__c = testLt.Id);
        Territory_Field_Criteria__c testLeadFIeldCriteria4 = new Territory_Field_Criteria__c(Field__c = 'App_Map_First_Visit__c', Value__c = '9/8/2014', Operator__c = 'equals', Territory__c = testLt.Id);
        Territory_Field_Criteria__c testLeadFIeldCriteria5 = new Territory_Field_Criteria__c(Field__c = 'Estimated_Close_Date__c', Value__c = '9/8/2014', Operator__c = 'equals', Territory__c = testLt.Id);        
        insert new List<Territory_Field_Criteria__c> {testLeadFIeldCriteria1, testLeadFIeldCriteria2, testLeadFIeldCriteria3, testLeadFIeldCriteria4, testLeadFIeldCriteria5};        
        Territory_Geography__c testLeadGeo = new Territory_Geography__c(Territory__c = testLt.Id, Country__c = 'usa', State__c = 'ca', Zip_Start__c = '1000', Zip_End__c = '2000');
        insert testLeadGeo;
        PageReference testPage = new PageReference('/apex/EditLeadTerritory?id=' + testLt.Id);
        test.setCurrentPage(testPage);
        EditLeadTerritoryController controller = new EditLeadTerritoryController();
        controller.userinfo = userinfo.getUserName();
        controller.searchUser();
        Controller.addMoreLeadTerritoryGeos();
        Territory_Geography__c newLeadTerritoryGeo = controller.newLeadTerritoryGeos[0];
        newLeadTerritoryGeo.COuntry__c = 'CN';
        newLeadTerritoryGeo.State__c = 'BJ';
        newLeadTerritoryGeo.Zip_Start__c = '1000';
        newLeadTerritoryGeo.Zip_End__c = '2000';
        controller.insertNewLeadTerritoryGeos();
        COntroller.AssignmentsCSV = 'USA,CA,1000,2000\nUSA,CA,2000,4000';
        COntroller.insertNewLeadTerritoryGeosByCSV();
        system.assert(controller.getLeadFields() != null);
        controller.saveLeadTerritory();           
        Controller.jsonCriteria = '{"Territory__c":"' +  testLt.Id
                          + '","Country__c":"USA'
                          + '","State__c":"CS'
                          + '","Zip_Start__c":"10000'
                          + '","Zip_End__c":"20000'
                          + '"}';
      Controller.createGeographicCriteria();
      Controller.jsonCriteria = '{"Territory__c":"' +  testLt.Id
                          + '","Field__c":"Name'
                          + '","Operator__c":"equals' 
                          + '","Value__c":"Acme'
                          + '"}';
      Controller.createLeadFieldCriteria();
      Controller.removedType = 'leadField';
      Controller.removedId = testLeadFIeldCriteria1.Id;
      Controller.remove();
      Controller.removedType = 'geography';
      Controller.removedId = testLeadGeo.Id;
      Controller.remove();
    }
}