src/objects/LicenseDetail__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Is_Permanent__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Is Permanent ?</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Deployment Option</label>
        <picklist>
            <picklistValues>
                <fullName>On-Premise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosted (SaaS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosted (SaaS Lite)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>License</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SimpleLicenseController.cls
public with sharing class SimpleLicenseController {

	private final LicenseDetail__c license;
	
	public SimpleLicenseController(ApexPages.StandardController licenseController){
		if(licenseController.getRecord() != null){
			this.license = (LicenseDetail__c)licenseController.getRecord();
		}else{
			this.license = new LicenseDetail__c();
		}
	}
	
	public Boolean getSection(String section){
		return section.equalsIgnoreCase(this.license.Product_Type__c);
		//return false; 
	}
	
	public boolean getOnPremiseVisible(){
		return 'On-Premise'.equalsIgnoreCase(this.license.Product_Type__c);
	}
	
	public boolean getPermanentPanelVisible(){
		return this.license.Is_Permanent__c;
	}
	
	
	public static testMethod void testSimpleLicController(){
		SimpleLicenseController lic = new SimpleLicenseController(new ApexPages.Standardcontroller(new LicenseDetail__c()));
		lic.getSection('');
		lic.getOnPremiseVisible();
		lic.getPermanentPanelVisible();
		System.assert(true);
	}
}