src/objects/License_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>License__c</fullName>
        <label>License</label>
        <referenceTo>LicenseDetail__c</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LicenseDetail__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>License_Expiry_Date__c</fullName>
        <label>License Expiration Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Deployment Option</label>
        <picklist>
            <picklistValues>
                <fullName>On-Premise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosted (SaaS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosted (SaaS Lite)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Server_Agents__c</fullName>
        <label>Java Agents Old</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>License</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/DelLicenseOpportunityController.cls
public with sharing class DelLicenseOpportunityController {
	private ApexPages.StandardController stdController;
	public License_Opportunity__c licOpp{get;set;}
	public DelLicenseOpportunityController(ApexPages.StandardController stdController){
		this.stdController = stdController;
		licOpp = (License_Opportunity__c)stdController.getRecord();
		licOpp = (License_Opportunity__c)DataLayerConstants.fetchSingle('License_Opportunity__c', licOpp.Id);
	}
	public PageReference deleteAction(){
		if(licOpp!=null){
			List<License_Opportunity__c> licenseOpps = DataLayerConstants.fetchMultiple('License_Opportunity__c', 'License__c',licOpp.License__c);
			if(licenseOpps!=null){
				if(licenseOpps.size()>1){
					delete licOpp;
					PageReference ref = new PageReference('/'+licOpp.License__c);
					ref.setRedirect(false);
					return ref;
				}else{
					ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL,'Cannot Remove Opportunity License Association as the license doesnot have any other Opportunity association');
	            	ApexPages.addMessage(myMsg);
	            	ApexPages.Message myMsg2 = new ApexPages.Message(ApexPages.Severity.INFO,'Please associate another opportunity for the license and then try deleting the association');
	            	ApexPages.addMessage(myMsg2);
	            	return null;
				}
			}
		}
		return stdController.cancel();
	}
	
	public static testMethod void deleteInit(){
		LicenseDetail__c lic = new LicenseDetail__c();
		lic.Product_Type__c = AppDConstants.LICENSE_PRODUCT_TYPE_ON_PREMISE;
		lic.License_Expiry_Date__c = System.now().date().addDays(5);
		lic.Server_Agents__c = 2;
		upsert lic;
		
		List<Opportunity> opps = DataLayerConstants.fetchMultiple('Opportunity', ' LIMIT 2');
		Opportunity opp1 = opps.get(0);
		Opportunity opp2 = opps.get(1);
		License_Opportunity__c licOpp = new License_Opportunity__c();
		licOpp.License__c = lic.Id;
		licOpp.Opportunity__c = opp1.Id;
		upsert licOpp;
		
		DelLicenseOpportunityController ctrlr = new DelLicenseOpportunityController(new ApexPages.StandardController(licOpp));
		ctrlr.deleteAction();
		
		License_Opportunity__c licOpp1 = new License_Opportunity__c();
		licOpp1.License__c = lic.Id;
		licOpp1.Opportunity__c = opp2.Id;
		upsert licOpp1;
		
		ctrlr.deleteAction();
	}
}