src/objects/License_Agent__c.object
<CustomObject>
    <description>License Agent which will have:
Agent Type as Java/.Net/PHP
and Agent count</description>
    <fields>
        <fullName>Agent_Type__c</fullName>
        <label>Agent Type</label>
        <picklist>
            <picklistValues>
                <fullName>Java</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>.NET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PHP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NodeJs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Database</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Python</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transaction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Log</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Machine</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Edition__c</fullName>
        <description>Product Edition</description>
        <inlineHelpText>Product Edition</inlineHelpText>
        <label>Edition</label>
        <picklist>
            <picklistValues>
                <fullName>PRO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pro Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LITE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <label>License</label>
        <referenceTo>LicenseDetail__c</referenceTo>
        <relationshipLabel>License Agents</relationshipLabel>
        <relationshipName>License_Agents</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Licensing_Model__c</fullName>
        <label>Licensing Model</label>
        <picklist>
            <picklistValues>
                <fullName>FIXED</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Overages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VARIABLE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Max_Agents__c</fullName>
        <label>Max Agents</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>License Agent</label>
    <nameField>
        <label>License Units Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Agents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/License_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>License__c</fullName>
        <label>License</label>
        <referenceTo>LicenseDetail__c</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LicenseDetail__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>Custom_URL_Name__c</fullName>
        <label>Customer SaaS URL</label>
        <length>63</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_Expiry_Date__c</fullName>
        <label>License Expiration Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Deployment Option</label>
        <picklist>
            <picklistValues>
                <fullName>On-Premise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosted (SaaS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosted (SaaS Lite)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>TRIAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRIAL EXPIRED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAID EXPIRED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DISABLED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>License</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Count__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LicenseProvision_PaidController.cls
public with sharing class LicenseProvision_PaidController extends LicenseProvisionController{
	
	public LicenseProvision_PaidController(ApexPages.StandardController stdCtrlr){
		super(stdCtrlr,BackendConstants.OPCODE_ADD_LICENSE);
	}
	
	public override virtual PageReference initAction(){
		loggerHandle.setClassName(LicenseProvision_PaidController.class.getName());
		licenseDetailObj.Stage__c = 'PAID_PERMANENT';
		licenseOpcode = BackendConstants.OPCODE_ADD_LICENSE;  
	    showPermanentLicense = true;
	    showMacAddress=true;  
	    licenseDetailObj = new LicenseDetail__c();
	    pageContextObj = licenseDetailObj;
	    Date todaysDate = System.now().date();
	    Date provisionDefaultDate = todaysDate.addDays(AppDConstants.getProvisionDefaultDate());
	    licenseDetailObj.License_Expiry_Date__c =  provisionDefaultDate;
	    productTypeSelectOptions = CommonUtil.getProductTypeSelectOptions(licenseOpcode,stage);
	    deltaValues = false;
	    
	    super.initAction();
	    
	 	pageTitle = 'Provision Paid License for Opportunity:'+myOpportunity.Name;
	 	this.saveButtonTitle = 'Provision';
	 	isPermanent = true;
	 	licenseDetailObj.Stage__c = 'PAID_PERMANENT';
	 	if(licAgentInfoList!=null){
			for(PortalDataType.LicenseAgentInfo licAgentInfo:licAgentInfoList){
				License_Agent__c licAgent = licAgentInfo.licAgent;
				licAgent.Count__c=0;
				if(licAgent.Licensing_Model__c==null){
					licAgent.Licensing_Model__c = 'FIXED';
				}
				licAgent.Max_Agents__c=licAgent.Count__c;
				licAgent.Edition__c = PortalDataType.EDITION_PRO;
				licAgentinfo.selectedProductEdition = PortalDataType.EDITION_PRO;
				if(licAgent.Agent_Type__c == 'Synthetic'){
					licAgent.Edition__c = PortalDataType.EDITION_NONE;
				}
			}
		}
		return null;
	}
	
	public static testMethod void testCase(){
		RESTAPI.unitTestMode=true;
		Opportunity opp = (Opportunity)DataLayerConstants.fetch('Opportunity').get(0);
		ApexPages.currentPage().getParameters().put('Opportunity_Id',opp.Id);
		
		LicenseDetail__c lic= new LicenseDetail__c();
    	lic.Product_Type__c=AppDConstants.LICENSE_PRODUCT_TYPE_ON_PREMISE;
    	//licenseObj.Custom_URL_Name__c='SRINIDHI_TEST_2513';
    	lic.License_Expiry_Date__c=System.now().date().addDays(10);
    	lic.Stage__c='PAID_TEMP';
    	upsert lic;
    	License_Opportunity__c licOpp = new License_Opportunity__c();
    	licOpp.License__c=lic.ID;
    	licOpp.Opportunity__c=opp.Id;
    	upsert licOpp;
    	List<License_Agent__c> licAgents = LicenseUtil.getLicenseAgents(lic,LicenseUtil.getSupportedProductsMetadata(),false, 1);
    	for(License_Agent__c licAgent:licAgents){
    		licAgent.Count__c=10;
    		licAgent.License__c=lic.Id;
    	}
    	upsert licAgents;
		LicenseProvision_PaidController ctrlr = new LicenseProvision_PaidController(new ApexPages.StandardController(lic));
		ctrlr.initAction();
		try{
		ctrlr.setupBackend();
		ctrlr.doPreSave();
		ctrlr.doPostSave();
		ctrlr.doPreSave();
		ctrlr.doCancel();
		}catch(Exception e){}
		
	} 
}