src/objects/License_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>License__c</fullName>
        <label>License</label>
        <referenceTo>LicenseDetail__c</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LicenseDetail__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>License_Expiry_Date__c</fullName>
        <label>License Expiration Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>MAC_Address__c</fullName>
        <description>MAC Address of the machine to be registered with license</description>
        <label>MAC Address</label>
        <length>17</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Machine_Agents__c</fullName>
        <label>Additional Machine Agents Old</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Net_Agents__c</fullName>
        <label>.Net Agents Old</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Server_Agents__c</fullName>
        <label>Java Agents Old</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>License</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/OppLicRelatedListController.cls
public with sharing class OppLicRelatedListController {/*
	public String oppId{get;set;}
	public List<LicenseDetail__c> licenses{get{return licenses = Database.query('select Id,Name,License_Expiry_Date__c,Server_Agents__c,Net_Agents__c,Machine_Agents__c,MAC_Address__c from LicenseDetail__c where ID in (select License__c from License_Opportunity__c where Opportunity__c=\''+oppId+'\')');}set;}
	public List<HistoryWrapper> licenseHistories{get{return getHistroyWrappers();}}
	
	public OppLicRelatedListController(){
		//init();
	}
	
	private List<HistoryWrapper> getHistroyWrappers(){
		List<HistoryWrapper> historyWrappers = new List<HistoryWrapper>();
		LicenseDetail__c[] licIds = [select ID from LicenseDetail__c where ID IN (Select License__c from License_Opportunity__c where Opportunity__c =: oppId)];
		if(licenses!=null && licenses.size()>0){
			List<LicenseDetail__History>histories = [select Id,CreatedDate,CreatedById,Field,OldValue,NewValue from LicenseDetail__History where parentId IN:licIds ORDER BY CreatedDate DESC LIMIT 100];
			for(LicenseDetail__History licHistory:histories){
				HistoryWrapper history = new HistoryWrapper();
				history.actualHistory = licHistory;
				historyWrappers.add(history);
			}
		}
		return historyWrappers;
	}
	
	static testMethod void getHistoryWrappersTest() {
		OppLicRelatedListController licController = new OppLicRelatedListController();
		List<License_Opportunity__c> licOpps = CommonUtil.createLicense();
		if( licOpps != null & licOpps.size() > 0 ) {
			License_Opportunity__c licOpp = (License_Opportunity__c) licOpps.get(0);
			licController.oppId = licOpp.Opportunity__c;
			//LicenseDetail__History history = new LicenseDetail__History();
			//history.
			List<HistoryWrapper>  wrapper = licController.licenseHistories;
		}
	}
	
	public class HistoryWrapper{
		public LicenseDetail__History actualHistory{get;set;}
	
		public String getActionString(){
			string sActionFormat = '';
 
            if (actualHistory!= null) {
                sActionFormat = 'Record {0}.';
 				
                if (actualHistory.newValue != null && actualHistory.oldValue == null) {
                    sActionFormat = 'Changed <strong>{1}</strong> to <strong>{3}</strong>.';
                }
                else if (actualHistory.newValue != null && actualHistory.oldValue != null) {
                    sActionFormat = 'Changed <strong>{1}</strong> from {2} to <strong>{3}</strong>.';
                }
                else if (actualHistory.Field != null && actualHistory.Field.equalsIgnoreCase('created')) {
                    sActionFormat = 'Created.';
                }
            }
 
            return sActionFormat;
		}	
	}
	
	
	public static testMethod void testOppLicRelatedList(){
		OppLicRelatedListController ctrlr = new OppLicRelatedListController();
		Opportunity oppObj = [Select ID from Opportunity LIMIT 1];
		String opportunityId = oppObj.Id;
		ctrlr.oppId = opportunityId;
		//System.assertNotEquals(ctrlr.licenseHistories,null);
	}*/
}