src/objects/License_Agent__c.object
<CustomObject>
    <description>License Agent which will have:
Agent Type as Java/.Net/PHP
and Agent count</description>
    <fields>
        <fullName>Agent_Type__c</fullName>
        <label>Agent Type</label>
        <picklist>
            <picklistValues>
                <fullName>Java</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>.NET</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PHP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>NodeJs</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Database</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Python</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Transaction</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Log</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Machine</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Count__c</fullName>
        <label>Count</label>
        <precision>8</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Edition__c</fullName>
        <description>Product Edition</description>
        <inlineHelpText>Product Edition</inlineHelpText>
        <label>Edition</label>
        <picklist>
            <picklistValues>
                <fullName>PRO</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Pro Trial</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>LITE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Licensing_Model__c</fullName>
        <label>Licensing Model</label>
        <picklist>
            <picklistValues>
                <fullName>FIXED</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Overages</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VARIABLE</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Max_Agents__c</fullName>
        <label>Max Agents</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <label>License Agent</label>
    <nameField>
        <label>License Units Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License Agents</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LicenseDetail__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>License_Expiry_Date__c</fullName>
        <label>License Expiration Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>License</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Count__c</fullName>
        <formula>1</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Count</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/LicenseProvision_FreeTrialController.cls
public with sharing class LicenseProvision_FreeTrialController extends LicenseProvisionController{
	public LicenseProvision_FreeTrialController(ApexPages.StandardController stdCtrlr){
		super(stdCtrlr,BackendConstants.OPCODE_PROVISION_FREE_TRIAL);
	}
	
	public override virtual PageReference initAction(){
		try{
			loggerHandle.setClassName(LicenseProvision_FreeTrialController.class.getName());
			licenseOpcode = BackendConstants.OPCODE_PROVISION_FREE_TRIAL;  
			
			showMacAddress=false;
	        licenseDetailObj = new LicenseDetail__c();
	        pageContextObj = licenseDetailObj;
	        Date todaysDate = System.now().date();
	        Date provisionDefaultDate = todaysDate.addDays(AppDConstants.getProvisionDefaultDate());
	        licenseDetailObj.License_Expiry_Date__c =  provisionDefaultDate;
	        
	        productTypeSelectOptions = CommonUtil.getProductTypeSelectOptions(licenseOpcode,stage);
	        deltaValues = false;
	        
	        super.initAction();
	        
	        if(myOpportunity!=null){
	        	pageTitle = 'Provision Free Trial License for Opportunity:'+myOpportunity.Name;
	        }
	        this.saveButtonTitle = 'Provision';
	        isPermanent = false;
	        
			if(licAgentInfoList!=null){
				for(PortalDataType.LicenseAgentInfo licAgentInfo:licAgentInfoList){
					License_Agent__c licAgent = licAgentInfo.licAgent;
					if('Java'.equals(licAgent.Agent_Type__c)){
						licAgent.Count__c=10;
					}else{
						licAgent.Count__c=0;
					}
					licAgent.Max_Agents__c = licAgent.Count__c;
					if(licAgent.Licensing_Model__c==null){
						licAgent.Licensing_Model__c = 'FIXED';
					}
					if('Synthetic'.equals(licAgent.Agent_Type__c)){
						licAgent.Edition__c = PortalDataType.EDITION_NONE;
					}					
				}
			}
		}catch(Exception e){
			EmailUtil.notifyError(e, licenseDetailObj);
			loggerHandle.error(e.getMessage(),e);
			super.cancelOperation(e.getMessage(),e);
			//throw 
		}
		return null;
	}
}