src/objects/License_EUM_Details__c.object
<CustomObject>
    <fields>
        <fullName>Access_Key__c</fullName>
        <label>EUM Access Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountName__c</fullName>
        <label>EUM Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>License to which this EUM details are associated with.</inlineHelpText>
        <label>License</label>
        <referenceTo>LicenseDetail__c</referenceTo>
        <relationshipLabel>License EUM Details</relationshipLabel>
        <relationshipName>License_EUM_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>EUM State</label>
        <picklist>
            <picklistValues>
                <fullName>ENABLED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DISABLED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DELETED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>License EUM Detail</label>
    <nameField>
        <label>License EUM Detail(s) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License EUM Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/License_History_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>License_Operation__c</fullName>
        <label>License Operation</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License</label>
        <referenceTo>LicenseDetail__c</referenceTo>
        <relationshipLabel>License History Tracking</relationshipLabel>
        <relationshipName>License_History_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>License_History_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>License History Tracking</label>
    <nameField>
        <label>License History Tracking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License History Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LicenseDetail__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>License_BackendID__c</fullName>
        <label>License_BackendID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>ProcessState__c</fullName>
        <label>Last Transaction Result</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAILED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>TRIAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRIAL EXPIRED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAID EXPIRED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DISABLED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>License</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Status__c.object
<CustomObject>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads Owners Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PortalREST_UpdateLicenseDetails.cls
@RestResource(urlMapping='/portal/update_license_details/*')
global class PortalREST_UpdateLicenseDetails {
    /*
     * UpdateLicenses method is exposed through update_license_details rest api.
     * In this method we update IN_PROGRESS licenses 
     */
    @HttpPost
    global static void updateLicenses(List<PortalDataType.License> licenses) { 
        RestResponse response = RestContext.response;
        try{
            if(licenses!=null && licenses.size()>0){
                
                List<String> licenseIds = new List<String>();
                Map<String,PortalDataType.License> licnesesMAP = new Map<String,PortalDataType.License>();
                
                for(PortalDataType.License license: licenses){
                    licnesesMAP.put(license.salesforceLicenseID, license);
                }
                
                List<LicenseDetail__c> licenseDetails = [select Id, ProcessState__c, Stage__c, (select id, Access_Key__c, AccountName__c, State__c from License_EUM_Details__r), (select id, License__c, License_Operation__c, User__c, Status__c from License_History_Tracking__r where Status__c='IN_PROGRESS' ORDER BY CreatedDate DESC limit 1) from LicenseDetail__c where id IN: licnesesMAP.keySet()];
                List<License_EUM_Details__c> licenseEumDetails = new List<License_EUM_Details__c>();
                List<License_History_Tracking__c> licenseHistoryTracking = new List<License_History_Tracking__c>();
                
                /*
                 * Here, we are looping through license records and updating the details.
                 */ 
                for(LicenseDetail__c licenseDetail: licenseDetails){
                    PortalDataType.License license = licnesesMAP.get(licenseDetail.id);
                    licenseDetail.ProcessState__c = license.processState;
                    licenseDetail.Stage__c = license.stage;
                    licenseDetail.License_BackendID__c = license.id;        
                    
                    /*
                     * Updating License EUM details.
                     */
                    if(licenseDetail.License_EUM_Details__r!=null && licenseDetail.License_EUM_Details__r.size()>0 && license.license_eum_details!=null){
                        License_EUM_Details__c led = licenseDetail.License_EUM_Details__r.get(0);
                        led.Access_Key__c = license.license_eum_details.accessKey;
                        led.State__c = license.license_eum_details.state;
                        licenseEumDetails.add(led);  
                    }
                    
                    /*
                     * Updating License History tracking status.
                     */
                    if(licenseDetail.License_History_Tracking__r!=null && licenseDetail.License_History_Tracking__r.size()>0){
                        License_History_Tracking__c lht = licenseDetail.License_History_Tracking__r.get(0);
                        lht.Status__c = license.processState;
                        licenseHistoryTracking.add(lht);
                    }
                    
                }
                
                update licenseDetails;
                
                if(licenseEumDetails.size()>0){
                    update licenseEumDetails;
                }
                if(licenseHistoryTracking.size()>0){
                    update licenseHistoryTracking;
                }
                
                response.statusCode = 200;
                response.responseBody = Blob.valueOf('{"status":"SUCCESS"}');
                 
            }
        }catch(Exception e){
            response.statusCode = 500;
            response.responseBody = Blob.valueOf('{"status":"failure","reason":"'+e.getMessage()+'"}'); 
        }
    }
    
}