src/objects/License_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>License__c</fullName>
        <label>License</label>
        <referenceTo>LicenseDetail__c</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/LicenseOpportunityViewController.cls
public with sharing class LicenseOpportunityViewController {
    License_Opportunity__c licenseOpportunity;
    private String licenseId;
    public LicenseOpportunityViewController(ApexPages.StandardController stdController)
    {
        licenseOpportunity = (License_Opportunity__c) stdController.getRecord();
        
        try
        {
            licenseOpportunity =[select Opportunity__c, License__c from License_Opportunity__c where Id=:licenseOpportunity.Id];
            licenseId = licenseOpportunity.License__c;
        }
        catch(Exception e)
        {
            ApexPages.Message myMsg = new ApexPages.Message(ApexPages.Severity.FATAL,'Error while retrieving associated license for opportunity:'+e.getMessage());
            ApexPages.addMessage(myMsg);
        }
    }
    
    public PageReference redirectToLicense()
    {
        if(licenseId!=null)
        {
            PageReference ref = new PageReference('/'+licenseId);
            ref.setRedirect(true);
            return ref;
        }
        return null;
    }
}