src/objects/License_Opportunity__c.object
<CustomObject>
    <fields>
        <fullName>License__c</fullName>
        <label>License</label>
        <referenceTo>LicenseDetail__c</referenceTo>
        <relationshipName>Opportunities</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <fields>
        <fullName>Opportunity__c</fullName>
        <label>Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Licenses</relationshipLabel>
        <relationshipName>Licenses</relationshipName>
        <relationshipOrder>1</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>Opportunity</label>
    <nameField>
        <displayFormat>L-{0000}</displayFormat>
        <label>License Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Opportunities</pluralLabel>
    <recordTypes>
        <fullName>Opportunity</fullName>
        <active>true</active>
        <label>Opportunity</label>
    </recordTypes>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/LicenseDetail__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>License_BackendID__c</fullName>
        <label>License_BackendID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_Expiry_Date__c</fullName>
        <label>License Expiration Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>Net_Agents__c</fullName>
        <label>.Net Agents Old</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Deployment Option</label>
        <picklist>
            <picklistValues>
                <fullName>On-Premise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosted (SaaS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosted (SaaS Lite)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>SAAS_UserName__c</fullName>
        <label>SaaS User Name</label>
        <length>63</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>SaaS_Password__c</fullName>
        <label>SaaS Password</label>
        <length>63</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Server_Agents__c</fullName>
        <label>Java Agents Old</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>TRIAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRIAL EXPIRED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAID EXPIRED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DISABLED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>License</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/SaaSLoginController.cls
public with sharing class SaaSLoginController {

	static void createLicense() {
		Opportunity opp = [Select Id from Opportunity LIMIT 1];
        List<LicenseDetail__c>  licenses = new  List<LicenseDetail__c>();
        for( integer i =0; i<1; i++) {
        	LicenseDetail__c lic = new LicenseDetail__c();
        	lic.Product_Type__c = 'On-Premise';
        	lic.License_BackendID__c = '100';
        	lic.License_Expiry_Date__c = System.now().date().addDays(15);
        	lic.Product_Type__c = AppDConstants.LICENSE_PRODUCT_TYPE_ON_PREMISE;
        	lic.Server_Agents__c  = 10;
        	lic.Net_Agents__c  = 10;
        	lic.Stage__c = 'TRIAL';
        	licenses.add(lic);
        		
        }
        
        insert licenses;
        List<License_Opportunity__c> licOpps = new List<License_Opportunity__c>();
        for (integer i =0; i<licenses.size(); i++ ) {
        	LicenseDetail__c lic = licenses.get(i);
        	License_Opportunity__c licOpp = new License_Opportunity__c();
        	licOpp.Opportunity__c = opp.id;
        	licOpp.license__c = lic.id;
        	licOpps.add(licOpp);
        }
       	insert licOpps;
		
	}

	public PageReference saasLogin(){
		Id id = System.currentPageReference().getParameters().get('license_id');
		LicenseDetail__c license = (LicenseDetail__c)[Select SAAS_UserName__c ,SaaS_Password__c from LicenseDetail__c where Id = :id][0];
		String username = license.SAAS_UserName__c;
		String password = license.SaaS_Password__c;
		PageReference pageRef = new PageReference('http://www.google.com?id='+username+'&password='+password);
		return pageRef;
	} 
	
	
	public static testMethod void testSaasLogin(){
		createLicense();
		String licenseId='';
		LicenseDetail__c lic = [Select ID from LicenseDetail__c limit 1];
		licenseId = lic.Id;
		SaaSLoginController controller = new SaaSLoginController();
		ApexPages.currentPage().getParameters().put('license_id',licenseId);
		PageReference ref = controller.saasLogin();
		System.assertNotEquals(ref, null);	
	}
}