src/objects/License_EUM_Details__c.object
<CustomObject>
    <fields>
        <fullName>Access_Key__c</fullName>
        <label>EUM Access Key</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>AccountName__c</fullName>
        <label>EUM Account Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <inlineHelpText>License to which this EUM details are associated with.</inlineHelpText>
        <label>License</label>
        <referenceTo>LicenseDetail__c</referenceTo>
        <relationshipLabel>License EUM Details</relationshipLabel>
        <relationshipName>License_EUM_Details</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>State__c</fullName>
        <label>EUM State</label>
        <picklist>
            <picklistValues>
                <fullName>ENABLED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DISABLED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DELETED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>License EUM Detail</label>
    <nameField>
        <label>License EUM Detail(s) Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License EUM Details</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/License_History_Tracking__c.object
<CustomObject>
    <fields>
        <fullName>License_Operation__c</fullName>
        <label>License Operation</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>License</label>
        <referenceTo>LicenseDetail__c</referenceTo>
        <relationshipLabel>License History Tracking</relationshipLabel>
        <relationshipName>License_History_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Status__c</fullName>
        <label>Status</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>User__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>User</label>
        <referenceTo>User</referenceTo>
        <relationshipName>License_History_Tracking</relationshipName>
        <type>Lookup</type>
    </fields>
    <label>License History Tracking</label>
    <nameField>
        <label>License History Tracking Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>License History Tracking</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/LicenseDetail__c.object
<CustomObject>
    <description>This is a generic template for Custom Object.  With this template, you may adjust the default elements and values and add new elements and values.</description>
    <fields>
        <fullName>License_BackendID__c</fullName>
        <label>License_BackendID</label>
        <length>80</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>License_Expiry_Date__c</fullName>
        <label>License Expiration Date</label>
        <required>true</required>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>ProcessState__c</fullName>
        <label>Last Transaction Result</label>
        <picklist>
            <picklistValues>
                <fullName>In Progress</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Completed</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>FAILED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Product_Type__c</fullName>
        <label>Deployment Option</label>
        <picklist>
            <picklistValues>
                <fullName>On-Premise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosted (SaaS)</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Hosted (SaaS Lite)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Stage__c</fullName>
        <label>Stage</label>
        <picklist>
            <picklistValues>
                <fullName>TRIAL</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAID</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>TRIAL EXPIRED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>PAID EXPIRED</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>DISABLED</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <label>License</label>
    <nameField>
        <label>License</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Licenses</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/objects/Status__c.object
<CustomObject>
    <label>Status</label>
    <nameField>
        <label>Status Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Leads Owners Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/TestPortalREST_UpdateLicenseDetails.cls
/**
 * This class contains unit tests for validating the behavior of Apex classes
 * and triggers.
 *
 * Unit tests are class methods that verify whether a particular piece
 * of code is working properly. Unit test methods take no arguments,
 * commit no data to the database, and are flagged with the testMethod
 * keyword in the method definition.
 *
 * All test methods in an organization are executed whenever Apex code is deployed
 * to a production organization to confirm correctness, ensure code
 * coverage, and prevent regressions. All Apex classes are
 * required to have at least 75% code coverage in order to be deployed
 * to a production organization. In addition, all triggers must have some code coverage.
 * 
 * The @isTest class annotation indicates this class only contains test
 * methods. Classes defined with the @isTest annotation do not count against
 * the organization size limit for all Apex scripts.
 *
 * See the Apex Language Reference for more information about Testing and Code Coverage.
 */
@isTest
private class TestPortalREST_UpdateLicenseDetails {
    
    public static testMethod void testUpdateLicensesSuccess() {
        
        RestRequest req = new RestRequest(); 
        RestResponse res = new RestResponse();
        req.requestURI = 'https://cs1.salesforce.com/services/apexrest/portal/update_license_details/*';
        req.httpMethod = 'POST';
        RestContext.request = req;
        RestContext.response = res;
        
        LicenseDetail__c lic = new LicenseDetail__c();
        lic.Product_Type__c = 'On-Premise';
        lic.License_BackendID__c = '100';
        lic.Stage__c = 'TRIAL';
        lic.ProcessState__c = 'IN_PROGRESS';
        lic.License_Expiry_Date__c =  Date.newInstance(2014, 7, 7); 
        insert lic;
     
        License_EUM_Details__c eum =  new License_EUM_Details__c();
        eum.License__c = lic.id;
        eum.Access_Key__c = '4983338f-4dab-4343-895c-b67a59b31285';
        eum.State__c = 'In Progress';
        eum.AccountName__c = 'TestEUM';
        insert eum;
        
        License_History_Tracking__c lht = new License_History_Tracking__c();
        lht.License__c = lic.id;
        lht.License_Operation__c = 'TRIAL';
        lht.Status__c = 'IN_PROGRESS';
        lht.User__c = UserInfo.getUserId();
        insert lht;
        
        PortalDataType.LicenseEUMDetails licenseEum = new PortalDataType.LicenseEUMDetails();
        licenseEum.accessKey = '4983338f-4dab-4343-895c-b67a59b31285';
        licenseEum.salesforceEUMID = eum.Id;
        licenseEum.state = 'SUCCESS';
        
        
        List<PortalDataType.License> licenses = new List<PortalDataType.License>();
        PortalDataType.License license = new PortalDataType.License();
        PortalREST_UpdateLicenseDetails.updateLicenses(licenses);
        
        license.created_date = '7/7/2014';
        license.stage = 'TRIAL';
        license.expiryDate = '7/10/2014';
        
        license.salesforceLicenseID = lic.id;
        license.id = lic.License_BackendID__c;
        license.license_eum_details = licenseEum;
        license.ProductType = 'On-Premise';
        license.processState = 'SUCCESS';
        licenses.add(license);
        PortalREST_UpdateLicenseDetails.updateLicenses(licenses);
        
        license.created_date = '7/7/2014';
        license.stage = 'TRIAL';
        license.expiryDate = '7/10/2014';
        
        license.salesforceLicenseID = 'abcdef';
        license.id = lic.License_BackendID__c;
        license.license_eum_details = licenseEum;
        license.ProductType = 'On-Premise';
        license.processState = 'SUCCESS';
        licenses.add(license);
        PortalREST_UpdateLicenseDetails.updateLicenses(licenses);
   }
}