src/objects/OppAutoRenewSetting__c.object
<CustomObject>
    <customSettingsType>List</customSettingsType>
    <customSettingsVisibility>Public</customSettingsVisibility>
    <description>Settings to use for Opportunity Auto Renewal</description>
    <fields>
        <fullName>Id__c</fullName>
        <description>Salesforce Id of the associated resource</description>
        <label>Id</label>
        <length>18</length>
        <type>Text</type>
    </fields>
    <label>Auto Renewal Settings</label>
</CustomObject>

src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Deal_Type__c</fullName>
        <label>Deal Type</label>
        <picklist>
            <controllingField>Type</controllingField>
            <picklistValues>
                <fullName>New</fullName>
                <default>true</default>
            </picklistValues>
            <picklistValues>
                <fullName>Training</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Subscription</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Renewal - Perpetual</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Expansion</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Growth - (Co-Term)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Deployment_Option__c</fullName>
        <inlineHelpText>Please select the deployment option for this customer.</inlineHelpText>
        <label>Deployment Option</label>
        <picklist>
            <picklistValues>
                <fullName>On-Premise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saas-Shared Controller</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Saas-Dedicated Controller (additional cost)</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>End_Date__c</fullName>
        <label>End Date</label>
        <type>Date</type>
    </fields>
    <fields>
        <fullName>License_Term_in_Months__c</fullName>
        <description>Please enter the license term in whole months.</description>
        <inlineHelpText>Please enter the license term in whole months.</inlineHelpText>
        <label>License Term in Months</label>
        <precision>3</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Opportunity_Type__c</fullName>
        <description>To identify whether it is a Direct Deal or 3rd Party involved order.</description>
        <label>Opportunity Type</label>
        <picklist>
            <picklistValues>
                <fullName>Direct</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VAR – Resale</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Fulfillment</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>VAR – Referral</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>MSP</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Financed</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Partner_Involved__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>The Partner involved in this deal/opportunity</description>
        <label>Partner On Opportunity</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Previous_Opportunity__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>Opportunity that was previously renewed into this one.</description>
        <label>Previous Opportunity</label>
        <referenceTo>Opportunity</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Renewed_Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Project_Country__c</fullName>
        <label>Project Country</label>
        <picklist>
            <picklistValues>
                <fullName>United States of America</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>UK</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Afghanistan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Albania</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Algeria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>American Samoa</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Andorra</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Angola</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Anguilla</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Antigua and Barbuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Argentina</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Armenia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aruba</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Australia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Austria</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Azerbaijan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahamas, The</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bahrain</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bangladesh</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Barbados</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belarus</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belgium</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Belize</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Benin</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bermuda</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bhutan</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bolivia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bosnia</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Botswana</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Bougainville</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Project_Region__c</fullName>
        <label>EULA Region</label>
        <picklist>
            <controllingField>Project_Country__c</controllingField>
            <picklistValues>
                <fullName>Americas</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>EMEA</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>APAC</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <fields>
        <fullName>Renewal__c</fullName>
        <label>Renewal</label>
        <precision>4</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Secondary_Partner__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <description>If there is a secondary partner, enter here</description>
        <inlineHelpText>If there is a secondary partner, enter here</inlineHelpText>
        <label>Secondary Partner</label>
        <referenceTo>Account</referenceTo>
        <relationshipLabel>Opportunities (Secondary Partner)</relationshipLabel>
        <relationshipName>Opportunities1</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/OpportunityAutoRenew.cls
public class OpportunityAutoRenew {

   @future
   public static void CloneOpps(List<String> OppIdsToClone) {
      OppAutoRenewSetting__c RenewalDealRecordType = OppAutoRenewSetting__c.getInstance('Renewal Deal Record Type');
      
      List<Opportunity> ClonedOpps = new List<Opportunity>();
      Map<String,String> ClonedOppMap = new Map<String,String>();
      Map<String,String> OppTypes     = new Map<String,String>();

      for (Opportunity o : [SELECT Id,Name,AccountId,StageName,CloseDate,LeadSource,OwnerId,Type,RecordTypeId,Deal_Type__c,Renewal__c,
                            CurrencyIsoCode,PriceBook2Id,Previous_Opportunity__c,License_Term_in_Months__c,Project_Country__c,Project_Region__c,
                            Opportunity_Type__c,Primary_Contact__c,Deployment_Option__c,Partner_Involved__c,Secondary_Partner__c,ForecastCategoryName FROM Opportunity WHERE Id =: OppIdsToClone]) {
         Opportunity newOpp = o.clone(false, false, false, false);
         if (newOpp.Renewal__c == NULL) { 
            if (newOpp.Name.length() <= 110) { newOpp.Name += ' (Renewal)'; }
            newOpp.Renewal__c = 1;
         }   // end if it's a first renewal
         else if (newOpp.Renewal__c != NULL && newOpp.Renewal__c > 0) {
            // Attempt to change the name later using a regular expression, i.e. "Renewal" -> "Renewal #2"
            String[] NameParts = newOpp.Name.Split('\\ \\(Renew', 2);
            newOpp.Renewal__c++;
            String newName = NameParts[0] + ' (Renewal #' + String.valueOf(newOpp.Renewal__c) + ')';
            if (newName.length() < 120) { newOpp.Name = newName; }
         }
         newOpp.StageName = 'B2 - First Meeting/Qualification';
         newOpp.RecordTypeId = RenewalDealRecordType.Id__c;   // Sets the Record Type ID to be "Renewal Deal"
         newOpp.Previous_Opportunity__c = o.Id;
         Integer numMonths = Integer.valueOf(newOpp.License_Term_in_Months__c);
         newopp.LeadSource = 'Existing Customer';
         newopp.ForecastCategoryName = 'Pipeline';
         newopp.Project_Country__c = o.Project_Country__c;
         newopp.Project_Region__c = o.Project_Region__c;
         newopp.Type = o.Type;
         newopp.Deployment_Option__c = o.Deployment_Option__c;
         OppTypes.put(o.Id,o.Type);
         newopp.Opportunity_Type__c = o.Opportunity_Type__c;
         newopp.Deal_Type__c = 'Renewal - '+ o.Type;
         newopp.Primary_Contact__c = o.Primary_Contact__c;
         newopp.Secondary_Partner__c = o.Secondary_Partner__c;
         newopp.Partner_Involved__c = o.Partner_Involved__c;
         System.debug('+++ OPP CLOSE DATE: ' + newopp.Id + ' :: ' + newopp.CloseDate.format());
         newOpp.CloseDate = newOpp.CloseDate.addMonths(numMonths);
           //newopp.CloseDate = o.End_Date__c;
         ClonedOpps.add(newOpp);
      }  // end for Opportunity

      List<String> CreatedOppIds = new List<String>();
      if (ClonedOpps.size() > 0) {
         Database.SaveResult[] srList = Database.insert(ClonedOpps, true);
         for (Database.SaveResult sr : srList) {
            if (sr.isSuccess()) {
               CreatedOppIds.add(sr.GetId());
               System.debug('++++ New Opp Id: ' + sr.GetId());
            }
            else { 
               for(Database.Error err : sr.getErrors()) {
                  System.debug('The following error has occurred.');                    
                  System.debug(err.getStatusCode() + ': ' + err.getMessage());
                  System.debug('Account fields that affected this error: ' + err.getFields());
               }
            }   // end if/else
         }      // end for srList
      }
      
      // Create a map to link back old Opportunity Products
      for (Opportunity o : [SELECT Id,Type,Previous_Opportunity__c FROM Opportunity WHERE Id=:CreatedOppIds]) {
         ClonedOppMap.put(o.Previous_Opportunity__c, o.Id);
      }
      
      // SObject "clone()" method doesn't copy Line Items, so we need to do it by hand
      List<OpportunityLineItem> ClonedLineItems = new List<OpportunityLineItem>();
      for (OpportunityLineItem oli : [SELECT Id,Product2.Family,PricebookEntryId,OpportunityId,Discount,ListPrice,Quantity,UnitPrice,CurrencyIsoCode,
                                      TotalPrice FROM OpportunityLineItem WHERE OpportunityId =: OppIdsToClone]) {
         String newOppId = ClonedOppMap.get(oli.OpportunityId);
         String oldOppType = OppTypes.get(oli.OpportunityId);
         Boolean addLineItem = false;
         
         if      (oldOppType == 'Subscription' && oli.Product2.Family == 'Subscription License') { addLineItem = true; }
         else if (oldOppType == 'Perpetual' && oli.Product2.Family == 'Perpetual Maintenance and Support') { addLineItem = true; }
         
         if (addLineItem) {   // Add Item if Subscription or Perpetual
            OpportunityLineItem new_oli = new OpportunityLineItem(
               OpportunityId = newOppId, 
               PricebookEntryId = oli.PricebookEntryId,
               Discount = oli.Discount,
               Quantity = oli.Quantity,
               UnitPrice = oli.UnitPrice
            );
            ClonedLineItems.add(new_oli);
         }   // end add item
      }  // end for OpportunityLineItem
      
      if (ClonedLineItems.size() > 0) { insert ClonedLineItems; }
   }

}