src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>FSR_Not_Required_On_Opp__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if there will not be an FSR on the opportunity</description>
        <inlineHelpText>Check this box if there will not be an FSR on the opportunity</inlineHelpText>
        <label>FSR Not Required On Opp</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>ISR_Not_Required_On_Opp__c</fullName>
        <defaultValue>false</defaultValue>
        <description>Check this box if there will not be an ISR on the opportunity</description>
        <inlineHelpText>Check this box if there will not be an ISR on the opportunity</inlineHelpText>
        <label>ISR Not Required On Opp</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Primary_Competitor_Strengths__c</fullName>
        <label>Primary Competitor Strengths</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Primary_Competitor_Weaknesses__c</fullName>
        <label>Primary Competitor Weaknesses</label>
        <length>32768</length>
        <type>LongTextArea</type>
    </fields>
    <fields>
        <fullName>Primary_Competitor__c</fullName>
        <label>Primary Competitor</label>
        <picklist>
            <picklistValues>
                <fullName>AppNeta/Traceview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Aternity</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BlueStripe</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>BMC Software</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>CA Technologies/Wily</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Compuware/dynaTrace</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Correlsense</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Crittercism</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ExtraHop</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>HP/Openview</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>IBM/ITCAM</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Keynote</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Loggly</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>ManageEngine</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Microsoft/Avicode</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Nastel</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>New Relic</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>None</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Opnet Technologies</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Optier</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Oracle</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Other</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Precise</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Quest Software/Foglight</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Ruxit</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Smartbear/Lucierna</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Solarwinds/Confio</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>Splunk</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>SumoLogic</fullName>
            </picklistValues>
            <sorted>true</sorted>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <recordTypes>
        <fullName>Services</fullName>
        <active>true</active>
        <label>Services</label>
    </recordTypes>
</CustomObject>

src/classes/JSButton_Test.cls
@isTest (seeAllData=true)
private class JSButton_Test {

    @isTest static void createVouchersTest() {
    User u1 = [SELECT Id FROM User WHERE Alias='dmoli'];
        
        //Run As U1
    System.RunAs(u1){

    
        Account a = TestClassUtility.createAccount();
    insert a;

    Id oppTrainingRecordType =
      Schema.SObjectType.Opportunity.getRecordTypeInfosByName().get(
        'Training and Services').getRecordTypeId();
    Opportunity o = TestClassUtility.createOpportunity(a);
    o.RecordTypeId = oppTrainingRecordType;
    insert o;

    Product2 p = TestClassUtility.createProduct();
    p.ProductCode = 'ENB-TRU-01-TRNG';
    p.Name = 'Training Units';
    insert p;

    Pricebook2 pb = [Select Id
                     From Pricebook2 Where IsStandard = True
                     limit 1];

    PricebookEntry pbe = TestClassUtility.createPricebookEntry(pb, p);
    insert pbe;

    Test.startTest();

    String result = JSButtonManagement.createVouchers('00O000000000000', '09/01/2017');
    system.assert(result == 'Invalid Opportunity Id');

    result = JSButtonManagement.createVouchers(o.Id, '09/01/2017');
    system.assert(
      result == 'This Opportunity is not in \'W10 - Closed/Won\' status.');

    o.StageName = 'W10 - Closed/Won';
    o.FSR_Not_Required_On_Opp__c = true;
    o.ISR_Not_Required_On_Opp__c = true;
    o.Primary_Competitor__c = 'New Relic';
    o.Primary_Competitor_Strengths__c = 'Strength1';
    o.Primary_Competitor_Weaknesses__c = 'Weakness1';
    update o;

    result = JSButtonManagement.createVouchers(o.Id, '09/01/2017');
    system.assert(result == 'No Training Products exist on this Opportunity');

    OpportunityLineItem oli =
      TestClassUtility.createOpportunityLineItem(o, pbe);
    insert oli;
    result = JSButtonManagement.createVouchers(o.Id, '09/01/2017');
    system.assert(result == '/' + o.Id);
    }
    Test.stopTest();
    }
}