src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>DR_Address__c</fullName>
        <description>Address at which the prospect resides. Populated when the company is not found in the D&amp;B search.</description>
        <label>DR Address</label>
        <type>TextArea</type>
    </fields>
    <fields>
        <fullName>DR_City__c</fullName>
        <description>City in which the prospect resides. Populated when the company is not found in the D&amp;B search.</description>
        <label>DR City</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DR_Company_Name__c</fullName>
        <inlineHelpText>Value entered by partner after being unable to find the company from the D&amp;B lookup</inlineHelpText>
        <label>DR Company Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DR_Contact_First_Name__c</fullName>
        <description>First Name of customer primary contact. Populated when the company is not found in the D&amp;B search.</description>
        <label>DR Contact First Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DR_Contact_Last_Name__c</fullName>
        <description>Last Name of customer primary contact. Populated when the company is not found in the D&amp;B search.</description>
        <label>DR Contact Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DR_Contact_Phone__c</fullName>
        <description>Phone of customer primary contact. Populated when the company is not found in the D&amp;B search.</description>
        <label>DR Contact Phone</label>
        <type>Phone</type>
    </fields>
    <fields>
        <fullName>DR_Country__c</fullName>
        <description>Country in which the prospect resides. Populated when the company is not found in the D&amp;B search</description>
        <label>DR Country</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DR_Email_Address__c</fullName>
        <description>Email address of customer primary contact. Populated when the company is not found in the D&amp;B search.</description>
        <label>DR Email Address</label>
        <type>Email</type>
    </fields>
    <fields>
        <fullName>DR_State_Province__c</fullName>
        <description>State/Province in which the prospect resides. Populated when the company is not found in the D&amp;B search.</description>
        <label>DR State/Province</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DR_Title__c</fullName>
        <description>Title of customer primary contact. Populated when the company is not found in the D&amp;B search.</description>
        <label>DR Title</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DR_Zip__c</fullName>
        <description>Zip at which the prospect resides. Populated when the company is not found in the D&amp;B search.</description>
        <label>DR Zip</label>
        <length>50</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Primary_Contact__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Primary Contact</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>Opportunities</relationshipLabel>
        <relationshipName>Opportunities</relationshipName>
        <type>Lookup</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CreateAccountContactExtension.cls
/*
 ** Apex class to be used by CreateAccountContact VF to create Account and Contact, and
 ** relate them to the current opportunity.
 
 ** Author: Eric He
 */
public with sharing class CreateAccountContactExtension 
{
    public Account RelatedAccount { get; set; }
    public Contact PrimaryContact { get; set; }
    public String OppId { get; private set; }
    public Boolean IsSuccess { get; private set; }

    private Opportunity deal;

    public CreateAccountContactExtension(ApexPages.StandardController stdController) 
    {
        OppId = stdController.getId();
        deal = [select DR_Company_Name__c, DR_Address__c, DR_City__c, DR_State_Province__c, DR_Zip__c, DR_Country__c, 
                    DR_Contact_First_Name__c, DR_Contact_Last_Name__c, DR_Title__c, DR_Contact_Phone__c, DR_Email_Address__c, CreatedById
                from Opportunity where Id = :OppId];        
        
        RelatedAccount = new Account(Name = deal.DR_Company_Name__c,
                                     BillingStreet = deal.DR_Address__c,
                                     BillingCity = deal.DR_City__c,
                                     BillingState = deal.DR_State_Province__c,
                                     BillingPostalCode = deal.DR_Zip__c,
                                     BillingCountry = deal.DR_Country__c,
                                     OwnerId = UserInfo.getUserId());

        PrimaryContact = new Contact(FirstName = deal.DR_Contact_First_Name__c,
                                     LastName = deal.DR_Contact_Last_Name__c,
                                     Title = deal.DR_Title__c,
                                     Phone = deal.DR_Contact_Phone__c,
                                     Email = deal.DR_Email_Address__c,
                                     OwnerId = deal.CreatedById);

        IsSuccess = false;
    }

    public void save()
    {        
        try
        {
            upsert RelatedAccount;

            PrimaryContact.AccountId = RelatedAccount.Id;
            upsert PrimaryContact;

            deal.AccountId = RelatedAccount.Id;
            deal.Primary_Contact__c = PrimaryContact.Id;
            deal.OwnerId = RelatedAccount.OwnerId;
            update deal;
            
            IsSuccess = true;
        }
        catch(Exception ex)
        {            
            ApexPages.addMessages(ex);
        }
    }
}