src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>DR_Company_Name__c</fullName>
        <inlineHelpText>Value entered by partner after being unable to find the company from the D&amp;B lookup</inlineHelpText>
        <label>DR Company Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DR_Contact_Last_Name__c</fullName>
        <description>Last Name of customer primary contact. Populated when the company is not found in the D&amp;B search.</description>
        <label>DR Contact Last Name</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>DR_Email_Address__c</fullName>
        <description>Email address of customer primary contact. Populated when the company is not found in the D&amp;B search.</description>
        <label>DR Email Address</label>
        <type>Email</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/classes/CreateAccountContactExtensionTest.cls
@isTest
public class CreateAccountContactExtensionTest {

    @isTest(SeeAllData=true) static void testCreateAccountContactExtension(){
        Opportunity oppt = [select Id from Opportunity where DR_Contact_Last_Name__c != null and DR_Email_Address__c != null and DR_Company_Name__c != null limit 1];
        CreateAccountContactExtension controller = new CreateAccountContactExtension(new ApexPages.StandardController(oppt));
        controller.RelatedAccount.Name = 'test';
        controller.save();
    }
}