src/objects/Opportunity.object
<CustomObject>
    <fields>
        <fullName>Partner_Margin_Discount__c</fullName>
        <formula>SyncedQuote.Partner_Margin_Discount__c</formula>
        <formulaTreatBlanksAs>BlankAsZero</formulaTreatBlanksAs>
        <label>Partner Margin Discount %</label>
        <precision>18</precision>
        <scale>2</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>Private</sharingModel>
</CustomObject>

src/objects/Product2.object
<CustomObject>
    <fields>
        <fullName>Monthly__c</fullName>
        <defaultValue>false</defaultValue>
        <label>Monthly</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Partner_Margin_Applied__c</fullName>
        <description>Determines whether the partner margin is applied to the quote line item</description>
        <label>Partner Margin Applied</label>
        <picklist>
            <picklistValues>
                <fullName>True</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>False</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
</CustomObject>

src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>Federal_Distributor_Margin__c</fullName>
        <label>Federal Distributor Margin</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>One_Time_Discount__c</fullName>
        <description>This is the one time discount price based on the line item</description>
        <label>One Time Discount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Partner_Margin_Discount__c</fullName>
        <label>Partner Margin Discount %</label>
        <precision>13</precision>
        <scale>10</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote_Discount_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>This is the custom setting for quote discounts.</description>
    <fields>
        <fullName>Federal_Distributor_Discount_Product__c</fullName>
        <label>Federal Distributor Discount Product</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>One_Time_Discount_Product__c</fullName>
        <description>This is the name of the product for the one time discount.</description>
        <label>One Time Discount Product</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Margin_Discount_Product__c</fullName>
        <description>This is the product name for the partner margin discount.</description>
        <label>Partner Margin Discount Product</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Quote Discount Settings</label>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>One_Time_Discount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>One Time Discount %</label>
        <precision>11</precision>
        <scale>8</scale>
        <type>Percent</type>
    </fields>
    <fields>
        <fullName>Partner_Margin_Applied__c</fullName>
        <label>Partner Margin Applied</label>
        <picklist>
            <picklistValues>
                <fullName>Yes</fullName>
            </picklistValues>
            <picklistValues>
                <fullName>No</fullName>
            </picklistValues>
        </picklist>
        <type>Picklist</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QuoteTrigger_Test.cls
@isTest(seeAllData=true)
private class QuoteTrigger_Test {
    @isTest static void testQuote() {
    Account acc = TestUtil.createAccounts(1, true)[0];
    Contact con =  TestUtil.createContacts(1, acc.Id, true)[0];
    Opportunity opp = TestUtil.createOpps(1, acc.Id, true)[0];
    Quote q = TestUtil.createQuotes(1, con.Id, opp.Id, false)[0];

    Pricebook2 standardPB = [SELECT Id
                             FROM Pricebook2
                             WHERE isStandard = true];

    Pricebook2 pb = new Pricebook2(
      Name = 'Test Price Book',
      Description = ' Price Book',
      IsActive = true);
    insert pb;

    Quote_Discount_Settings__c quoteSetting =
      Quote_Discount_Settings__c.getInstance();

    if (quoteSetting == null) {
      insert new Quote_Discount_Settings__c(
        One_Time_Discount_Product__c = 'One Time Discount Product',
        Partner_Margin_Discount_Product__c = 'Partner Margin Discount Product');
    }

    List<Product2> prodList = new List<Product2>();
    Product2 prod = new Product2(
      Name = quoteSetting.One_Time_Discount_Product__c,
      Family = 'Renewal',
      IsActive = true,
      Partner_Margin_Applied__c = 'True',
      Monthly__c = true);
    prodList.add(prod);

    Product2 supportProd = new Product2(
      Name = quoteSetting.Partner_Margin_Discount_Product__c,
      Family = 'Renewal',
      IsActive = true);
    prodList.add(supportProd);
    
    Product2 supportProd3 = new Product2(
      Name = quoteSetting.One_Time_Discount_Product__c,
      Family = 'Renewal',
      IsActive = true);
    prodList.add(supportProd3);
    
    Product2 supportProd4 = new Product2(
      Name = quoteSetting.Federal_Distributor_Discount_Product__c,
      Family = 'Renewal',
      IsActive = true);
    prodList.add(supportProd4);

    Product2 supportProd2 = new Product2(
      Name = 'Test Prod 3',
      Family = 'Renewal',
      IsActive = true);
    prodList.add(supportProd2);
    insert prodList;

    List<PricebookEntry> entryList = new List<PricebookEntry>();
    PricebookEntry standardPrice = new PricebookEntry(
      Pricebook2Id = standardPB.Id,
      Product2Id = prod.Id,
      UnitPrice = 10000,
      IsActive = true,
      UseStandardPrice = false);
    entryList.add(standardPrice);

    PricebookEntry standardPriceSupport = new PricebookEntry(
      Pricebook2Id = standardPB.Id,
      Product2Id = supportProd.Id,
      UnitPrice = 10000,
      IsActive = true,
      UseStandardPrice = false);
    entryList.add(standardPriceSupport);

    PricebookEntry standardPriceSupport2 = new PricebookEntry(
      Pricebook2Id = standardPB.Id,
      Product2Id = supportProd2.Id,
      UnitPrice = 10000,
      IsActive = true,
      UseStandardPrice = false);
    entryList.add(standardPriceSupport2);
    insert entryList;

    q.Pricebook2Id = pb.Id;
    q.Partner_Margin_Discount__c = 15;
    q.One_Time_Discount__c = 1000;
    q.Federal_Distributor_Margin__c= 10;
    q.Name = 'Test Quote';
    
    insert q;
    
    List<Quote> qte = new List<Quote>();
    Map<Id, Quote> mapQte = new Map<Id, Quote>();
    
    qte.add(q);
    
    
    QuoteTriggerHandler.afterInsert(qte);

    entryList = new List<PricebookEntry>();
    PricebookEntry pbe = new PricebookEntry(
      Pricebook2Id = pb.Id,
      Product2Id = prod.Id,
      UnitPrice = 10000,
      IsActive = true,
      UseStandardPrice = false);
    entryList.add(pbe);

    PricebookEntry pbe1 = new PricebookEntry(
      Pricebook2Id = pb.Id,
      Product2Id = supportProd.Id,
      UnitPrice = 10000,
      IsActive = true,
      UseStandardPrice = false);
    entryList.add(pbe1);

    PricebookEntry pbe2 = new PricebookEntry(
      Pricebook2Id = pb.Id,
      Product2Id = supportProd2.Id,
      UnitPrice = 10000,
      IsActive = true,
      UseStandardPrice = false);
    insert pbe2;
    insert entryList;

    List<QuoteLineItem> itemList = new List<QuoteLineItem>();
    //QuoteLineItem prodQLI = TestUtil.createQLIs(1, q.Id, pbe.Id, false)[0];
    QuoteLineItem supportQLI = TestUtil.createQLIs(1, q.Id, pbe2.Id, false)[0];
    itemList.add(supportQLI);
    //itemList.add(prodQLI);
    insert itemList;
    
    QuoteLineItemTriggerHandler.afterInsert(itemList);

    //update quote
    q.One_Time_Discount__c = 2500;
    q.Federal_Distributor_Margin__c=0;
    q.Partner_Margin_Discount__c = 20;
    update q;
    
    QuoteTriggerHandler.afterUpdate(qte, mapQte);
    
    
    System.assertEquals(itemList.size(), 1);
    
    }
}