src/objects/Partner_Campaign__c.object
<CustomObject>
    <fields>
        <fullName>Campaign__c</fullName>
        <deleteConstraint>SetNull</deleteConstraint>
        <label>Campaign</label>
        <referenceTo>Campaign</referenceTo>
        <relationshipLabel>Partner Campaigns</relationshipLabel>
        <relationshipName>Partner_Campaigns</relationshipName>
        <type>Lookup</type>
    </fields>
    <fields>
        <fullName>Partner_Region__c</fullName>
        <label>Partner Region</label>
        <length>200</length>
        <type>Text</type>
        <unique>true</unique>
    </fields>
    <label>Partner Campaign</label>
    <nameField>
        <displayFormat>PC-{0000}</displayFormat>
        <label>Partner Campaign Number</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Partner Campaigns</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/PartnerCampaignsController.cls
public class PartnerCampaignsController
{
    public PartnerCampaignsController()
    {
       PartnerCampaigns = [select Id, Campaign__c, Campaign__r.Name, Partner_Region__c from Partner_Campaign__c];
    }
    
    public List<Partner_Campaign__c> PartnerCampaigns {get; set; }
    
    public PageReference CreateNewPartnerCampaign()
    {
        PageReference retPage = new PageReference('/apex/NewEditPartnerCampaign');
        retPage.setRedirect(true);
        return retPage;
    }
}