src/objects/Quote.object
<CustomObject>
    <fields>
        <fullName>One_Time_Discount__c</fullName>
        <description>This is the one time discount price based on the line item</description>
        <label>One Time Discount</label>
        <precision>16</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <fields>
        <fullName>Total_Price_Custom__c</fullName>
        <description>Gross Total Price minus the One Time Discount amount.

Referenced by code inserting Partner Margin SKU.</description>
        <label>Total Price After One Time Discount</label>
        <precision>12</precision>
        <scale>2</scale>
        <type>Currency</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/objects/Quote_Discount_Settings__c.object
<CustomObject>
    <customSettingsType>Hierarchy</customSettingsType>
    <customSettingsVisibility>Protected</customSettingsVisibility>
    <description>This is the custom setting for quote discounts.</description>
    <fields>
        <fullName>Federal_Distributor_Discount_Product__c</fullName>
        <label>Federal Distributor Discount Product</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>One_Time_Discount_Product__c</fullName>
        <description>This is the name of the product for the one time discount.</description>
        <label>One Time Discount Product</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Partner_Margin_Discount_Product__c</fullName>
        <description>This is the product name for the partner margin discount.</description>
        <label>Partner Margin Discount Product</label>
        <length>100</length>
        <type>Text</type>
    </fields>
    <label>Quote Discount Settings</label>
</CustomObject>

src/objects/QuoteLineItem.object
<CustomObject>
    <fields>
        <fullName>One_Time_Discount__c</fullName>
        <defaultValue>0</defaultValue>
        <label>One Time Discount %</label>
        <precision>11</precision>
        <scale>8</scale>
        <type>Percent</type>
    </fields>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

src/classes/QuoteLineItemTriggerHandler.cls
public with sharing class QuoteLineItemTriggerHandler {
    public static Quote_Discount_Settings__c quoteSetting = Quote_Discount_Settings__c.getInstance();

    public static void afterInsert(List<QuoteLineItem> newList) {
        updateQuoteWithDiscounts(newList);
        //updateTotalPriceCustom(newList);
       
    }

    public static void afterUpdate(List<QuoteLineItem> newList, Map<Id, QuoteLineItem> oldMap) {
        updateQuoteWithDiscounts(newList);
        //updateTotalPriceCustom(newList);
    }

    public static void afterDelete(List<QuoteLineItem> oldList) {
        updateQuoteWithDiscounts(oldList);
        //updateTotalPriceCustom(oldList);
    }
    
    /*private static void updateTotalPriceCustom(List<QuoteLineItem> newList) {
      
        Set<Id> quoteLineIdSet = new Set<Id>();
        Map<Id, Double> quoteTotalPriceMap = new Map<Id, Double>();
        List<Quote> quoteToUpdateTotalPriceCustom = new List<Quote>();
        
        for (QuoteLineItem item : newList) {
            if (item.QuoteId != null) {
                quoteLineIdSet.add(item.QuoteId);
            }
        }
        
        System.Debug('Quote TtoalPrice : ' + quoteLineIdSet);
        
        for (AggregateResult r : [SELECT QuoteId, sum(TotalPrice) 
                                       FROM QuoteLineItem
                                      WHERE quoteid IN :quoteLineIdSet
                                        AND PricebookEntry.Name NOT IN(:quoteSetting.Partner_Margin_Discount_Product__c, 
                                                                  :quoteSetting.Federal_Distributor_Discount_Product__c)
                                   group by quoteid]) {
            quoteTotalPriceMap.put((Id)r.get('QuoteId'),(Double)r.get('expr0'));
                                                   
        }
        
        System.Debug('Quote Total Price Map : ' + quoteTotalPriceMap);
        
        for (Quote q : [select Id, Total_Price_Custom__c from Quote where Id IN :quoteLineIdSet]) {
        
            Double totalAmount = quoteTotalPriceMap.get(q.Id);
            q.Total_Price_Custom__c = totalAmount;
            quoteToUpdateTotalPriceCustom.add(q);
        
        }
        
        update quoteToUpdateTotalPriceCustom;
    }*/


    private static void updateQuoteWithDiscounts(List<QuoteLineItem> newList) {
        Map<Id, Quote> quoteToUpdateMap = new Map<Id, Quote>();
        List<QuoteLineItem> itemsToTestList = new List<QuoteLineItem>();
        Set<Id> quoteIdSet = new Set<Id>();

        for (QuoteLineItem item : newList) {
            if (item.QuoteId != null) {
                quoteIdSet.add(item.QuoteId);
            }
        }

        if (quoteSetting != null) {
            for (QuoteLineItem item : [SELECT Id,
                                        QuoteId,
                                        TotalPrice,
                                        PricebookEntryId,
                                        PricebookEntry.Name
                                 FROM QuoteLineItem
                                 WHERE QuoteId IN :quoteIdSet
                                   AND PricebookEntry.Name NOT IN(:quoteSetting.Partner_Margin_Discount_Product__c, 
                                                                  :quoteSetting.Federal_Distributor_Discount_Product__c)]) {
                itemsToTestList.add(item);
            }
        }

        for (QuoteLineItem item : itemsToTestList) {
            if (!quoteToUpdateMap.containsKey(item.QuoteId)) {
                quoteToUpdateMap.put(item.QuoteId, new Quote(Id = item.QuoteId, One_Time_Discount__c = 0));
        // check why setting to 0 fails
            }
        
            if (quoteSetting.One_Time_Discount_Product__c != null &&
                item.PricebookEntry.Name == quoteSetting.One_Time_Discount_Product__c) {
                quoteToUpdateMap.get(item.QuoteId).One_Time_Discount__c = item.TotalPrice < 0 ? -(item.TotalPrice) : item.TotalPrice;
            }
            if (quoteSetting.Partner_Margin_Discount_Product__c == null ||
                item.PricebookEntry.Name != quoteSetting.Partner_Margin_Discount_Product__c) {
                if (quoteToUpdateMap.get(item.QuoteId).Total_Price_Custom__c == null) {
                    quoteToUpdateMap.get(item.QuoteId).Total_Price_Custom__c = 0;
                }
                quoteToUpdateMap.get(item.QuoteId).Total_Price_Custom__c += item.TotalPrice;
            }
        }
        System.debug('quotetoUpdateMap : ' + quoteToUpdateMap);
        System.debug('quotetoUpdateMap size :'+ quoteToUpdateMap.size());
        if (!quoteToUpdateMap.isEmpty()) {
            update quoteToUpdateMap.values();
        }
    }
}