src/objects/Territory_AppD__c.object
<CustomObject>
    <description>Used to manage lead/account routing.</description>
    <fields>
        <fullName>Active__c</fullName>
        <defaultValue>true</defaultValue>
        <label>Active</label>
        <type>Checkbox</type>
    </fields>
    <fields>
        <fullName>Effective_Date__c</fullName>
        <label>Effective Date</label>
        <type>Date</type>
    </fields>
    <label>Territory</label>
    <nameField>
        <label>Territory Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Territories</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

src/classes/ActiveTerritories.cls
global class ActiveTerritories implements Schedulable
{
    global void execute(SchedulableContext ctx)
    {
        List<Territory_AppD__c> inactiveTerritories = [select Id, Active__c, Effective_Date__c from Territory_AppD__c where Active__c = false and Effective_Date__c <= :Date.today()];
        for(Territory_AppD__c inactiveTerritory : inactiveTerritories)
        {
            inactiveTerritory.Active__c = true;
        }
        database.update(inactiveTerritories, false);
    }
}